.ig
. manual page for NEW and IMPROVED linux top
.
. Copyright (c) 2002-2026 Jim Warner <james.warner@comcast.net
.
. This file may be copied under the terms of the GNU Public License.
..
.\"  Setup ////////////////////////////////////////////////////////////////
.\"                      Commonly used strings (for consistency) ----------
.\"                           - our em-dashes
.ds Em \ \-\-\ 
.ds EM \fB\ \-\-\ \fP
.\"                           - our program name (makes great grammar)
.ds We top
.ds WE \fBtop\fP
.\"                           - other misc strs for consistent usage
.ds F \fI关闭\fP
.ds O \fI开启\fP
.
.ds AK 星号 ("*")
.ds AM 备用显示模式
.ds AS 辅助存储器
.ds CF 配置文件
.ds CG "当前" 窗口/字段组
.ds CI 交互式命令
.ds CO 命令行选项
.ds CT 切换命令
.ds CW "当前" 窗口
.ds FG 字段组
.ds FM 全屏模式
.ds KA 方向键
.ds KS 滚动键
.ds MP 物理内存
.ds MS 交换文件
.ds MV 虚拟内存
.ds NT \fB附注\fP：
.ds PU CPU
.ds Pu CPU
.ds SA 概览区
.ds TA 任务区
.ds TD 任务显示
.ds TT \fB进程\fP 或 \fB线程\fP
.ds TW 任务窗口
.\"                      Reference to the various widths/sizes ------------
.\"                           - the max screen width limit
.ds WX 512
.\"                           - the header width w/ all fields
.ds WF 大约 580
.\"                           - pid monitoring limit
.\"                      Xref's that depend on/mention other stuff --------
.ds Xa 参见
.ds XC 参见
.ds Xc 参见
.ds XT 参见主题
.ds Xt 参见主题
.ds XX 参见 "综述，Linux 内存类型" 以了解更多细节
.ds ZX 访问 smaps 值的开销比访问其他内存统计信息高 10 倍，并且访问其他用户的数据需要 root 权限
.
.\" Document /////////////////////////////////////////////////////////////
.\" ----------------------------------------------------------------------
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.TH TOP 1 2025\-03\-13 procps\-ng 
.\" ----------------------------------------------------------------------
.nh

.\" ----------------------------------------------------------------------
.SH 名称
.\" ----------------------------------------------------------------------
top \- 显示 Linux 进程

.\" ----------------------------------------------------------------------
.SH 概述
.\" ----------------------------------------------------------------------
\*(WE [\fI选项\fP .\|.\|.]

.\" ----------------------------------------------------------------------
.SH 描述
.\" ----------------------------------------------------------------------
\*(WE 程序用于查看系统的动态的、实时的运行状态。它可以显示 \fB系统\fP 概览信息以及当前由 Linux 内核管理的 \*(TT
列表。系统概览信息的类型和显示的进程信息的类型、顺序和大小都是用户可配置的，并且该配置可以在重新启动程序后保持不变。

本程序为进程操作提供了有限的交互界面，并为个人配置提供了功能更广泛的界面 \*(Em 涵盖了其操作的各个方面。虽然本文档中使用的名字是
\*(WE，但是您可以随意给本程序起一个新的名称。这个新名称（可能是别名）将显示在 \*(We 的显示区域，并将在读取和写入\*(CF时使用。

.\" ----------------------------------------------------------------------
.SH 综述
.\" ----------------------------------------------------------------------
.\" ......................................................................
.SS 文档
.\" ----------------------------------------------------------------------
剩余部分的目录

.nf
    综述
       操作
       Linux 内存类型
    1. 命令行选项
    2. 概览显示
       a. 上线时间和平均负载
       b. 任务和 CPU 状态
       c. 内存使用量
    3. 字段 / 列显示
       a. 字段描述
       b. 管理字段
    4. 交互式命令
       a. 全局命令
       b. 概览区命令
       c. 任务区命令
          1. 外观
          2. 内容
          3. 大小
          4. 排序
       d. 底部窗口命令
       e. 颜色映射
    5. 备用显示功能
       a. 窗口综述
       b. 窗口命令
       c. 滚动窗口
       d. 在窗口中查找
       e. 在窗口中筛选
    6. 文件
       a. 个人配置文件
       b. 添加检视条目
       c. 系统配置文件
       d. 系统限制文件
    7. 环境变量
    8. 傻瓜技巧集锦
       a. 内核魔术
       b. 跳动窗口
       c. 大鸟窗口
       d. 峰回路转
    9. 错误, 10. 参见
.fi

.\" ......................................................................
.SS 操作
.\" ----------------------------------------------------------------------
操作 \*(We 时，最重要的两个键是帮助 (h 或 ?) 键和退出 ("q") 键。或者，完成工作后您可以简单地使用传统的中断键 (^C)。

第一次启动时，您将在 \*(We 主屏幕上看到这些传统元素：1) 概览区；2) 字段/列标题行；3)
任务区。各个部分都将在接下来的章节中进行探讨。概览区和列标题行之间还有一个输入/消息行，该行无需进一步解释。

\*(We 的主屏幕 \fI通常\fP 非常适应 X\-Windows 下终端尺寸的变化。其他 \*(We
屏幕可能不太适应，特别是那些带有静态文本的屏幕。然而，这最终取决于您具体使用的窗口管理器和终端模拟器。有时它们对终端大小和当前内容的结论可能与
\*(We 的结论不同，后者始终基于操作系统调用返回的结果。

在任何调整大小操作之后，如果 \*(We
屏幕损坏、显示不完整或混乱，只需键入标点符号或光标移动键等无害的内容，通常就能恢复。在极端情况下，以下序列几乎肯定能恢复：
.nf
       \fI键/命令  目标 \fP
       ^Z       \fB挂起\fP \*(We
       fg       \fB恢复\fP \*(We
       <左>     强制 \fB重新绘制\fP 屏幕（如有需要）
.fi

但如果显示仍然有问题，您还可以尝试加一个步骤。将此命令插入到 \*(We 挂起之后、恢复之前。
.nf
       \fI键/命令  目标 \fP
       reset    恢复您的 \fB终端设置\fP
.fi

\*(NT\*(We 的输出宽度的限制是 \*(WX 个位置。如果无法做到，显示所有字段需要\*(WF
个字符。所有剩余的输出宽度将被分配给可见的可变宽度字段。这些可变宽度列，例如 "命令 (COMMAND)" 列，在主题 3a. 字段描述
中进行了说明。实际输出宽度也可能受到 \-w 选项的影响，这在主题 1. 命令行选项 中进行了讨论。

最后，\*(We 的一些屏幕或功能需要使用光标移动键，例如标准\*(KA加上 Home、End、PgUp 和 PgDn
键。如果您的终端或模拟器不提供这些键，则可以使用以下组合键作为替代方案：
.nf
      \fI 键       等价的键 \fP
       左       alt +\fB h \fP
       下       alt +\fB j \fP
       上       alt +\fB k \fP
       右       alt +\fB l \fP
       Home     alt + ctrl +\fB h \fP
       PgDn     alt + ctrl +\fB j \fP
       PgUp     alt + ctrl +\fB k \fP
       End      alt + ctrl +\fB l \fP
.fi

\fB上\fP 和 \fB下\fP \*(KA在程序提示输入一行内容，并按 <Enter>
键结束时，具有特殊的含义。这些键或其别名可用于检索以前的输入行，然后可以对其进行编辑和重新输入。还有四个键可以用于行输入。
.nf
      \fI 键       特殊含义 \fP
       上       调出 \fB更旧的\fP 字符串进行重新编辑
       下       调出 \fB更新的\fP 字符串或者 \fB清除\fP 整行
       Insert   在 \fB插入\fP 和 \fB覆盖\fP 模式间切换
       Delete   \fB删除\fP 光标处的字符，其他字符左移
       Home     跳到输入行的 \fB开头\fP
       End      跳到输入行的 \fB末尾\fP
.fi

.\" ......................................................................
.SS "Linux 内存类型"
.\" ----------------------------------------------------------------------
就我们的目的而言，内存分为三种类型，其中一种是可选的。第一种是\*(MP，一种有限的资源，代码和数据被执行或引用时必须位于其中。接下来是可选的\*(MS，可以在对\*(MP的需求过高时保存已修改的（脏的）内存，并在稍后取回。最后我们有\*(MV，一种近乎无限的资源，服务于以下目标：

.nf
   1. 抽象，不受物理内存地址的束缚和大小的限制
   2. 隔离，每个进程都在独立的地址空间
   3. 共享，单一的映射可满足多个需求
   4. 灵活，可以为文件分配虚拟地址
.fi

无论内存属于哪种类型，所有内存都以页（通常为 4096 字节）的形式进行管理，但在 \*(We 中默认以 KiB (kibibyte) 为单位表示。主题
"2c. 内存使用量" 中讨论的内存指的是整个系统的\*(MP和\*(MS。主题 "3. 字段 / 列显示"
中讨论的内存包含所有三种内存类型，但是是针对单独的进程。

对于每个这样的进程，每个内存页都属于下表中的一个象限。\*(MP和\*(MV可以包括四个中的任何一个，而\*(MS只包括 #1 到 #3。象限 #4
中的内存在修改后，是它自己的专用\*(MS。

.nf
                                 \fB私有\fP | \fB共享\fP
                          \fB1\fP           |          \fB2\fP
     \fB匿名\fP       . 栈                  |
                . malloc()            |
                . brk()/sbrk()        | . POSIX shm*
                . mmap(私有, 匿名)    | . mmap(共享, 匿名)
               \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
                . mmap(私有, fd)      | . mmap(共享, fd)
   \fB基于文件\fP     . 程序/共享库         |
                          \fB3\fP           |          \fB4\fP
.fi

以下内容可能有助于解释进程级别的各种内存值，它们可以显示为可调节单位的字段，并在主题 "3a. 字段描述" 中进行了讨论。

.nf
   %MEM \- 就是 "驻留" 除以总\*(MP
   代码 \- (CODE) 象限 \fB3\fP 的 "程序" 部分
   数据 \- (DATA) "虚拟" 的象限 \fB1\fP 的全部，加上
          象限 \fB3\fP 中的显式的基于文件的 mmap 页
   驻留 \-  (RES) 所有占据\*(MP的东西，从
          Linux\-4.5 开始，是以下三个字段的和：
          RSan \- 象限 \fB1\fP 的页面，包括所有曾经属于象限 \fB3\fP 但被修改的页面
          RSfd \- 象限 \fB3\fP 和象限 \fB4\fP 的页面
          RSsh \- 象限 \fB2\fP 的页面
   RSlk \- "驻留" 的子集，是其中不可换出的部分（任何象限）
   共享 \-  (SHR) "驻留" 的子集（不包括 \fB1\fP，包括 \fB2\fP 和 \fB4\fP 的全部，
          和 \fB3\fP 的一部分）
   交换 \- (SWAP) 可能是除 \fB4\fP 之外的任何象限
   已用 \- (USED) 就是 "驻留" 和 "交换" 的和
   虚拟 \- (VIRT) 所有正在使用的和/或被保留的内存（所有象限）
.fi

\*(NT虽然程序映像和共享库被认为是进程的 \fI私有\fP 内存，但内核会将它们计入 \fI共享\fP (SHR)。

.\" ----------------------------------------------------------------------
.SH "1. 命令行选项"
.\" ----------------------------------------------------------------------
长选项的必选 \fI参数\fP 对于短选项也是必选的。

虽然不是必需的，但两种形式的选项都可以使用等号，并且允许在 "=" 之前和/或之后使用空格。

.TP  3
\-\fBA\fP, \fB\-\-apply\-defaults\fP
使用编译时的默认值运行 \*(We，忽略除 /etc/toprc 之外的所有配置文件。指定此选项时，它必须是命令行里唯一的选项。

.TP  3
\-\fBb\fP, \fB\-\-batch\fP
以批处理模式启动 \*(We，这在需要将 \*(We 的输出发送到其他程序或发送到文件时很有用。在此模式下，\*(We
不会接受输入，并将持续运行，直到达到您使用 "\-n" \*(CO设置的迭代限制，或被杀死。

.TP  3
\-\fBc\fP, \fB\-\-cmdline\-toggle\fP
启动 \*(We 并将上次记住的 "c" 状态反转。因此，如果 \*(We 上次显示命令行，则这次显示程序名称，反之亦然。\*(XC\*(CI "c"
以获取更多信息。

.TP  3
\-\fBd\fP, \fB\-\-delay\fP = \fI秒\fP [\fI.分秒\fP]
指定屏幕更新之间的延迟，并覆盖个人\*(CF或启动时的默认值中的相应值。之后可以使用\*(CI "d" 或 "s" 进行更改。

秒数允许使用小数，但不允许使用负数。然而，在所有情况下，如果 \*(We 在安全模式下运行，则禁止此类更改，root 除外（除非使用了 "s"
\*(CO）。有关安全模式的其他信息，\*(Xt 6d. 系统限制文件。

.TP  3
\-\fBE\fP, \fB\-\-scale\-summary\-mem\fP = \fIk\fP | \fIm\fP | \fIg\fP | \fIt\fP | \fIp\fP | \fIe\fP
指示 \*(We 将\*(SA的内存单位强制设定为：
.nf
   k \- kibibytes
   m \- mebibytes
   g \- gibibytes
   t \- tebibytes
   p \- pebibytes
   e \- exbibytes
.fi

之后可以使用\*(CT "E" 更改。

.TP  3
\-\fBe\fP, \fB\-\-scale\-task\-mem\fP = \fIk\fP | \fIm\fP | \fIg\fP | \fIt\fP | \fIp\fP
指示 \*(We 将\*(TA的内存单位强制设定为：
.nf
   k \- kibibytes
   m \- mebibytes
   g \- gibibytes
   t \- tebibytes
   p \- pebibytes
.fi

之后可以使用\*(CT "e" 更改。

.TP  3
\-\fBH\fP, \fB\-\-threads\-show\fP
指示 \*(We 显示各个线程。如果没有这个\*(CO，则会显示每个进程中所有线程的总和。之后可以使用\*(CI "H" 更改。

.TP  3
\-\fBh\fP, \fB\-\-help\fP
显示用法帮助文本，然后退出。

.TP  3
\-\fBi\fP, \fB\-\-idle\-toggle\fP
启动 \*(We 并将上次记住的 "i" 状态反转。当此开关为 \*F 时，自上次更新以来未使用任何 \*(PU
的任务将不会显示。有关此开关的其他信息\*(Xt 4c. 任务区命令，大小。

.TP  3
\-\fBn\fP, \fB\-\-iterations\fP = \fI数字\fP
指定 \*(We 在退出前执行的最大迭代次数，即生成的帧的个数。

.TP  3
\-\fBO\fP, \fB\-\-list\-fields\fP
此选项可以用作下面的 \-o 选项的某种形式的帮助。它将使 \*(We 在单独的行中分别打印每个可用的字段名称，然后退出。这些名称可以通过 NLS
(National Language Support) 进行翻译。

.TP  3
\-\fBo\fP, \fB\-\-sort\-override\fP = \fI字段名称\fP
指定对任务进行排序的字段的名称，与配置文件中存在的内容无关。您可以在字段名称前面添加 "+" 或 "\-" 以覆盖排序方向。前导 "+"
将强制从高到低排序，而 "\-" 将确保从低到高排序。

该选项的存在主要是为了支持自动化/脚本化的批处理模式操作。

.TP  3
\-\fBp\fP, \fB\-\-pid\fP = \fIPID列表\fP（格式为：\fI1\fP,\fI2\fP,\fI3\fP, .\|.\|. 或
\-p\fI1\fP \-p\fI2\fP \-p\fI3\fP .\|.\|.）仅监视具有指定进程 ID 的进程。然而，当与线程模式 ("H")
同时使用时，也将显示每个被监视的 PID 的线程组（\*(Xa TGID）中的所有进程。

此选项最多可以给出 20 次，或者您可以提供最多包含 20 个 pid 的以逗号分隔的列表。允许混合使用两种方法。

如果 pid 值为 0，视为当 \*(We 程序开始运行后，\*(We 程序本身的进程 ID。

这只是一个命令行选项而已，如果您希望返回正常操作，没有必要退出并重新启动 \*(We \*(Em 只需执行以下命令中的任何一个："="、"u" 或
"U"。

\*(CO "p"、"u" 和 "U" 互斥。

.TP  3
\-\fBS\fP, \fB\-\-accum\-time\-toggle\fP
启动 \*(We 并将上次记住的 "S" 状态反转。当累积时间模式 \*O 时，每个进程列出的 \*(Pu
时间都包括它自身和它的已死亡的子进程所使用的时间。\*(XC\*(CI "S" 以了解有关此模式的更多信息。

.TP  3
\-\fBs\fP, \fB\-\-secure\-mode\fP
启动 \*(We 并强制使用安全模式，即使是 root。此模式可以通过系统\*(CF进行更好的控制（\*(Xt 6. 文件）。

.TP  3
\-\fBU\fP, \fB\-\-filter\-any\-user\fP = \fI用户\fP（格式为：\fI数字\fP 或 \fI名称\fP）
仅显示用户 ID 或用户名与给定的 ID 或名称匹配的进程。此选项匹配 \fI任意类型\fP 的用户（即 \fI真实\fP、\fI有效\fP、\fI保存\fP 或
\fI文件系统\fP 用户）。

在用户 ID 或名称前面添加感叹号 ("!") 会指示 \*(We 仅显示用户与所指定的用户不匹配的进程。

\*(CO "p"、"U" 和 "u" 互斥。

.TP  3
\-\fBu\fP, \fB\-\-filter\-only\-euser\fP = \fI用户\fP（格式为：\fI数字\fP 或 \fI名称\fP）
仅显示用户 ID 或用户名与给定的 ID 或名称匹配的进程。此选项仅匹配 \fI有效\fP 用户 ID。

在用户 ID 或名称前面添加感叹号 ("!") 会指示 \*(We 仅显示用户与所指定的用户不匹配的进程。

\*(CO "p"、"U" 和 "u" 互斥。

.TP  3
\-\fBV\fP, \fB\-\-version\fP
显示版本信息，然后退出。

.TP  3
\-\fBw\fP, \fB\-\-width\fP [=\fI列数\fP]
在批处理模式下，当不带参数使用时，如果已设置 COLUMNS= 和 LINES= 环境变量，\*(We 将用它们的值格式化输出。否则，宽度将固定为最大
\*(WX 列。带参数使用时，可以减少或增加输出宽度（最大 \*(WX），但行数视为无限制。

在正常显示模式下，当不带参数使用时 \*(We 将 \fI尝试\fP 使用 COLUMNS= 和 LINES=
环境变量（如果已设置）来格式化输出。带参数使用时，输出宽度只能减少，而不能增加。不管是使用环境变量还是使用 \-w 的参数，当 \fI不\fP
在批处理模式下时，永远不会超出实际的终端尺寸。

\*(NT如果不使用这个\*(CO，输出宽度将始终基于调用 \*(We 的终端，无论是否在批处理模式下。

.TP  3
\-\fB1\fP, \fB\-\-single\-cpu\-toggle\fP
启动 \*(We 并将上次记住的\*(SA中的 Cpu 状态显示反转。要么所有 \*(Pu 信息将显示在单行中，要么每个 \*(Pu
将单独显示，具体取决于 NUMA 节点\*(CT ("2") 的状态。

\*(XC\*(CI "1" 和 "2" 以了解更多信息。

.\" ----------------------------------------------------------------------
.SH "2. 概览显示"
.\" ----------------------------------------------------------------------
以下三个区域中的每一个区域均通过一个或多个\*(CI控制。\*(XT 4b. 概览区命令 了解有关这些功能的更多信息。

.\" ......................................................................
.SS "2a. 上线时间和平均负载"
.\" ----------------------------------------------------------------------
该部分由一行组成，其中包含：
.nf
    \fB程序\fP 或 \fB窗口\fP 名称，取决于显示模式
    当前时间和自上次启动以来经过的时间
    用户总数
    最近 1、5 和 15 分钟的系统平均负载
.fi

.\" ......................................................................
.SS "2b. 任务和 CPU 状态"
.\" ----------------------------------------------------------------------
该部分至少由两行组成。在 SMP 环境中，额外的行可以用来显示各个 \*(PU 的状态百分比。

第 1 行显示 \fB任务\fP 或 \fB线程\fP 的总数，具体取决于线程模式切换开关的状态。该总数根据任务状态被进一步细分为：
.nf
    显示的名称      进程状态 ("S")
    \-\-\-\-\-\-\-\-\-\-\-\-    \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
    运行中          R
    睡眠            S + 所有剩下的
    不可中断睡眠    D
    已停止          T + t
    僵尸            Z
.fi

第 2 行显示自上次刷新以来的 \*(PU 状态百分比。

默认情况下，显示以下各个类型的百分比。根据您的内核版本，可能不会显示 \fB丢\fP 字段。
.nf
    \fB用\fP：(us) 运行未调整 nice 值的用户进程的时间
    \fB系\fP：(sy) 运行内核进程的时间
    \fBni\fP：运行调整了 nice 值的用户进程的时间
    \fB闲\fP：(id) 在内核空闲处理函数中花费的时间
    \fB等\fP：(wa) 等待 I/O 完成的时间
    \fB硬\fP：(hi) 处理硬件中断所花费的时间
    \fB软\fP：(si) 处理软件中断所花费的时间
    \fB丢\fP：(st) 虚拟机管理程序从此 vm 中偷取的时间
.fi

除了第一个任务/线程行之外，还有其他 \*(PU 显示模式，可通过 4 路的\*(CT "t" 获得。它们显示由以下元素组成的简短概览：
.nf
               a    b     c    d
    %Cpu(s):  \fB75.0\fP/25.0  \fB100\fP[ .\|.\|. ]

.fi

其中：a) 是 "用户"（用户 + ni）百分比；b) 是 "系统"（系统 + 硬中断 + 软中断 + 客户）百分比；c) 是总百分比；d)
是这些数字的两种可视化图表之一。这些图表还会单独显示 "用户" 和 "系统" 部分。

如果使用了\*(CT "4" 使得每行显示超过两个 cpu，显示将进一步被精简，a) 和 b)
元素会被删除。然而，如果颜色功能启用，这些信息仍然会反映在图表中，如果颜色功能关闭，则用竖线和方块作区分。

\*(XT 4b. 概览区命令 了解关于\*(CT "t" 和 "4" 的更多信息。

.\" ......................................................................
.SS "2c. 内存使用量"
.\" ----------------------------------------------------------------------
该部分由两行组成，可以根据由\*(CI "E" 强制选择的单位，以 kibibyte (KiB) 到 exbibyte (EiB)
为单位表示值。括号里的是 /proc/meminfo 源字段。

第 1 行显示\*(MP，分为：
.nf
    总共           ( MemTotal )
    空闲           ( MemFree )
    已用           ( MemTotal \- MemAvailable )
    缓冲/缓存      ( Buffers + Cached + SReclaimable )
.fi

第 2 行主要显示\*(MV，分为：
.nf
    总共           ( SwapTotal )
    空闲           ( SwapFree )
    已用           ( SwapTotal \- SwapFree )
    可用           ( MemAvailable，这个是\*(MP )
.fi

第 2 行的 \fB可用\fP 指的是在不需要交换的情况下，可用于启动新应用程序的\*(MP。与 \fB空闲\fP 字段不同，它尝试计入很容易回收的页面缓存和内存
slab。它在内核 3.14 上可用，在内核 2.6.27+ 上为模拟得到，否则与 \fB空闲\fP 相同。

在其他内存显示模式中，显示两行简短的概览，其中包含以下元素：
.nf
               a    b          c
    GiB 内存: \fB18.7\fP/15.738   [ .\|.\|. ]
    GiB 交换: \fB 0.0\fP/7.999    [ .\|.\|. ]
.fi

其中：a) 是已用的百分比；b) 是可用的总量；c) 是这些数字的两种可视化图表之一。

在\*(MP的情况下，百分比表示 \fB总共\fP 减去上面提到的估计的 \fB可用\fP。"内存" 图本身被分为 \fB已用\fP 内存的非缓存部分和未计入 \fB可用\fP
内存的所有剩余内存。\*(XT 4b. 概览区命令 和 "m" 命令以获取有关这一特殊的 4 路切换命令的更多信息。

下表可能有助于理解所显示的带有单位的值：
.nf
    KiB = kibibyte = 1024 字节
    MiB = mebibyte = 1024 KiB = 1,048,576 字节
    GiB = gibibyte = 1024 MiB = 1,073,741,824 字节
    TiB = tebibyte = 1024 GiB = 1,099,511,627,776 字节
    PiB = pebibyte = 1024 TiB = 1,125,899,906,842,624 字节
    EiB = exbibyte = 1024 PiB = 1,152,921,504,606,846,976 字节
.fi

.\" ----------------------------------------------------------------------
.SH "3. 字段 / 列"
.\" ----------------------------------------------------------------------
.\" ......................................................................
.SS "3a. 字段描述"
.\" ----------------------------------------------------------------------
下面列出了 \*(We 可用的进程字段（列）。这些字段严格按照 ASCII 字母顺序列出。您可以使用\*(CI
"f"（字段管理）自定义是否显示它们，以及它们的位置。

任何字段都可以被选为排序字段，并且您可以控制它们是从高到低还是从低到高排序。有关排序功能的更多信息，\*(Xt 4c. 任务区命令，排序。

与\*(MP或\*(MV相关的字段提到了 "(KiB)"，这是不带后缀时的默认单位。但是，显示的单位可以是从 KiB 到 PiB。该单位受到\*(CI
"e" 的影响，或者可以通过编译时的选项设定启动时的默认值。

.TP  4
\fB%CPU\fP \*(Em \*(PU 使用量
自上次屏幕更新以来，任务在已用 \*(PU 时间中所占的比例，以占总 \*(PU 时间的百分比表示。

在真正的 SMP 环境中，如果进程是多线程的并且 \*(We 在线程模式下运行，则数字可能会大于 100%。您可以使用\*(CI "H" 开关线程模式。

同样对于多处理器环境，如果 Irix 模式 \*F，\*(We 将在 Solaris 模式下运行，此时任务的 \*(Pu 使用量将除以 \*(PU
总数。您可以使用\*(CI "I" 切换 Irix/Solaris 模式。

\*(NT在森林视图模式 ("V") 下运行且隐藏子进程 ("v") 时，此字段还将包括那些被隐藏的子进程的 \*(PU 时间。\*(XT
4c. 任务区命令 以了解有关切换命令 "V" 和 "v" 的更多信息。

.TP  4
\fB%CUC\fP \*(Em \*(PU 利用率
此字段和下面的 %CUU 相同，除了它的百分比也包括了被收割的子进程。

.TP  4
\fB%CUU\fP \*(Em \*(PU 利用率
任务的总 \*(PU 使用量除以它已运行的时间，以百分比表示。

如果一个进程当前的 \*(PU 使用率较高，则此字段可以帮助确定此情况是否正常。相反，如果进程当前的 \*(PU 使用率较低，%CUU
可能提示它的生命周期中历史上的 CPU 需求较高。

.TP  4
\fB%MEM\fP \*(Em 内存使用量（驻留）
任务当前的驻留内存占可用\*(MP的比例。

\*(XX。

.TP  4
\fBAGID\fP \*(Em 自动组标识符
与进程关联的自动组标识符。此标识符与 CFS 调度器配合使用，可提高交互式桌面性能。

当 /proc/sys/kernel/sched_autogroup_enabled 被设置时，每个新会话都会创建一个新的自动组（\*(Xa
SID）。该会话中所有后续 fork 出的进程都会继承此自动组的成员属性。然后，内核会尝试在这些组之间均衡分配 CPU 周期。因此，具有许多 \*(PU
密集型进程（例如 make \-j）的自动组不会占据仅具有一两个进程的自动组的 CPU 时间。

显示 \-1 时，表示此信息不可用。

.TP  4
\fBAGNI\fP \*(Em 自动组 Nice 值
自动组 nice 值，影响该组中所有进程的调度。负的 nice 值意味着更高的优先级，而正的 nice 值意味着更低的优先级。

.TP  4
\fBCG名称 (CGNAME)\fP \*(Em 控制组名称
进程所属的控制组的名称，或者如果不适用于该进程，则为 "\-"。

只在 cgroup v1 中可用，它通常是 CGROUPS 那节中所描述的控制组完整列表中显示的最后一个条目。和那个字段一样，该字段的宽度也是可变的。

.TP  4
\fBCGROUPS\fP \*(Em 控制组
进程所属的控制组的名称（或列表），或者如果不适用于该进程，则为 "\-"。

控制组用于在安装之后定义的进程组之间分配资源（CPU、内存、网络带宽等）。它可以对这些资源的分配、拒绝、优先级设置、管理和监控进行细粒度控制。

许多不同的 cgroup 层次结构可以同时存在于一个系统上，并且每个层次结构都属于一个或多个子系统。一个子系统代表一种资源。

\*(NTCGROUPS 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX
字符）将分配给它和其他所有可变宽度列。即使如此，这种可变宽度字段仍然可能会被截断。\*(XT 5c. 滚动窗口 以获取关于查看被截断的数据的更多信息。

.TP  4
\fB类 (CLS) \*(Em 调度类 \fP
任务当前的调度策略，可以是以下各值中的一个：
    \fB\-  \fP = 未报告
    \fBTS \fP = SCHED_OTHER
    \fBFF \fP = SCHED_FIFO
    \fBRR \fP = SCHED_RR
    \fBB  \fP = SCHED_BATCH
    \fBISO\fP = SCHED_ISO
    \fBIDL\fP = SCHED_IDLE
    \fBDLN\fP = SCHED_DEADLINE
    \fB?  \fP = 未知的值

.TP  4
\fB代码 (CODE)\fP \*(Em 代码大小 (KiB)
当前用于可执行代码的\*(MP数量，也叫做文本驻留集 (Text Resident Set) 大小，或 TRS。

\*(XX。

.TP  4
\fB命令 (COMMAND)\fP \*(Em 命令 \fB名称\fP 或命令 \fB行 \fP
显示用于启动任务的命令行或相关程序的名称。您可以使用 "c" 在命令 \fI行\fP 和命令 \fI名称\fP 之间切换，"c" 既是\*(CO也是\*(CI。

当您选择显示命令行时，没有命令行的进程（如内核线程）将仅显示程序名称，以方括号包围，如下例所示：
    [kthreadd]

该字段也可能受到森林视图显示模式的影响。\*(XC\*(CI "V" 以了解有关该模式的更多信息。

\*(NT"命令" 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX
字符）将分配给它和其他所有可变宽度列。即使如此，这种可变宽度字段仍然可能会被截断。当显示命令行时（\*(CI
"c"），这一问题对于该字段而言尤为突出。\*(XT 5c. 滚动窗口 以获取关于查看被截断的数据的更多信息。

.TP  4
\fB数据 (DATA)\fP \*(Em 数据 + 栈大小 (KiB)
进程 \fI保留\fP 的私有内存数量。也叫做数据驻留集 (Data Resident Set) 或
DRS。这种内存可能尚未映射到\*(MP（驻留），但将始终包含在\*(MV（虚拟）中。

\*(XX。

.TP  4
\fBDocker\*(Em Docker 容器 ID \fP
正在运行任务的 docker 容器的 ID（哈希值的缩略形式）。如果进程未在容器内运行，则会显示短横线 ("\-")。

.TP  4
\fB已运行 (ELAPSED)\fP \*(Em 已经经过的运行时间
自进程启动以来经过的时间长度。因此，最近启动的任务显示的时间最小。

该值将表示为 "HH,MM"（小时,分钟），但如果时间数值太大而无法适应列宽，则可能会进行额外的单位缩放。届时，它将缩放为
"DD+HH"（天+小时），甚至更大的单位。

.TP  4
\fB环境 (ENVIRON)\fP \*(Em 环境变量
显示对应的进程能看到的所有环境变量（如果有的话）。这些变量将按原始顺序显示，而不是您习惯的使用不带参数的 "set" 命令看到的已排序好的顺序。

\*(NT"环境" 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX
字符）将分配给它和其他所有可变宽度列。即使如此，这种可变宽度字段仍然可能会被截断。这一问题对于该字段而言尤为突出。\*(XT 5c. 滚动窗口
以获取关于查看被截断的数据的更多信息。

.TP  4
\fB可执行文件 (EXE)\fP \*(Em 可执行文件路径
显示到可执行文件的完整路径（如果可用），包括程序名。

\*(NT"可执行文件" 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX 字符）将分配给它和其他所有可变宽度列。

.TP  4
\fB标志 (Flags)\fP \*(Em 任务标志
此列显示任务的当前调度标志，以十六进制表示法表示，不显示零。这些标志的官方文档在 <linux/sched.h> 中。

.TP  4
\fBGID\fP \*(Em 组 Id
\fI有效\fP 组 ID。

.TP  4
\fB组 (GROUP)\fP \*(Em 组名
\fI有效\fP 组名称。

.TP  4
\fBLOGID\fP \*(Em 登录用户 Id
\fI登录\fP 时使用的用户 ID。显示 \-1 时，表示此信息不可用。

.TP  4
\fBLXC\fP \*(Em LXC 容器名
正在运行任务的 lxc 容器的名称。如果进程未在容器内运行，则会显示短横线 ("\-")。

.TP  4
\fBNI\fP \*(Em Nice 值
任务的 nice 值。负的 nice 值意味着更高的优先级，而正的 nice 值意味着更低的优先级。该字段为 0
时，则表示在决定是否调度此任务时不会调整优先级。

\*(NT该值影响的调度优先级只是相对于同一自动组中其他进程而言的。\*(XC "AGID" 和 "AGNI" 字段以获取有关自动组的更多信息。

.TP  4
\fBNU\fP \*(Em 最后一次已知的 NUMA 节点
一个数字，表示与最后使用的处理器 ("P") 关联的 NUMA 节点。显示 \-1 时，表示 NUMA 信息不可用。

\*(XC\*(CI "2" 和 "3" 以了解更多影响\*(SA的、与 NUMA 相关的功能。

.TP  4
\fBOOMa\fP \*(Em OOM 调整因子
该值范围是 \-1000 到 +1000，会被加到当前的 OOMs (Out of Memory Score) 中，然后决定内存耗尽时要终止哪个任务。

.TP  4
\fBOOMs\fP \*(Em OOM 分数
该值范围是 0 到 +1000，曾经用于决定内存耗尽时要终止哪个任务。0 表示 "从不杀死"，而 1000 表示 "总是杀死"。

.TP  4
\fBP\fP \*(Em 最后使用的 \*(PU (SMP)
一个数字，表示最后使用的处理器。在真正的 SMP 环境中，这一数字可能会频繁更改，因为内核刻意使用弱亲和性 (affinity)。此外，运行 \*(We
本身可能会破坏这种弱亲和性，并导致更多进程更频繁地更换 \*(PU（因为对 \*(Pu 时间产生了额外需求）。

.TP  4
\fBPGRP\fP \*(Em 进程组 Id
每个进程都是唯一一个进程组的成员，该进程组用于分发信号，以及被终端用于仲裁其输入和输出的请求。当一个进程被创建 (fork)
时，它就成为其父进程所在的进程组的成员。按照惯例，该值等于进程组第一个成员的进程 ID（\*(Xa PID），这个进程叫做进程组头领。

.TP  4
\fBPID\fP \*(Em 进程 Id
任务的唯一的进程 ID，会定期重复使用，但不会从零重新开始。用内核术语来说，它是一个由 task_struct 定义的可调度实体。

该值还可以被用于：进程组 ID（\*(Xa PGRP）；会话头领的会话 ID（\*(Xa SID）；线程组头领的线程组 ID（\*(Xa
TGID）；以及进程组头领的 TTY 进程组 ID（\*(Xa TPGID）。

.TP  4
\fBPPID\fP \*(Em 父进程 Id
任务的父进程的进程 ID (pid)。

.TP  4
\fB优 (PR)\fP \*(Em 优先级
任务的调度优先级。如果此字段为 "rt"，则表示任务正在实时调度优先级下运行。

在 Linux 下，实时优先级有一定的误导性，因为传统上操作系统本身是不可抢占的。虽然 2.6 内核可以编译成大部分情况下可抢占，但是并非总是如此。

.TP  4
\fBPSS\fP \*(Em 比例驻留内存，smaps (KiB)
此任务所占有的 "RSS"，其中每个页面都除以共享该页面的进程数。它也是 "PSan"、"PSfd"和 "PSsh" 字段的总和。

例如，如果一个进程单独占有 1000 个驻留页，并且与另一个进程共享 1000 个驻留页，则其 "PSS" 将为 1500（乘以页大小）。

\*(ZX。

.PP
\fBPSan\fP \*(Em 比例匿名内存，smaps (KiB)
.br
\fBPSfd\fP \*(Em 比例文件内存，smaps (KiB)
.br
\fBPSsh\fP \*(Em 比例共享内存，smaps (KiB)
.RS 4
与上面的 "PSS"（总的比例驻留内存）字段一样，这些字段表示该任务所占有的各个类型的内存，每个页面都除以共享该页面的进程数。

\*(ZX。
.RE

.TP  4
\fB驻留 (RES)\fP \*(Em 驻留内存大小 (KiB)
虚拟地址空间（"虚拟 (VIRT)"）的子集，代表任务当前使用的非交换\*(MP。它也是 "RSan"、"RSfd" 和 "RSsh" 字段的总和。

它可以包括私有匿名页面、映射到文件（包括程序映像和共享库）的私有页面以及共享匿名页面。所有这些内存都由在 "交换 (SWAP)"
字段中表示的\*(MS在背后提供支持。

最后，该字段还可能包括共享的基于文件的页面，这些页面被修改后是作为专用的\*(MS，因此永远不会影响 "交换 (SWAP)"。

\*(XX。

.TP  4
\fBRSS\fP \*(Em 驻留内存，smaps (KiB)
这是另一个可以查看进程非交换\*(MP的字段，而且更加准确。它是从 "smaps_rollup" 文件中获得的，通常比 "驻留 (RES)"
显示的稍大。

\*(ZX。

.TP  4
\fBRSan\fP \*(Em 驻留匿名内存大小 (KiB)
驻留内存（"驻留 (RES)"）的子集，表示未映射到文件的虚拟页。

.TP  4
\fBRSfd\fP \*(Em 驻留文件内存大小 (KiB)
驻留内存（"驻留 (RES)"）的子集，表示支撑程序映像和共享库的、隐式的共享页。它也包括显式的文件映射（包括私有的和共享的）。

.TP  4
\fBRSlk\fP \*(Em 驻留锁定内存大小 (KiB)
驻留内存（"驻留 (RES)"）的子集，是其中不可换出的部分。

.TP  4
\fBRSsh\fP \*(Em 驻留共享内存大小 (KiB)
驻留内存（"驻留 (RES)"）的子集，表示显式共享的、匿名的 shm*/mmap 页面。

.TP  4
\fBRUID\fP \*(Em 真实用户 Id
\fI真实\fP 用户 ID。

.TP  4
\fB真实用户 (RUSER)\fP \*(Em 真实用户名
\fI真实\fP 用户名称。

.TP  4
\fBS\fP \*(Em 进程状态
任务的状态，可以是以下几种之一：
    \fBD\fP = 不可中断睡眠
    \fBI\fP = 空闲
    \fBR\fP = 运行中
    \fBS\fP = 睡眠中
    \fBT\fP = 被任务控制信号停止
    \fBt\fP = 在追踪时被调试器停止
    \fBZ\fP = 僵尸

显示为 "运行中" 的任务的更加准确的说法应该是 "准备运行（就绪）" \*(Em 简单地说，它们的 task_struct 位于 Linux
的运行队列中。即使不是真正的 SMP 机器，您也可能会看到多个处于此状态的任务，具体取决于 \*( We 的延迟间隔和 nice 值。

.TP  4
\fB共享 (SHR)\fP \*(Em 共享内存大小 (KiB)
驻留内存（"驻留
(RES)"）的子集，是其中可被其他进程使用的部分。它包括共享的匿名页面和共享的基于文件的页面。它还包括映射到程序映像文件和共享库文件的私有页面。

\*(XX。

.TP  4
\fBSID\fP \*(Em 会话 Id
会话是进程组（\*(Xa PGRP）的集合，通常由登录 shell 建立。新 fork
出来的进程会加入它的创建者的会话。按照惯例，该值等于会话的第一个成员的进程 ID（\*(Xa PID），该成员称为会话头领，通常是登录 shell。

.TP  4
\fB启动于 (STARTED)\fP \*(Em 启动时间
从系统启动到进程启动所经过的时间长度。因此，最近启动的任务将显示最大的时间。

该值将表示为 "MM:SS"（分钟:秒）。但是如果时间太大，无法适应列宽，则会被缩放为 "HH,MM"（小时,分钟），甚至更大的单位。

.TP  4
\fBSUID\fP \*(Em 保存用户 Id
\fI保存\fP 用户 ID。

.TP  4
\fB增补 GID (SUPGIDS)\fP \*(Em 增补组 ID
登录时确立的，或者从任务的父进程继承的所有增补组的 ID。用以逗号分隔的列表表示。

\*(NT"增补 GID" 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX 字符）将分配给它和其他所有可变宽度列。

.TP  4
\fB增补组 (SUPGRPS)\fP \*(Em 增补组名称
登录时确立的，或者从任务的父进程继承的所有增补组的名称。用以逗号分隔的列表表示。

\*(NT"增补组" 字段与大多数列不同，不是固定宽度的。显示时，所有剩余的屏幕宽度（最多为 \*(WX 字符）将分配给它和其他所有可变宽度列。

.TP  4
\fB保存用户 (SUSER)\fP \*(Em 保存用户名
\fI保存\fP 用户名称。

.TP  4
\fB交换 (SWAP)\fP \*(Em 已交换大小 (KiB)
当\*(MP过度分配以后，任务的地址空间中之前驻留在内存里，现在被写到\*(MS中的部分的大小。

\*(XX。

.TP  4
\fBTGID\fP \*(Em 线程组 Id
任务所处的线程组的 ID。它是线程组头领的 PID。用内核术语来说，它代表所有共享同一个 mm_struct 的任务。

.TP  4
\fB时间 (TIME)\fP \*(Em \*(PU 时间
任务启动后使用的总 \*(PU 时间。当累积模式 \*O 时，每个进程显示的 \*(Pu 时间都包括它和它的已死亡的子进程所使用的时间。使用 "S"
可以切换累积模式，它既是\*(CO，也是\*(CI。\*(XC\*(CI "S" 以获得关于此模式的更多信息。

.TP  4
\fB时间+ (TIME+)\fP \*(Em \*(PU 时间，0.01 秒
和 "时间 (TIME)" 相同，但是精度更高，精确到 0.01 秒。

.TP  4
\fBTPGID\fP \*(Em Tty 进程组 Id
连接到的 tty 的前台进程的进程组 ID，如果进程未连接到终端，则为 \-1。按照惯例，该值等于进程组头领（\*(Xa PGRP）的进程
ID（\*(Xa PID）。

.TP  4
\fBTTY\fP \*(Em 控制 Tty
控制进程的终端的名称。它通常是启动该进程的设备（串口、pty 等），并且该进程使用它进行输入输出。但是，任务不是必须和一个终端关联，这种情况下，将显示
"?"。

.TP  4
\fBUID\fP \*(Em 用户 Id
任务的所有者的 \fI有效\fP 用户 ID。

.TP  4
\fB已用 (USED)\fP \*(Em 使用中的内存 (KiB)
这个字段表示任务使用的非交换\*(MP（"驻留 (RES)"），加上它的地址空间中已被换出的部分（"交换 (SWAP)"）。

\*(XX。

.TP  4
\fB用户 (USER)\fP \*(Em 用户名
任务的所有者的 \fI有效\fP 用户名称。

.TP  4
\fBUSS\fP \*(Em 唯一集大小
\*(MP中的非交换部分 ("RSS") 中的未与任何其他进程共享的部分。它由 "smaps_rollup" 文件中的数据推导得出。

\*(ZX。

.TP  4
\fB虚拟 (VIRT)\fP \*(Em 虚拟内存大小 (KiB)
任务使用的\*(MV的总量。它包括所有的代码、数据和共享库，加上已被换出的页面，还有已被映射但未使用的页面。

\*(XX。

.TP  4
\fBWCHAN\fP \*(Em 在哪个函数中睡眠
这一字段将显示进程睡眠时处于的内核函数名称。正在运行的任务这一列会显示短横线 ("\-")。

.TP  4
\fBioR\fP \*(Em I/O 读取的字节
进程导致的从存储层获取的字节数。

显示其他用户的 "io" 数据需要 root 权限。

.TP  4
\fBioRop\fP \*(Em I/O 读操作
进程的 I/O 读操作（系统调用）的数量。这类调用不一定会导致实际的物理磁盘 I/O。

.TP  4
\fBioW\fP \*(Em I/O 写入的字节
进程导致的发送到存储层的字节数。

.TP  4
\fBioWop\fP \*(Em I/O 写操作
进程的 I/O 写操作（系统调用）的数量。这类调用不一定会导致实际的物理磁盘 I/O。

.TP  4
\fB脏页 (nDRT)\fP \*(Em 脏页计数
自其上次被写入\*(AS以来已被修改的页面数量。脏页必须先写入\*(AS，然后才能将相应的物理内存位置用于其他虚拟页。

该字段在 Linux 2.6 中已被弃用，并且始终为零。

.TP  4
\fBnFD \*(Em 文件描述符的数量 \fP
与进程关联的已打开的文件的总数。

.TP  4
\fB主要 (nMaj)\fP \*(Em 主要缺页计数
任务发生的 \fB主要\fP
缺页的数量。当进程尝试读取或写入当前不位于其地址空间中的虚拟页时，就会发生缺页。主要缺页指的是需要访问\*(AS才能使该页可用的缺页。

.TP  4
\fB次要 (nMin)\fP \*(Em 次要缺页计数
任务发生的 \fB次要\fP
缺页的数量。当进程尝试读取或写入当前不位于其地址空间中的虚拟页时，就会发生缺页。次要缺页指的是不需要访问\*(AS就能使该页可用的缺页。

.TP  4
\fB线 (nTH)\fP \*(Em 线程数
与进程关联的线程数量。

.TP  4
\fBnsCGROUP\fP \*(Em CGROUP 命名空间
用于隐藏进程所属控制组的身份的命名空间的 Inode。

.TP  4
\fBnsIPC\fP \*(Em IPC 命名空间
用于隔离进程间通信 (IPC) 资源（例如 System V IPC 对象和 POSIX 消息队列）的命名空间的 Inode。

.TP  4
\fBnsMNT\fP \*(Em MNT 命名空间
用于隔离文件系统挂载点，进而提供文件系统层次结构的不同视图的命名空间的 Inode。

.TP  4
\fBnsNET\fP \*(Em NET 命名空间
用于隔离网络设备、IP 地址、IP 路由、端口号等资源的命名空间的 Inode。

.TP  4
\fBnsPID\fP \*(Em PID 命名空间
用于隔离进程 ID 号，使其不需要保持唯一性的命名空间的 Inode。这使得每个这样的命名空间都可以有自己的 "init/systemd" (PID
#1)，来管理各种初始化任务，以及收割失去了父进程的子进程。

.TP  4
\fBnsTIME\fP \*(Em TIME 命名空间
允许进程以类似于 UTS 命名空间的方式看见不同的系统时间的命名空间的 Inode。

.TP  4
\fBnsUSER\fP \*(Em USER 命名空间
用于隔离用户和组 ID 号的命名空间的 Inode。这使得进程可以在某个用户命名空间之外拥有普通的非特权用户 ID，而在该命名空间内拥有用户 ID
0，从而具有完全的 root 权限。

.TP  4
\fBnsUTS\fP \*(Em UTS 命名空间
用于隔离主机名和 NIS 域名的命名空间的 Inode。UTS 其实就是 "Unix 分时系统 (Unix Time\-sharing System)"。

.TP  4
\fBv主 (vMj)\fP \*(Em 主要缺页计数变化量
自上次更新以来发生的 \fB主要\fP 缺页的数量（参见 "主要 (nMaj)"）。

.TP  4
\fBv次 (vMn)\fP \*(Em 次要缺页计数变化量
自上次更新以来发生的 \fB次要\fP 缺页的数量（参见 "次要 (nMin)"）。

.\" ......................................................................
.SS "3b. 管理字段"
.\" ----------------------------------------------------------------------
按下\*(CI "f"（字段管理）后，您将看到一个屏幕，其中显示：1) "\*(CW名称；2) 指定的排序字段；3)
所有字段，按当前顺序排列，并附有说明。标有星号的条目是当前显示的字段，如果屏幕宽度允许的话。

.RS +4
.IP \(bu 3
正如屏幕上的说明所示，您可以使用 \fB上\fP 和 \fB下\fP \*(KA在字段之间移动。PgUp、PgDn、Home 和 End
键可用于快速到达第一个或最后一个可用字段。

.IP \(bu 3
\fB右\fP \*(KA选择要重新放置的字段，\fB左\fP \*(KA或 <\fBEnter\fP> 键提交该字段的放置位置。

.IP \(bu 3
"\fBd\fP" 键或 <\fB空格\fP> 键可切换字段的显示状态，从而也会切换星号的显示与否。

.IP \(bu 3
"\fBs\fP" 键指定一个字段作为排序字段。\*(XT 4c. 任务区命令，排序 以获得关于选择排序字段的更多信息。

.IP \(bu 3
"\fBa\fP" 和 "\fBw\fP" 键可以循环浏览所有可用窗口，"\fBq\fP" 或 <\fBEsc\fP> 键可退出字段管理。
.RS -4

.PP
字段管理屏幕还可用于更改\*(FM或\*(AM中的 "\*(CG。当按下 "q" 或 <Esc> 时，在您返回 \*(We
的同时，当前正在编辑的目标窗口将成为当前窗口。\*(XT 5. 备用显示功能 和\*(CI "g" 以深入了解 "\*(CW和\*(FG。

.PP
\*(NT如果通过字段管理屏幕进行了任何字段更改，则任何已被 \fI水平\fP 滚动的窗口都将被重置。但是，任何经过 \fI垂直\fP
滚动的位置不会被影响。\*(XT 5c. 滚动窗口 以获得有关垂直和水平滚动的更多信息。

.\" ----------------------------------------------------------------------
.SH "4. 交互式命令"
.\" ----------------------------------------------------------------------
下面列出的是命令的简要索引，已经分成了不同的类别。有些命令出现了多次 \*(Em 它们的含义或范围可能会根据发出它们时的上下文而有所不同。

.nf
  4a.\fI 全局命令 \fP
        <Enter/空格>, ?, =, 0,
        A, B, d, E, e, g, H, h, I, k, q, r, s, W, X, Y, Z,
        ^E, ^R
  4b.\fI 概览区命令 \fP
        C, l, t, m, 1, 2, 3, 4, 5, !, ^
  4c.\fI 任务区命令 \fP
        外观： b, J, j, x, y, z
        内容： c, F, f, O, o, S, U, u, V, v
        大小： #, i, n
        排序： <, >, f, R
  4d.\fI 底部窗口命令 \fP
        ^A, ^G, ^K, ^L, ^N, ^P, ^U, Tab, Shift+Tab
  4e.\fI 颜色映射 \fP
        <回车>, a, B, b, H, M, q, S, T, w, z, @, 0 \- 7
  5b.\fI 窗口命令 \fP
        \-, _, =, +, A, a, G, g, w
  5c.\fI 滚动窗口 \fP
        C, 上, 下, 左, 右, PgUp, PgDn, Home, End
  5d.\fI 在窗口中查找 \fP
        L, &
  5e.\fI 在窗口中筛选 \fP
        O, o, ^O, =, +
.fi

.\" ......................................................................
.SS "4a. 全局命令"
.\" ----------------------------------------------------------------------
全局\*(CI在\*(FM和\*(AM中都 \fB总是\fP 可用。但是，在安全模式下运行时，其中一些\*(CI \fB不可用\fP。

如果您想提前知道您的 \*(We 是否处于安全模式，只需使用帮助命令，再查看第二行的系统概况即可。

.TP  7
\ \ <\fBEnter\fP> 或 <\fB空格\fP>\ \ :\fI刷新显示 \fP
这些命令唤醒 \*(We，在收到任何输入后，将重新绘制整个显示区域。它们还会强制针对任何热插拔导致的 \*(Pu 或\*(MP更改进行更新。

如果您设置了较大的延迟间隔但希望查看当前状态，请使用这两个键中的任何一个。

.TP  7
\ \ \ \fB?\fP | \fBh\fP\ \ :\fI帮助 \fP
有两个可用的帮助层级。第一层将提供所有基本\*(CI的简要提示。如果 \*(We 处于 \fI安全模式\fP，该屏幕的内容也将有所省略。

在主帮助屏幕上输入 "h" 或 "?" 将显示特殊键的帮助。\*(XT 4d. 底部窗口命令 以获取更多信息。

在主帮助屏幕上输入 "H" 将显示适用于\*(AM的\*(CI的帮助。\*(XT 5. 备用显示功能 以获取更多信息。

.TP  7
\ \ \ \fB=\fP\ \ :\fI解除显示限制 \fP
消除对显示内容的限制。此命令将撤销任何生效的 "i"（空闲任务）、"n"（最大任务数）、"v"（隐藏子进程）和 "F"（保持焦点）命令。它还可以让您退出
PID 监控、用户筛选、其他筛选、查找，以及合并 CPU 模式。

此外，如果窗口已被滚动，此命令会将其重置。

.TP  7
\ \ \ \fB0\fP\ \ :\fI不显示零值\fP 切换开关 
此命令决定是否显示\*(TW中的许多字段的零值。UID、GID、NI、优 (PR) 或 P 等字段不受此切换开关的影响。

.TP  7
\ \ \ \fBA\fP\ \ :\fI备用显示模式\fP 切换开关 
此命令将在\*(FM和\*(AM之间进行切换。\*(XT 5. 备用显示功能 和\*(CI "g" 以深入了解 "\*(CW和\*(FG。

.TP  7
\ \ \ \fBB\fP\ \ :\fI禁用/启用粗体\fP 切换开关 
此命令将影响 terminfo 功能 "粗体" 的使用，且对 "\*(CW的\*(SA和\*(TA \fB都\fP
有效。虽然它主要用于哑终端，但是任何时候都可以使用。

\*(NT当此切换开关 \*O 且 \*(We 处于单色模式时，\fB整个显示区域\fP 都会是普通文本。因此，除非 "x" 和/或 "y"
切换开关使用了反色来进行强调，否则不会有任何视觉上的区别能让您确认它们处于开启状态。

.TP  7
*\ \ \fBd\fP | \fBs\fP\ \ :\fI更改延迟时间 \fP
程序将提示您输入显示区域的更新延迟（以秒为单位）。

可以使用小数秒数，但不允许使用负数。输入 0 会导致（几乎）连续不断的更新，显示效果将会不理想，因为系统和 tty 驱动程序会试图满足 \*(We
的需求。延迟值与系统负载成反比，因此请小心设置。

如果您在任何时候想知道当前的延迟时间，只需使用帮助命令，再查看第二行的系统概况即可。

.TP  7
\ \ \ \fBE\fP\ \ :\fI强制设置概览内存单位\fP （概览区）
您可以使用此命令循环切换\*(SA内存的单位，从 KiB（kibibytes 或 1,024 字节）到 EiB（exbibytes 或
1,152,921,504,606,846,976 字节）。

如果您在显示的数字和后面的标签之间看到一个 "+"，则意味着 \*(We 被迫截断该数字的某些部分。通过增大单位，可以避免这种截断。

.TP  7
\ \ \ \fBe\fP\ \ :\fI强制设置任务内存单位\fP （任务区）
您可以使用此命令循环切换\*(TA内存的单位，从 KiB（kibibytes 或 1,024 字节）到 PiB（pebibytes 或
1,125,899,906,842,624 字节）。

虽然 \*(We
将尝试使用所选的单位，但为了适应当前值，可能仍然需要使用更大的单位。如果您希望在内存列中看到单位更加一致的结果，增大单位通常可以实现该目标。然而，单位太大可能会导致显示的数值全为零，且这种零值不能用\*(CI
"0" 禁止显示。

.TP  7
\ \ \ \fBg\fP\ \ :\fI选择另一个窗口/字段组 \fP
程序将提示您输入 1 到 4 之间的数字，指定要设为 "\*(CW的\*(FG。您很快就会熟悉这 4 个窗口，特别是在尝试使用\*(AM后。

.TP  7
\ \ \ \fBH\fP\ \ :\fI线程模式\fP 切换开关
当此切换开关 \*O 时，所有可见\*(TW中的所有进程将单独显示各个线程。否则，\*(We 将显示每个进程中所有线程的和。

.TP  7
\ \ \ \fBI\fP\ \ :\fIIrix/Solaris模式\fP 切换开关
当在 Solaris 模式下运行时（"I" 切换开关 \*F），任务的 \*(Pu 使用量将除以 \*(PU
的总数。执行此命令后，将告知您该切换开关的新的状态。

.TP  7
*\ \ \fBk\fP\ \ :\fI杀死一个任务 \fP
程序将提示您输入 PID，然后提示您输入要发送的信号。

不输入 PID 或输入负数将被视为输入了提示符中显示的默认值（显示的第一个任务）。PID 为零表示 \*(We 程序自身。

正如提示符中所描述的，默认信号是 SIGTERM。但是，您可以通过输入信号编号或名称发送任何信号。

如果您希望取消杀死进程的操作，请根据您所处的进度执行以下操作之一：
.nf
    1) 在 pid 提示符处，输入无效的数字
    2) 在信号提示符处，输入 0（或任何无效的信号）
    3) 在任何提示符处，按下 <Esc>
.fi

.TP  7
\ \ \ \fBq\fP\ \ :\fI退出 \fP

.TP  7
*\ \ \fBr\fP\ \ :\fI重新设置任务nice值 \fP
程序将提示您输入 PID，然后提示您输入要设置的 nice 值。

不输入 PID 或输入负数将被视为输入了提示符中显示的默认值（显示的第一个任务）。PID 为零表示 \*(We 程序自身。

正的 nice 值将导致进程失去优先级。相反，负的 nice 值将使内核更青睐该进程。一般来说，普通用户只能增加 nice 值，而不能降低 nice
值。

如果您希望取消重新设置 nice 值的操作，请根据您所处的进度执行以下操作之一：
.nf
    1) 在 pid 提示符处，输入无效的数字
    2) 在 nice 提示符处，不输入任何内容，并按 <Enter>
    3) 在任何提示符处，按下 <Esc>
.fi

.TP  7
\ \ \ \fBW\fP\ \ :\fI写入配置文件 \fP
这将保存您的所有选项和切换开关，以及当前的显示模式和延迟时间。如果您在退出 \*(We 之前执行此命令，之后您将能够以完全相同的状态重新启动。

.TP  7
\ \ \ \fBX\fP\ \ :\fI加宽固定宽度字段 \fP
有些字段是固定宽度且不可缩放的。因此，它们可能会被截断，此时字段的最后一个字符显示为 "+"。

可以使用此\*(CI修改以下字段的宽度：

.nf
   \fI 字段     默认     字段     默认     字段      默认 \fP
    GID       5       Docker    8       WCHAN      10
    LOGID     5       组        8       nsCGROUP   10
    RUID      5       LXC       8       nsIPC      10
    SUID      5       真实用户  8       nsMNT      10
    UID       5       保存用户  8       nsNET      10
                      TTY       8       nsPID      10
                      用户      8       nsTIME     10
                                        nsUSER     10
                                        nsUTS      10
.fi

程序将提示您输入要给上述默认宽度增加的数值。输入零会强制恢复这些默认值。

如果您输入一个负数，\*(We 将根据需要自动增加列宽，直到不再有数据被截断。

\*(NT无论是显式增加还是自动增加，\*(We 都不会减少这些字段的宽度。要使字段变窄，您必须指定一个更小的数值或恢复默认值。

.TP  7
\ \ \ \fBY\fP\ \ :\fI检视其他输出 \fP
执行\*(CI "Y" 后，程序将提示您输入目标
PID。键入一个值或接受默认值后，将显示一个单独的屏幕。该屏幕可用于查看各种文件，或者通过管道传来的命令输出，与此同时，正常的 \*(We
迭代显示会被暂停。

只有当支持性条目被手动添加到 \*(We \*(CF的末尾以后，这个\*(CI才会被完全实现。有关创建这些条目的详细信息，\*(Xt
6b. 添加检视条目。

有关检视功能的大多数按键都在屏幕顶端的帮助文本中有所说明。但是，在您选择了特定文件或命令后，还有其他一些按键可以使用。这些按键对于任何使用过
"less" 分页器的人来说，都会感到很熟悉，这里总结一下以供参考。

.nf
   \fI 按键     功能 \fP
    =        切换显示状态栏、文件名或管道命令行
    /        查找，等价于 "L"
    n        查找下一个，等价于 "&"
    <空格>   向下滚动，等价于 <PgDn>
    b        向上滚动，等价于 <PgUp>
    g        第一行，等价于 <Home>
    G        最后一行，等价于 <End>
.fi

.TP  7
\ \ \ \fBZ\fP\ \ :\fI更改颜色映射 \fP
按下此按键将显示一个单独的屏幕，您可以在其中更改 "\*(CW或所有窗口的颜色映射。要了解有关此\*(CI的详细信息，\*(Xt 4e. 颜色映射。

.TP  7
\ \ \fB^E\fP\ \ :\fI缩放CPU时间字段\fP（Ctrl 键 + "e"）
"时间" 字段的显示精度通常是其宽度允许的最高精度。此切换开关会降低精度，直到重新回到最高精度。此切换开关还可以展示这些字段 \fI可能\fP
会自动进行的缩放，是否出现自动缩放通常取决于系统运行的时间长短。

例如，如果显示的是 "分钟:秒.百分秒"，按下 ^E 时，时间会依次变为："分钟:秒"、"小时,分钟"、"天+小时"，最后是 "周+天"。

不是所有时间字段在进行这种缩放时都支持完整的缩放范围。

.TP  7
*\ \fB^R\fP\ \ :\fI重新设置自动组nice值 \fP（Ctrl 键 + "r"）
程序将提示您输入 PID，然后提示您输入要给其自动组 AGNI 设置的值。

不输入 PID 将被视为输入了提示符中显示的默认值（显示的第一个任务）。

正的 AGNI 值将导致该自动组中的进程失去优先级。相反，负值会使内核更青睐它们。普通用户不允许设置负的 AGNI 值。

如果您希望取消重新设置 nice 值的操作，请按 <Esc>。

.IP * 3
带有\*(AK 的命令在安全模式下不可用，也不会显示在第 1 层的帮助屏幕上。

.\" ......................................................................
.SS "4b. 概览区命令"
.\" ----------------------------------------------------------------------
\*(SA\*(CI在\*(FM和\*(AM中都 \fB总是可用\fP。它们会影响显示区域的头几行，并将决定消息和提示符的位置。

这些命令总是仅影响 "\*(CG。\*(XT 5. 备用显示功能 和\*(CI "g" 以深入了解 "\*(CW和\*(FG。

.TP  7
\ \ \ \fBC\fP\ \ :\fI显示滚动坐标\fP 切换开关
切换显示一条信息性消息，只要消息行未被其他消息占用，就会显示该消息。有关更多信息\*(Xt 5c. 滚动窗口。

.TP  7
\ \ \ \fBl\fP\ \ :\fI平均负载/上线时间\fP 切换开关
处于\*(FM时，这一行也包含程序名称（可能是别名）。处于\*(AM时，这一行也包含 "\*(CW名称。

.TP  7
\ \ \ \fBt\fP\ \ :\fI任务/CPU状态\fP 切换开关
该命令影响\*(SA中的 2 行到很多行，具体取决于\*(CT "1"、"2" 或 "3" 的状态，以及 \*(We 是否在真正的 SMP 环境下运行。

\*(SA的这一部分也受到\*(CI "H" 切换开关的影响，比如 "总共" 标签中显示的是 "任务" 还是 "线程"。

此命令是一个 4 路的切换开关，循环激活以下模式：
.nf
    1. 各类别的详细百分比
    2. 简略的用户/系统和总计百分比 + 竖线图表
    3. 简略的用户/系统和总计百分比 + 方块图表
    4. 关闭任务和 CPU 状态显示
.fi

使用两种有图表的模式中的任意一种时，如果同时显示单个 CPU 或 NUMA 节点的情况，则显示的内容会变得更有意义。\*(XC下方的命令 "1"、"2"
和 "3" 以获取更多信息。

.TP  7
\ \ \ \fBm\fP\ \ :\fI内存/交换使用量\fP 切换开关
该命令影响\*(SA中的关于物理和虚拟内存的两行。

此命令是一个 4 路的切换开关，循环激活以下模式：
.nf
    1. 各内存类型的详细百分比
    2. 简略的已用百分比/可用总量 + 竖线图表
    3. 简略的已用百分比/可用总量 + 方块图表
    4. 关闭内存显示
.fi

.TP  7
\ \ \ \fB1\fP\ \ :\fI单行/分开显示CPU状态\fP 切换开关
此命令影响 "t" 命令的 CPU 状态部分的显示方式。尽管此切换开关主要用于并行度很高的 SMP 机器，但它并不仅限于在 SMP 环境中使用。

当您在\*(SA中看到 "%Cpu(s):" 时，意味着 "1" 切换开关 \*O，并且所有 \*(Pu 信息都汇总在一行中。否则，每个 \*(Pu
会分开显示为："%Cpu0、%Cpu1、..."，最多可占据全部的可用屏幕高度。

.TP  7
\ \ \ \fB2\fP\ \ :\fINUMA节点/CPU概览\fP 切换开关
此命令切换（仅）显示 "1" 命令的 cpu 概览，或是显示概览和每个 NUMA 节点的 cpu 使用量统计信息。仅在系统具有必要的 NUMA
支持时才可用。

.TP  7
\ \ \ \fB3\fP\ \ :\fI展开NUMA节点 \fP
程序将提示您输入表示 NUMA 节点的数字。此后，将显示该节点的概览以及该节点中每个 cpu 的统计信息，直到按下\*(CT "1"、"2" 或
"4"。此\*(CI仅在系统具有必要的 NUMA 支持时才可用。

.TP  7
\ \ \ \fB4\fP\ \ :\fI并列显示多个元素\fP 切换开关
这个\*(CT会 \*F 切换开关 "1"，并在每一行中显示多个 \*(PU 和内存结果。每按一次 "4" 键，增加一个
\*(PU，直到重新恢复为每行显示一个 \*(PU 和内存结果。

每行最多可以显示 8 个 \*(PU。但是，在达到这一最大值之前可能就会发生数据截断。通过\*(CT "t"
显示详细统计信息时肯定会出现这种情况，因为此类数据无法像图表一样缩放。

如果希望快速退出并列模式而不想一直循环到 8，只需使用\*(CT "1"。

.TP  7
\ \ \ \fB5\fP\ \ :\fI显示P核和E核\fP 切换开关
此\*(CT仅在多核平台具有两种不同类型的核心时才生效，即多线程（P 核）和单线程（E 核）。

平常每个 \*(Pu 显示为 "%Cpu0、%Cpu1、.\|.\|."，而使用此切换开关后，可根据核心类型识别和/或筛选这些 \*(Pu，将它们分为
P 核（performance，性能） 和 E 核（efficient，高效）。

第 1 次敲击 "5" 时，每个 \*(PU 显示为 "%Cp\fBP\fP" 或 "%Cp\fBE\fP"，代表两种核心类型。第 2 次敲击时，仅显示 P 核
(%Cp\fBP\fP)。第 3 次，仅显示 E 核 (%Cp\fBE\fP)。第 4 次敲击此\*(CT时，\*(PU 显示将恢复成正常的 "%Cpu" 格式。

.TP  7
\ \ \ \fB!\fP\ \ :\fI合并CPU模式\fP 切换开关
此\*(CT适用于并行度很高的 SMP 环境，此类环境中，即使使用 "4" \*(CT，也无法显示所有处理器。每按一次 "!"，合并的 \*(Pu
数量就会加倍，从而减少显示的 \*(Pu 行总数。

例如，第一次按 "!" 时，将合并每两个 \*(Pu，显示为 "0\-1、2\-3、.\|.\|." 而不是平常的
"%Cpu0、%Cpu1、%Cpu2、%Cpu3, .\|.\|."。第二次按 "!" \*(CT时，将合并每四个 \*(Pu，显示为
"0\-3、4\-7、.\|.\|."。第三次按 "!" 时，将合并每八个 \*(Pu，显示为 "0\-7、8\-15、.\|.\|."，以此类推。

这一过程将持续下去，直到再次显示单个 \*(Pu。使用 "=" 命令退出 \fB合并 CPU\fP 模式。

.TP  7
\ \ \ \fB^\fP\ \ :\fI显示核心 vs CPU\fP 切换开关
现代的平台通常具有同时多线程（SMT）技术的某种实现，允许多个线程在单个物理核心上同时执行。每个核心支持两个线程是最常见的配置。然而，某些企业级和专用架构支持更高的线程数量。

此\*(CT用于显示单个物理 \*(Pu 核心的利用率，而不是报告的单个 CPU，即线程的利用率。

.PP
\*(NT对于任何窗口，如果 \*F 了整个\*(SA的显示 ，您将只能看见一行
\fB消息行\fP。这样，您将得到最多的任务行，但（暂时）无法看到程序名称（处于\*(FM时）或 "\*(CW名称（处于\*(AM时）。

.\" ......................................................................
.SS "4c. 任务区命令"
.\" ----------------------------------------------------------------------
在\*(FM中，\*(TA的\*(CI \fB总是\fP 可用。

在\*(AM中，\fI如果\fP "\*(CW的\*(TD被 \*F，那么\*(TA的\*(CI \fB总是不可用\fP（\*(Xt 5. 备用显示功能）。

.\" ..................................................
.PP
\*(TW的 \fB外观\fP

.TP  7
\ \ \ \fBJ\fP\ \ :\fI对齐数字列\fP 切换开关
对于数字数据，在右对齐（默认）和左对齐之间切换。如果数字数据完全填满了列，则此\*(CT可能仅影响列标题。

.TP  7
\ \ \ \fBj\fP\ \ :\fI对齐字符列\fP 切换开关
对于字符数据，在左对齐（默认）和右对齐之间切换。如果字符数据完全填满了列，则此\*(CT可能仅影响列标题。

.PP
.RS +2
以下命令还受到全局切换开关 "B"（启用粗体）的状态的影响。
.RS -2

.TP  7
\ \ \ \fBb\fP\ \ :\fI加粗/反色\fP 切换开关
此命令将影响 "x" 和 "y" 切换开关的显示方式。当通过 "t" 或 "m" 切换开关选择了使用竖线图展示 \*(Pu
状态或内存使用情况时，此命令可能也会影响\*(SA。

.TP  7
\ \ \ \fBx\fP\ \ :\fI列高亮\fP 切换开关
开关当前排序字段的高亮显示。如果您忘记了正在对哪个字段进行排序，此命令可以进行一种快速的视觉上的提醒，但前提是排序字段当前显示在屏幕上。排序字段可能由于以下原因 \fI不\fP 可见：
    1）没有足够的 \fI屏幕宽度\fP
    2) 被\*(CI "f" \*F

.TP  7
\ \ \ \fBy\fP\ \ :\fI行高亮\fP 切换开关
开关 "运行中" 的任务的高亮显示。要进一步了解此任务状态，\*(Xt 3a. 字段描述，"S" 字段（进程状态）。

此功能可以提供关于系统健康状况的重要信息。唯一的系统开销是要多处理一些 tty 转义序列。

.TP  7
\ \ \ \fBz\fP\ \ :\fI彩色/单色\fP 切换开关
切换 "\*(CW的颜色设置，在上次使用的配色方案和旧式的白底黑字或黑底白字之间切换。此命令将影响\*(SA \fB和\fP \*(TA，但不影响
"x"、"y" 或 "b" 切换开关的状态。

.\" ..................................................
.PP
\*(TW的 \fB内容\fP

.TP  7
\ \ \ \fBc\fP\ \ :\fI命令行/程序名称\fP 切换开关
无论命令 (COMMAND) 列当前是否可见，此命令都有效。之后，假如该字段开始显示，您将可以看到您执行此命令引起的变化。

.TP  7
\ \ \ \fBF\fP\ \ :\fI保持父进程焦点\fP 切换开关
当处于森林视图模式时，此切换开关决定是否保持焦点在某一目标任务（也许是有 fork 出来的子进程的任务）上。如果森林视图模式处于 \*F
状态，则此键无效。

此切换开关应用于 "\*(CW中的第一个（最上方的）进程。一旦生效，该任务及其 fork
出来的子进程将始终显示为第一个（最上方的）进程。所有其他进程都将停止显示。

\*(NT"i"（空闲任务）、"n"（最大任务数）、"v"（隐藏子进程）以及用户/其他筛选等按键仍然可以使用，并且可能会影响显示的内容。

.TP  7
\ \ \ \fBf\fP\ \ :\fI字段管理\fP
该键显示一个单独的屏幕，您可以在其中更改要显示的字段及其顺序，还可以指定排序字段。有关此\*(CI的更多信息，\*(Xt 3b. 管理字段。

.TP  7
\ \ \ \fBO\fP | \fBo\fP\ \ :\fI其他筛选\fP
程序将提示您输入筛选标准，然后确定哪些任务将显示在 "\*(CW中。您的标准可以区分大小写，也可以忽略大小写。然后您决定 \*(We
应该包含还是排除匹配的任务。

\*(XT 5e. 在窗口中筛选 以了解关于这些功能和其他相关\*(CI的内容。

.TP  7
\ \ \ \fBS\fP\ \ :\fI累积时间模式\fP 切换开关
当累积模式 \*O 时，每个进程显示的 \*(Pu 时间都包括它和它的已死亡的子进程的 \*(Pu 时间。

当累积模式 \*F 时， fork 出很多单独任务的程序将显得资源消耗较低。对于像 "init" 或 shell
这样的程序，这是合适的，但对于其他程序，比如编译器，可能不合适。尝试使用两个具有相同排序字段但具有不同 "S"
命令状态的\*(TW，看看您更喜欢哪种表示方式。

执行此命令后，将告知您此切换开关的新的状态。如果您想提前知道累积模式是否生效，只需使用帮助命令，再查看第二行的窗口概况即可。

.TP  7
\ \ \ \fBU\fP | \fBu\fP\ \ :\fI仅显示特定用户\fP
程序将提示您输入要显示的用户的 \fBuid\fP 或 \fB名称\fP。\-u 选项匹配 \fB有效\fP 用户，而 \-U 选项匹配 \fB任意\fP
类型的用户（真实、有效、保存或文件系统用户）。

之后，在此\*(TW中，将仅显示匹配的用户，或者有可能不显示任何进程。在用户 ID 或名称前面加上感叹号 ("!") 会使得 \*(We
仅显示与所提供的用户不匹配的进程。

不同的\*(TW可用于筛选不同的用户。之后，如果您希望再次在 "\*(CW中显示所有用户，请重新执行此命令，但只需在提示符下按
<Enter> 即可。

.TP  7
\ \ \ \fBV\fP\ \ :\fI森林视图模式\fP 切换开关
在此模式下，将根据进程的父进程重新排序进程，并且命令 (COMMAND)
列的布局类似于一棵树。在森林视图模式下，仍然可以切换显示程序名称和命令行（\*(Xc\*(CI "c"）或切换显示进程和线程（\*(Xc\*(CI
"H"）。

\*(NT按下影响排序顺序的任何按键都将使 "\*(CW退出森林视图模式。\*(XT 4c. 任务区命令，排序 以获取有关这些按键的信息。

.TP  7
\ \ \ \fBv\fP\ \ :\fI隐藏/显示子进程\fP 切换开关
在森林视图模式下，此切换开关用于折叠或展开父进程的子进程。

此切换开关应用于 "\*(CW中的第一个（最上方的）进程。\*(XT 5c. 滚动窗口 以获取有关垂直滚动的更多信息。

如果目标进程没有 fork 出任何子进程，则此按键无效。当不处于森林视图模式时，此按键也没有效果。

.\" ..................................................
.PP
\*(TW的 \fB大小\fP

.TP  7
\ \ \ \fBi\fP\ \ :\fI空闲进程\fP 切换开关
显示所有任务或仅显示活动的任务。当此切换开关 \*F 时，自上次更新以来未使用任何 \*(PU 的任务将不会显示。但是，受制于 %CPU 和 时间+
(TIME+) 字段的粒度，某些 \fI似乎没有\fP 使用过 \*(PU 的进程可能仍会显示出来。

如果此命令被应用于\*(AM中的最后一个\*(TD，那么它不会影响窗口的大小，因为所有先前的\*(TD都已被绘制。

.TP  7
\ \ \ \fBn\fP | \fB#\fP\ \ :\fI设置最大任务数\fP
程序将提示您输入要显示的任务数。将使用您输入的数字和可用屏幕行数中的较小者。

当在\*(AM中使用时，该命令可以让您精确控制当前可见的每个\*(TD的大小，最后一个除外。它不会影响最后一个窗口的大小，因为所有先前的\*(TD都已被绘制。

\*(NT处于\*(AM时，如果您希望增加最后一个可见的\*(TD的大小，只需减小其上方的\*(TD的大小即可。

.\" ..................................................
.PP
\*(TW的 \fB排序\fP
.PP
.RS +3
出于兼容性考虑，此 \*(We 支持大多数以前的 \*(We 的排序按键。由于该功能主要是为以前的 \*(We
用户服务的，这些命令不会出现在任何帮助屏幕上。
.nf
     \fI 命令      被排序的字段                  是否支持 \fP
      A         开始时间（不显示）           \fB 否 \fP
      M         %MEM                          是
      N         PID                           是
      P         %CPU                          是
      T         时间+                         是
.fi

在使用以下任何排序功能之前，\*(We 建议您使用 "x" \*(CI暂时开启列高亮显示。这将有助于确保实际使用的排序字段符合您的意图。

以下\*(CI \fB仅\fP 在当前排序字段 \fB可见\fP 时有效。
排序字段可能由于以下原因 \fI不\fP 可见：
      1）没有足够的 \fI屏幕宽度\fP
      2) 被\*(CI "f" \*F

.TP  7
\ \ \ \fB<\fP\ \ :\fI排序字段左移\fP
将排序列向左移动，除非当前排序字段是显示的第一个字段。

.TP  7
\ \ \ \fB>\fP\ \ :\fI排序字段右移\fP
将排序列向右移动，除非当前排序字段是显示的最后一个字段。

.PP
以下\*(CI \fB总是\fP 有效，无论当前排序字段是否可见。

.TP  7
\ \ \ \fBf\fP\ \ :\fI字段管理\fP
该按键将显示一个单独的屏幕，此屏幕允许您更改用作排序列的字段，也提供其他功能。当运行 \*(We 并将列高亮显示 \*F
时，这是一种查看当前排序字段的便捷方法。

.TP  7
\ \ \ \fBR\fP\ \ :\fI反向/正常排序字段\fP 切换开关
您可以使用此\*(CI在从高到低和从低到高排序之间切换。

.\" ......................................................................
.SS "4d. 底部窗口命令"
.\" ----------------------------------------------------------------------
这些按键将在屏幕底部打开一个单独的窗口，同时正常的 \*(We 监控仍将继续进行。再次按下 \fI相同的\fP "Ctrl" 命令或者使用 "="
命令移除这个窗口。

以下操作应用于当前显示的第一个任务。上/下方向键可以选择目标进程。使用更稳定的显示方式也很重要，如森林视图、按 PID 排序或使用更长的延迟间隔。

.nf
   \fB^A\fP\ \ :\fI显示进程能力 \fP (Ctrl 键 + "a")
   \fB^G\fP\ \ :\fI显示控制组 \fP   (Ctrl 键 + "g")
   \fB^K\fP\ \ :\fI显示命令行 \fP   (Ctrl 键 + "k")
   \fB^N\fP\ \ :\fI显示环境 \fP     (Ctrl 键 + "n")
   \fB^P\fP\ \ :\fI显示命名空间 \fP (Ctrl 键 + "p")
   \fB^U\fP\ \ :\fI显示增补组 \fP   (Ctrl 键 + "u")
.fi

此命令不执行特定的任务，而是调取 \*(We 最近输出的最多 10 条消息供查阅。

.nf
   \fB^L\fP\ \ :\fI显示消息日志 \fP（Ctrl 键 + "l"）
.fi

\fBTab\fP 键（向前）或 \fBShift+Tab\fP 组合键（向后）可用于高亮显示底部窗口中显示的各个元素。

这些功能中值得注意的是 Ctrl+N（环境）命令。它的输出可能很长，并且在自动换行以后不容易阅读。可以通过在 rc 文件中添加 "检视"
条目获得更具可读性的版本，如下所示。

.nf
    pipe ^I 环境 ^I cat /proc/%d/environ | tr '\e0' '\en'
.fi

\*(XC 4a. 全局命令 中的\*(CI "Y" 和主题 6b. 添加检视条目 以了解更多信息。

.\" ......................................................................
.SS "4e. 颜色映射"
.\" ----------------------------------------------------------------------
当您执行\*(CI "Z" 时，您将看到一个单独的屏幕。您可以使用该屏幕更改 "\*(CW或所有四个窗口的颜色设置，然后再返回到 \*(We 的显示。

.P
可使用以下\*(CI。
.nf
    \fB5\fP 个大写字母用来选择 \fB目标\fP
    \fB8\fP 个数字用来选择 \fB颜色\fP
    可用的普通切换开关
        B         ：禁用/启用粗体
        b         ："加粗"/反色正在运行的任务
        z         ：彩色/单色
    可用的其他命令
        a/w       ：应用，然后转到下一个/上一个
        <Enter>   ：应用并退出
        q         ：放弃当前更改并退出
.fi

如果您使用 "a" 或 "w" 循环选择目标窗口，在您离开该窗口时，将应用所显示的配色方案。当然，您可以轻松返回到任何窗口并重新应用不同的颜色，或使用
"z" 切换开关完全 \*F 颜色显示。

颜色映射屏幕还可用于更改\*(FM或\*(AM的 "\*(CG。当按下 "q" 或 <Enter> 时，在您返回 \*(We
的同时，正在修改的目标会被设为 "当前" 窗口/字段组。

.\" ----------------------------------------------------------------------
.SH "5. 备用显示功能"
.\" ----------------------------------------------------------------------
.\" ......................................................................
.SS "5a. 窗口综述"
.\" ----------------------------------------------------------------------
.TP  3
\fB字段组/窗口\fP：
在\*(FM中，只有一个窗口，占据了整个屏幕。您仍然可以将这个窗口设置为显示 4 个不同的 \fB字段组\fP 中的 1 个（\*(Xc\*(CI
"g"，下文会再次说明）。4 个\*(FG中的每一个都有一个独立的可单独配置的 \fB\*(SA\fP 和它自己的可配置的 \fB\*(TA\fP。

在\*(AM中，这 4 个\*(FG可以同时设为可见，也可以依照您的命令单独 \*F。

\*(SA将始终显示，即使它只包含消息行。在任一特定时刻只会显示 \fI1\fP 个\*(SA。但是，依照您的命令，当前屏幕上可能会显示 \fI0\fP 到
\fI4\fP 个单独的\*(TD。

.TP  3
\fB当前窗口\fP：
"\*(CW是与\*(SA关联的窗口，也始终是与任务有关的命令的目标窗口。由于在\*(AM中，您可以 \*F \*(TD，因此对于
"\*(CW而言，某些命令的执行可能会受到限制。

当您将\*(SA的第一行 \*F 时，情况会变得更加复杂。由于不再显示窗口名称（"l" 切换开关所对应的行），您将难以确定哪个窗口是 "\*(CW。

.\" ......................................................................
.SS "5b. 窗口命令"
.\" ----------------------------------------------------------------------
.TP  7
\ \ \ \fB\-\fP | \fB_\fP\ \ :\fI显示/隐藏窗口\fP 切换开关
"\-" 键 \*O 或 \*F "\*(CW的\*(TD。\*O 时，\*(TA将至少显示您使用\*(CI "f"
设置的列标题行。它还将应用您已设置的任何其他\*(TA选项/切换开关，据此显示零个或多个任务。

"_" 键对所有\*(TD执行相同的操作。换句话说，它交替显示当前可见的\*(TD，以及被您 \*F 的所有\*(TD。如果 4
个\*(TD当前均可见，此\*(CI会将\*(SA作为唯一的显示元素。

.TP  7
*\ \ \fB=\fP | \fB+\fP\ \ :\fI平衡/重置窗口\fP
"=" 键强制使 "\*(CW的\*(TD变为可见。它还会撤销任何生效的
"i"（空闲任务）、"n"（最大任务数）、"u/U"（用户筛选）、"o/O"（其他筛选）、"v"（隐藏子进程）、"F"（保持焦点）、"L"（查找）和
"!"（合并 cpu）命令。此外，如果窗口已被滚动，此命令会将其重置。\*(XT 5c.滚动窗口 以获取有关垂直和水平滚动的更多信息。

"+" 键对所有窗口执行相同的操作。将重新显示四个\*(TD，平衡它们的大小，同时将保留之前应用的所有自定义设置，\*(CT "=" 中提到的除外。

.TP  7
*\ \ \fBA\fP\ \ :\fI备用显示模式\fP 切换开关
此命令将在\*(FM和\*(AM之间切换。

第一次执行此命令时，将显示所有四个\*(TD。此后，当您切换模式时，您将仅看到您已设为可见的\*(TD。

.TP  7
*\ \ \fBa\fP | \fBw\fP\ \ :\fI下一个/上一个窗口\fP
此命令将更改 "\*(CW，从而更改命令的目标窗口。这两个按键会循环选择窗口，因此您可以使用其中任何一个键选定任何您想选定的窗口。

假设窗口名称是可见的（您没有将 "l" 切换开关设为 \*F 状态），当 "\*(CW名称失去高亮/颜色时，这是在提醒您\*(TD已被
\*F，许多命令的执行将受到限制。

.TP  7
\ \ \ \fBG\fP\ \ :\fI更改窗口/字段组名称\fP
程序将提示您为 "\*(CW输入新名称。此命令不要求窗口名称可见（"l" 切换开关 \*O）。

.IP * 3
带有\*(AK 的\*(CI在\*(AM之外也有作用。
.nf
    =, A, g    总是可用
    a, w       在颜色映射和字段管理中具有相同的功能
.fi

.TP  7
*\ \ \fBg\fP\ \ :\fI选择另一个窗口/字段组\fP
程序将提示您输入 1 到 4 之间的数字，指定要设为 "\*(CW的\*(FG。

在\*(FM中，需要使用此命令来更改 "\*(CW。在\*(AM中，它只是 "a" 和 "w" 命令的不太方便的替代品。

.\" ......................................................................
.SS "5c. 滚动窗口"
.\" ----------------------------------------------------------------------
通常，\*(TW仅显示系统中的一部分任务/线程，也仅显示一部分可用的字段/列。您可以使用这些\*(KS垂直或水平移动视图，以显示任何想看到的任务或列。

.TP  4
\fB上\fP,\fBPgUp\fP\ \ :\fI滚动任务\fP
将视图向上移动，移向第一个任务，直到第一个任务显示在 "\*(CW的顶端。\fI上\fP \*(KA移动一行，而 \fIPgUp\fP 滚动整个窗口。

.TP  4
\fB下\fP,\fBPgDn\fP\ \ :\fI滚动任务\fP
将视图向下移动，移向最后一个任务，直到最后一个任务显示在 "\*(CW的顶端，并且是唯一一个显示的任务。\fI下\fP \*(KA移动一行，而 \fIPgDn\fP
滚动整个窗口。

.TP  4
\fB左\fP,\fB右\fP\ \ :\fI滚动列\fP
水平移动视图，调整显示的字段，一次移动一列。

\*(NT值得提醒的是，某些字段/列不是固定宽度的，而是在它们可见时分配给它们所有剩余的屏幕宽度。当向右或向左滚动时，该功能一开始可能会产生一些意想不到的结果。

此外，当任何可变宽度字段是最后一个显示的字段时，都有一个特殊功能。通过右\*(KA到达该字段后，该字段是唯一显示的列，但您可以继续在该字段内水平滚动。
\*(XC下面的\*(CI "C" 以了解更多信息。

.TP  4
\fBHome\fP\ \ :\fI跳转到Home位置\fP
重新放置显示区域到未滚动的位置。

.TP  4
\fBEnd\fP\ \ :\fI跳转到End位置\fP
重新放置显示区域，使得最右边的列是最后一个可显示字段，最下方的任务行是最后一个任务。

\*(NT仍然可以使用\*(KA从这个位置开始向 \fI下\fP 和向 \fI右\fP 滚动。直到只显示一列和一个任务之前都可以。

.TP  4
\fBC\fP\ \ :\fI显示滚动坐标\fP 切换开关
切换是否显示一条信息性消息，只要消息行未以其他方式使用，就会显示该消息。该消息将使用两种格式中的一个，具体取决于可变宽度列是否已被滚动。

.nf
  \fB滚动坐标：y = n/n（任务），x = n/n（字段）\fP
  滚动坐标：y = n/n（任务），x = n/n（字段）\fB + nn\fP
.fi

形如 \fBn\fP/\fBn\fP 的坐标是相对于 "\*(CW的左上角的。附加的 "\fB+\ nn\fP"
表示当可变宽度列已被水平滚动时，可变宽度列的位移。您可通过左\*(KA和右\*(KA实现这种位移，位移长度是普通的 8 个字符的制表符的整数倍。

.RS +4
.TP  4
\fBy = n/n（任务）\fP
第一个 \fBn\fP 表示最上方的可见任务，受\*(KS控制。第二个 \fBn\fP 会自动更新，以反映任务总数。

.TP  4
\fBx = n/n（字段）\fP
第一个 \fBn\fP 表示最左边的显示列，受\*(KS控制。第二个 \fBn\fP 是可显示字段的总数，受\*(CI "\fBf\fP" 控制。
.RS -4

.PP
在\*(FM中，上述\*(CI \fB总是\fP 可用，但在\*(AM中，如果 "\*(CW 的\*(TD被 \*F，则上述\*(CI总是 \fB不\fP 可用。

\*(NT当使用了任何形式的筛选时，滚动时可能会出现一些轻微的异常，因为并非所有任务都可见。当使用上/下\*(KA时，这种情况会更加明显。

.\" ......................................................................
.SS "5d. 在窗口中查找"
.\" ----------------------------------------------------------------------
您可以使用这些\*(CI查找含有某个特定值的任务行。

.TP  4
\fBL\fP\ \ :\fI查找字符串\fP
程序将提示您输入区分大小写的字符串，并从当前窗口坐标开始查找。查找字符串的内容没有限制。

查找的内容不限于单个字段或列的值。查找字符串的内容可以是显示的任务行中的一切值。可以包括空格、数字、符号，甚至森林视图里的 ASCII 艺术。

在没有输入内容的情况下按下 <Enter> 将会禁用 "&" 键，直到您输入新的查找字符串。

.TP  4
\fB&\fP\ \ :\fI查找下一个\fP
假设已经输入了查找字符串，\*(We 将尝试找到下一个匹配项。

.PP
找到匹配项后，将在垂直方向上重新放置当前窗口，使得包含该字符串的任务行位于第一行。您可以通过滚动坐标消息确认这种垂直方向上的重新放置的发生（\*(Xc\*(CI
"C"）。但是，水平方向上的坐标永远不会因为查找而改变。

以下因素牵涉到要匹配的字符串是否存在。
.RS +3
.TP  3
a. 在全部可用字段中，哪些字段是可显示的，
\*(Xt 3b. 管理字段。
.TP  3
b. 垂直或水平滚动窗口，
\*(Xt 5c. 滚动窗口。
.TP  3
c. 命令/命令行 切换开关的状态，
\*(Xc\*(CI "c"。
.TP  3
d. 所选择的排序列的稳定性，
例如，PID 可以，但是 %CPU 不行。
.RS -3

.PP
如果查找失败，将 "\*(CW恢复到 Home（未滚动的）位置、进行水平滚动、显示命令行，或选择更稳定的排序字段之后，仍然有可能成功使用 "&"
查找下一个。

在\*(FM中，上述\*(CI \fB总是\fP 可用，但在\*(AM中，如果 "\*(CW 的\*(TD被 \*F，则上述\*(CI总是 \fB不\fP 可用。

.\" ......................................................................
.SS "5e. 在窗口中筛选"
.\" ----------------------------------------------------------------------
您可以使用 "其他筛选" 功能来创建筛选标准，以确定哪些任务显示在 "\*(CW中。如果您执行\*(CI "W" 将此类筛选器保存在 rc
文件中，则可以使其永久生效。

创建筛选器至少需要：1) 字段名称；2) 运算符；3) 筛选值。这是 \*(We
中最复杂的对用户输入的要求，因此，当您犯错时，命令历史功能将是您的得力助手。当程序提示您输入内容时，请记得可以使用上/下\*(KA或其别名。

\fB筛选器基础知识\fP
.RS +3
.TP  3
1. 字段名称区分大小写，拼写与列标题中相同
.TP  3
2. 筛选值不需要包含显示的完整字段
.TP  3
3. 筛选值可以忽略大小写，也可以大小写敏感
.TP  3
4. 默认是包含，前面加上 "!" 表示排除
.TP  3
5. 一个\*(TW可以同时应用多个筛选标准
.TP  3
6. 可以同时应用包含和排除标准
.TP  3
7. 1 个判等 ("=") 和 2 个关系 (">", "<") 筛选器可以自由组合
.TP  3
8. 每个\*(TW有自己单独的已生效的筛选器的集合

.PP
如果字段未启用或当前不位于视图中，则您的筛选标准不会影响显示的任务。之后，如果筛选字段变得可见，则您的筛选标准将生效。
.RE

\fB按键概览\fP
.TP  6
\ \ \fBO\fP\ \ :\fI其他筛选\fP（大写）
程序将提示您创建 \fB大小写敏感\fP 的筛选器。

.TP  6
\ \ \fBo\fP\ \ :\fI其他筛选\fP（小写）
程序将提示您创建 \fB忽略大小写\fP 的筛选器。

.TP  6
\ \fB^O\fP\ \ :\fI显示生效的筛选器\fP（Ctrl 键 +\[oq]o\[cq]）
此命令可以提醒您 "\*(CW中哪些筛选器处于生效状态。将在消息行上显示筛选器概览，直到您按下 <Enter> 键。

.TP  6
\ \ \fB=\fP\ \ :\fI重置筛选器\fP，对当前窗口生效
此命令将清除 "\*(CW中的所有筛选标准。它还会产生其他影响，因此请\*(Xt 4a. 全局命令。

.TP  6
\ \ \fB+\fP\ \ :\fI重置筛选器\fP，对所有窗口生效
假设您处于\*(AM，此命令将清除所有窗口中的筛选标准。与\*(CI "=" 一样，它也会产生其他影响，因此您可能需要\*(Xt 5b. 窗口命令。

.PP
\fB输入要求\fP
.RS +3
.P
当程序提示您输入筛选标准时，您提供的数据必须使用两种格式之一。有 3 项必需信息，第 4 项为可选信息。
为了方便阅读，这些示例包含空格，但您的输入通常不包含。
.nf
        #1           \fB#2\fP  #3              （必需）
        字段名称     ?   包含的值
     \fB!\fP  字段名称     ?   \fB排除\fP的值
     #4                                  （可选）
.fi

#1、#3 和 #4 应该无需进一步解释。\fB#2\fP 既是必需的 \fI分隔符\fP，也是 \fI运算符\fP，它必须是判等（"="）或关系运算符（"<"
或 ">"）之一。

"=" 判等运算符仅要求部分匹配，这可以减少 "值" 的输入长度。">" 或 "<"
关系运算符始终使用字符串比较，即使对于数字字段也是如此。在设计上，它们在字段使用默认 \fI对齐方式\fP
和显示相同单位的数据时是能够正常工作的。当字段的某些数值被 \fI缩放\fP 而其他数值没有被 \fI缩放\fP 时，字段的数据就不再是相同单位的了。

如果您创建了关系筛选器并且您 \fB已经\fP 更改了默认的数字或字符 \fI对齐方式\fP，则该筛选器可能会无法正常工作。当关系筛选器应用于内存字段并且您
\fB尚未\fP 更改 \fI单位\fP 时，可能会产生误导性结果。这样说是因为，比如说，当视为字符串进行比较时，"100.0m" (MiB) 将被视为大于
"1.000g" (GiB)。

如果您的筛选结果看起来很可疑，可能只需更改对齐或缩放即可实现所需的效果。请参阅\*(CI "j"、"J" 和 "e" 了解更多信息。
.RE

\fB潜在的问题\fP
.RS +3
.P
这两个 \fB组 (GROUP)\fP 筛选器可能会产生完全相同的结果，也有可能第二个筛选器根本不显示任何内容，只产生一个空白的\*(TW。
.nf
     组=root           （ 仅在使用小写 "o" 命令时 ）
     组=ROOT           （ 结果相同                ）
.fi

这两个 \fB驻留 (RES)\fP
筛选器中的任何一个都可能产生不一致和/或有误导性的结果，具体取决于当前的内存缩放系数。或者这两个筛选器也有可能产生完全相同的结果。
.nf
     驻留>9999         （ 仅在内存单位是 "KiB" 时 ）
     !驻留<10000       （ 结果相同                ）
.fi

这个 \fB主要 (nMin)\fP 筛选器阐明了可缩放字段特有的问题。这个特定的字段最多可显示 4 位数字，超出该数字的值会自动缩放至 KiB
或以上。因此，虽然存在大于 9999 的数字，但它们将显示为 2.6m、197k 等。
.nf
     主要>9999         （ 永远产生空白的\*(TW ）
.fi
.RE

\fB潜在的解决方案\fP
.RS +3
.P
这些示例说明了如何创造性地使用 "其他筛选"
来实现几乎任何想要的结果。示例中有时会使用单引号来较为清晰地表示出筛选器中的空格，或者用来准确地表示请求筛选器状态 (^O)
命令的输出。但如果您在实际使用时在 "筛选值" 中包含单引号，则将无法找到匹配项。

假设字段 \fB线 (nTH)\fP
当前正在显示，第一个筛选器将导致仅显示多线程的进程。这个例子还提醒我们，末尾的空格是每个显示的字段的一部分。第二个筛选器以更少的输入实现了完全相同的结果。
.nf
     !线=' 1 '                 ( ' 只是为了方便阅读 )
     线>1                      ( 输入更短，结果相同 )
.fi

当森林视图模式已启用，并且 \fB命令 (COMMAND)\fP 列处于视图中时，此筛选器相当于折叠子进程，使得窗口中只显示 3 层。
.nf
     !命令='       `\- '        ( ' 只是为了方便阅读 )
.fi

最后两组筛选器表示为请求筛选器状态 (^O) 命令的输出。实际上，每个筛选器都需要单独输入。下述 \fB优 (PR)\fP 示例说明了显示优先级为 20
或更高的任务需同时使用的两个筛选器，因为有些优先级可能为负值。然后，通过利用末尾空格，下述 \fB次要 (nMin)\fP
筛选器序列可以实现上面讨论过的失败的 "9999" 筛选目标。
.nf
     '优>20' + '!优=\-'         （ 需要 2 个筛选器才能得到正确结果 ）
     '!次要=0 ' + '!次要=1 ' + '!次要=2 ' + '!次要=3 ' ...
.fi
.RS -3

.\" ----------------------------------------------------------------------
.SH "6. 文件"
.\" ----------------------------------------------------------------------
.SS "6a. 个人配置文件"
.\" ----------------------------------------------------------------------
此文件可通过\*(CI "W" 创建或更新。

旧版本的配置文件是 "$HOME/.您给\*(We取的名字" + "rc"，前面有一个 "."。

新创建的\*(CF是 "procps/您给\*(We取的名字" + "rc"，前面没有 "."。当 $XDG_CONFIG_HOME
变量设置为一个绝对路径时，会在其中创建 procps 目录，否则，在 $HOME/.config 中创建。

虽然不希望用户手动编辑该文件，但配置文件的总体布局如下：
.nf
     全局    # 行  1: 程序名称/别名记录
      "      # 行  2: id,altscr,irixps,delay,curwin
    每个窗   # 行  a: winname,fieldscur
    口一组   # 行  b: winflags,sortindx,maxtasks 等
      "      # 行  c: summclr,msgsclr,headclr,taskclr
     全局    # 行 15: 其他杂项设置
      "      # 任何剩余的行都是可选的
      "      # 生效的 "其他筛选器"，在上文 5e 节讨论
      "      # 加上 "检视" 条目，在下文 6b 节讨论
.fi

如果无法生成有效的指向 rc 文件的绝对路径，则对正在运行的 \*(We 作出的个性化设置将无法保留。

.\" ......................................................................
.SS "6b. 添加检视条目"
.\" ----------------------------------------------------------------------
要使用\*(CI "Y"，您必须将条目添加到 \*(We 个人\*(CF的
\fB末尾\fP。此类条目仅包含要读取的文件或要执行的命令/管道，其执行结果将显示在单独的可滚动、可搜索的窗口中。

如果您不知道 \*(We rc 文件的位置或名称，请使用\*(CI "W"，然后注意其中的细节。

可以通过使用重定向的 echo 命令，或者编辑\*(CF来添加检视条目。使用重定向的 echo 命令时，如果您使用了替换 (>) 而不是追加
(>>) 到该文件，则可能会导致 rc
文件被覆盖。相对地，使用编辑器时必须注意不要损坏现有行，其中某些行可能包含不可打印的数据或不寻常的字符，具体取决于保存该\*(CF的 \*(We 版本。

以 "#" 字符开头的检视条目会被忽略，无论其内容如何。否则，检视条目由以下 3 个元素组成，每个元素之间 \fI必须\fP 用制表符隔开（所以总共有 2 个
"\et"）：

.nf
  .type（类型）： 为 "file" 或 "pipe" 之一
  .name（名称）： 检视屏幕上的选择区域显示的名称
  .fmts（格式）： 表示路径或命令的字符串
.fi

这两种类型的检视条目 \fI不能\fP 相互替代。指定为 "\fBfile\fP" 的条目将使用 fopen 进行访问，并且在 ".fmts"
元素中必须引用单个文件。 指定为 "\fBpipe\fP" 的条目将使用 popen，它们的 ".fmts"
元素可以包含许多通过管道连接的命令，并且所有命令都不能与用户进行交互。

如果 ".fmts" 中包含的文件名或管道需要包含您在提示符处输入或者直接接受的那个特定的 PID，则格式字符串中还必须使用 "\fB%d\fP"
说明符，如下面这些例子所示。

.nf
  .fmts=  /proc/\fI%d\fP/numa_maps
  .fmts=  lsof \-P \-p\fI %d\fP
.fi

仅对于 "\fBpipe\fP" 类型条目而言，您可能还希望将标准错误重定向到标准输出以获得更完整的结果。因此格式字符串将变为：

.nf
  .fmts=  pmap \-x %d\fI 2>&1\fP
.fi

以下是两种类型的检视条目的示例，这是它们在 rc 文件中的样子。由于开头的 "#" 字符，第一个条目将被忽略。为了清楚起见，例子里的伪制表符 (^I)
两边有额外的空格，但实际的制表符两边没有空格。
.nf

  # pipe ^I 套接字 ^I lsof \-n \-P \-i 2>&1
  pipe ^I 打开的文件 ^I lsof \-P \-p %d 2>&1
  file ^I NUMA 信息 ^I /proc/%d/numa_maps
  pipe ^I 日志 ^I tail \-n100 /var/log/syslog | sort \-Mr
.fi

除开上面被注释掉的条目，接下来的示例展示了如何通过 echo 实现类似的结果（假设 rc 文件名为
".toprc"）。然而，由于存在嵌入的制表符，每一行的开头都应该加上 "\fB/bin/echo \-e\fP"，而不仅仅是一个简单的
"echo"，这样无论您使用哪种 shell，都能正确解释反斜杠。

.nf
  "pipe\et打开的文件\etlsof \-P \-p %d 2>&1" >> ~/.toprc
  "file\etNUMA 信息\et/proc/%d/numa_maps" >> ~/.toprc
  "pipe\et日志\ettail \-n200 /var/log/syslog | sort \-Mr" >> ~/.toprc
.fi

如果您创建的任何检视条目生成了带有不可打印字符的输出，它们将以 ^C 表示法或十六进制 <FF>
形式显示，具体取决于它们的值。这也适用于制表符，它将显示为 "^I"。如果您需要更真实的表示方式，则应展开任何嵌入的制表符。下面的示例原本使用
"file" 条目，但改为使用 "pipe" 来展开嵌入的制表符。

.nf
  # 下面这行可能会包含 "\et" ...
  # file ^I <您选择的名称> ^I /proc/%d/status
  # 但下面这行将消除嵌入的 "\et" ...
  pipe ^I <您选择的名称> ^I cat /proc/%d/status | expand \-
.fi

\*(NT有些程序可能依赖 \fISIGINT\fP 来结束。因此，如果建立了如下所示的 "\fBpipe\fP"，则必须使用 Ctrl\-C
来终止它才能查看结果。这是 "^C" 不会同时终止 \*(We 的唯一情况。

.nf
  pipe ^I 追踪 ^I /usr/bin/strace \-p %d 2>&1
.fi

最后，虽然到目前为止，关于 "\fBpipe\fP" 类型条目的讨论使用的都是管道和命令，但没有什么可以阻止您使用
\fIshell脚本\fP。您也许甚至可以使用专门为\*(CI "Y" 设计的新创建的脚本。

例如，随着检视条目数量随时间的推移而增长，当 "选项：" 行超出屏幕宽度时，
该行将被截断。除了使某些选项不可见之外，这一问题不会影响您的操作。但是，如果某些选项因截断而无法显示，但您想查看更多选项，下面解释了一个简单的解决方案。

.nf
  检视 暂停于 pid ...
  使用： 左箭头/右箭头然后 <Enter> ...
  选项： 帮助  1  2  3  4  5  6  7  8  9  10  11 ...
.fi

\*(We 的 rc 文件中的条目的 ".name" 元素是一个数字编号，而 "help" 条目指向一个您编写的 shell
脚本，解释这些带编号的选项的实际含义。这样就可以使更多选项变为可见。

.\" ......................................................................
.SS "6c. 系统配置文件"
.\" ----------------------------------------------------------------------
此\*(CF存储尚未保存自己的\*(CF的用户的默认设置。文件格式与个人\*(CF完全相同，并且还可以包含上面描述的 "检视" 条目。

创建它的过程很简单。

1. 适当地配置您安装好的 \*(We，并使用\*(CI "W" 保存该配置。

2. 添加并测试任何想要的\[oq]检视\[cq]条目。

3. 将此\*(CF复制到 \fI/etc/\fP，并命名为\[oq]\fBtopdefaultrc\fP\[cq]。

.\" ......................................................................
.SS "6d. 系统限制文件"
.\" ----------------------------------------------------------------------
该文件的存在将决定向普通用户展示哪一版本的帮助屏幕。

更重要的是，它会限制普通用户在 \*(We 运行时可以执行的操作。他们将无法执行以下命令。
.nf
    k        杀死任务
    r        重新设置任务的 nice 值
    d 或 s   更改延迟/睡眠间隔
.fi

这个\*(CF不应该由 \*(We 创建。相反，需要手动创建它，并将其放置在 \fI/etc/\fP 目录中，命名为 "\fBtoprc\fP"。

它应该只有两行，如下面的例子所示：
.nf
    s        # 行 1: 安全模式开关
    5.0      # 行 2: 延迟间隔（秒）
.fi

.\" ----------------------------------------------------------------------
.SH "7. 环境变量"
.\" ----------------------------------------------------------------------
以下环境变量的值并不重要，重要的是它是否存在。

.IP LIBPROC_HIDE_KERNEL
这将阻止显示任何内核线程，并使得此类进程不被计入\*(SA的任务/线程计数。

.\" ----------------------------------------------------------------------
.SH "8. 傻瓜技巧集锦"
.\" ----------------------------------------------------------------------
这些技巧中的大部分技巧在您提升了 \*(We 的调度优先级之后会更加有效。因此，假设您有相应的权限，请考虑以 \-10 的 nice 值启动他。

.\" ......................................................................
.SS "8a. 内核魔术"
.\" ----------------------------------------------------------------------
.\" sorry, just can't help it -- don't ya love the sound of this?
.\" ( apparently AM static was a potential concern )
对于这些傻瓜技巧，\*(We 需要处于\*(FM。

.IP \(bu 3
用户界面的提示符和帮助屏幕有意暗示用户延迟只能设置为 0.1 秒的整数倍。事实上，您可以自由设置任何想设置的延迟。如果您想看到 Linux
的调度能力处于最佳状态，请尝试将延迟设置为 0.09 秒或更短。

要进行此实验，请在 x\-windows 下打开 xterm 并将其最大化。然后执行以下操作：
.nf
  . 执行以下命令提升调度优先级并设置很小的延迟：
      nice \-n \-10 \*(We \-d.09
  . 保持排序列高亮显示处于 \*F 状态，以使路径长度最短
  . \*O 反色和行高亮显示，以提供更明显的视觉效果
  . 尝试各种排序列（时间 (TIME) 或 MEM 效果很好），
    以及正序或逆序排序，以显示最活跃的进程
.fi

您将看到一个非常繁忙的 Linux 正在做他一直以来为您做的事情，却一直没有可用的程序来展示这一点。

.IP \(bu 3
在使用 "黑底白字" 颜色的 xterm 下，在 \*(We
的颜色映射屏幕上将任务颜色设置为黑色，并确保任务高亮设置为加粗，而不是反色。然后将延迟间隔设置为 0.3 秒左右。

在显示最活跃的进程后，您将仅看到当前正在运行的任务的幽灵一般的图像。

.IP \(bu 3
删除现有的 rc 文件，或创建一个新的符号链接。启动这个新版本，然后按下 "T"（一个隐藏命令，\*(Xt 4c. 任务区命令，排序），然后按下 "W"
和 "q"。最后，使用 \-d0（零延迟）重新启动程序。

您的显示将以三倍于旧版本 \*(We 的速度刷新，也就是 300% 的速度优势。随着 \*(We 在时间 (TIME)
排行榜上越爬越高，请耐心等待，并猜猜看 \*(We 是否最终能攀登到顶峰 (top)。

.\" ......................................................................
.SS "8b. 跳动窗口"
.\" ----------------------------------------------------------------------
对于这些傻瓜技巧，\*(We 需要处于\*(AM。

.IP \(bu 3
使 3 到 4 个 \*(TD可见，然后选择最后一个窗口以外的任意窗口，然后使用\*(CT "i" 来 \*F 空闲进程。根据您应用 "i"
命令的位置，\*(We 会尽力分配屏幕空间，有时会出现多个\*(TD在跳动，有时就像手风琴一样。

.IP \(bu 3
以不同的方式设置每个窗口的概览行：一个窗口不显示内存 ("m")；另一个不显示状态 ("t")；另一个可能什么都没有，只有消息行。然后按住 "a" 或
"w"，观看跳动窗口的变种 \*(Em 弹跳窗口。

.IP \(bu 3
显示所有 4 个窗口，并依次对每个窗口使用\*(CT "i" \*F 空闲进程。您已进入 "极度跳动" 区域。

.\" ......................................................................
.SS "8c. 大鸟窗口"
.\" ----------------------------------------------------------------------
这个傻瓜技巧也需要处于\*(AM。

.IP \(bu 3
显示所有 4 个窗口并确保 1:Def 是 "\*(CW。然后，使用\*(CI "n" 不断增加窗口大小，直到所有其他\*(TD被 "赶出鸟巢"。

当它们全部被移位后，使用\*(CT "_" 在所有窗口可见/不可见之间切换。然后思考一下：
.br
\*(We 是在撒谎还是诚实地说出您强加的真相？

.\" ......................................................................
.SS "8d. 峰回路转"
.\" ----------------------------------------------------------------------
这个傻瓜技巧在不处于\*(AM的情况下效果最好，因为对齐是每个窗口单独设置的。

.IP \(bu 3
启动 \*(We 并使命令 (COMMAND) 列是最后一个（最右侧）显示的列。如有必要，请使用\*(CT "c" 显示命令行，并使用\*(CT "V"
确保森林视图模式处于活动状态。

然后使用上/下\*(KA调整显示区域，使得显示的部分命令行被截断（最后一格显示 "+"）。您可能需要调整 xterm 的大小才能导致截断。

最后，使用\*(CT "j" 使命令 (COMMAND) 列右对齐。

现在使用右\*(KA定位到命令 (COMMAND) 列。继续使用右\*(KA，仔细观察显示的命令行的行进方向。

.br
   有些行向左，有些行向右

   最终所有行都峰回路转，一起向右

.\" ----------------------------------------------------------------------
.SH "9. 错误"
.\" ----------------------------------------------------------------------
请将错误报告发送到
.MT procps@freelists.org
.ME 。

 
.\" ----------------------------------------------------------------------
.SH "10. 参见"
.\" ----------------------------------------------------------------------
\fBfree\fP(1), \fBps\fP(1), \fBuptime\fP(1), \fBatop\fP(1), \fBslabtop\fP(1), \fBvmstat\fP(8),
\fBw\fP(1)
