# DO NOT EDIT! GENERATED AUTOMATICALLY!
# Copyright (C) 2002-2026 Free Software Foundation, Inc.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception to the GNU General Public License,
# this file may be distributed as part of a program that
# contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.
#
# This file represents the compiled summary of the specification in
# gnulib-cache.m4. It lists the computed macro invocations that need
# to be invoked from configure.ac.
# In projects that use version control, this file can be treated like
# other built files.


# This macro should be invoked from ./configure.ac, in the section
# "Checks for programs", right after AC_PROG_CC, and certainly before
# any checks for libraries, header files, types and library functions.
AC_DEFUN([gl_EARLY],
[
  m4_pattern_forbid([^gl_[A-Z]])dnl the gnulib macro namespace
  m4_pattern_allow([^gl_ES$])dnl a valid locale name
  m4_pattern_allow([^gl_LIBOBJS$])dnl a variable
  m4_pattern_allow([^gl_LTLIBOBJS$])dnl a variable

  # Pre-early section.
  AC_REQUIRE([gl_USE_SYSTEM_EXTENSIONS])
  AC_REQUIRE([gl_PROG_AR_RANLIB])

  # Code from module absolute-header:
  # Code from module accept:
  # Code from module accept-tests:
  # Code from module acl:
  # Code from module acl-permissions:
  # Code from module acl-tests:
  # Code from module alignasof:
  # Code from module alignasof-tests:
  # Code from module alloca:
  # Code from module alloca-opt:
  # Code from module alloca-opt-tests:
  # Code from module announce-gen:
  # Code from module arpa_inet-h:
  # Code from module arpa_inet-h-tests:
  # Code from module assert:
  # Code from module assert-h:
  # Code from module assert-h-tests:
  # Code from module attribute:
  # Code from module basename-lgpl:
  # Code from module binary-io:
  # Code from module binary-io-tests:
  # Code from module bind:
  # Code from module bind-tests:
  # Code from module bool:
  # Code from module bool-tests:
  # Code from module btoc32:
  # Code from module btoc32-tests:
  # Code from module btowc:
  # Code from module btowc-tests:
  # Code from module builtin-expect:
  # Code from module c-ctype:
  # Code from module c-ctype-tests:
  # Code from module c-strcasecmp:
  # Code from module c-strcasecmp-tests:
  # Code from module c-strcaseeq:
  # Code from module c-strcasestr:
  # Code from module c-strcasestr-tests:
  # Code from module c-strncasecmp:
  # Code from module c-strncasecmp-tests:
  # Code from module c32isprint:
  # Code from module c32isprint-tests:
  # Code from module c32isspace:
  # Code from module c32isspace-tests:
  # Code from module c32rtomb:
  # Code from module c32rtomb-tests:
  # Code from module c32tob:
  # Code from module c32tolower:
  # Code from module c32tolower-tests:
  # Code from module c32toupper:
  # Code from module c32toupper-tests:
  # Code from module c99:
  # Code from module calloc-gnu:
  # Code from module calloc-gnu-tests:
  # Code from module calloc-posix:
  # Code from module calloc-posix-tests:
  # Code from module canonicalize-lgpl:
  # Code from module canonicalize-lgpl-tests:
  # Code from module chdir:
  # Code from module chdir-tests:
  # Code from module clock-time:
  # Code from module cloexec:
  # Code from module cloexec-tests:
  # Code from module close:
  # Code from module close-tests:
  # Code from module closedir:
  # Code from module concat-filename:
  # Code from module connect:
  # Code from module connect-tests:
  # Code from module ctype-h:
  # Code from module ctype-h-tests:
  # Code from module dfa:
  # Code from module dfa-tests:
  # Code from module dirent-h:
  # Code from module dirent-h-tests:
  # Code from module dirfd:
  # Code from module dirfd-tests:
  # Code from module dirname-lgpl:
  # Code from module do-release-commit-and-tag:
  # Code from module double-slash-root:
  # Code from module dup2:
  # Code from module dup2-tests:
  # Code from module eloop-threshold:
  # Code from module environ:
  # Code from module environ-tests:
  # Code from module errno-h:
  # Code from module errno-h-tests:
  # Code from module error:
  # Code from module error-h:
  # Code from module error-tests:
  # Code from module exitfail:
  # Code from module extensions:
  # This is actually already done in the pre-early phase.
  # AC_REQUIRE([gl_USE_SYSTEM_EXTENSIONS])
  # Code from module extensions-aix:
  AC_REQUIRE([gl_USE_AIX_EXTENSIONS])
  # Code from module extern-inline:
  # Code from module fcntl:
  # Code from module fcntl-h:
  # Code from module fcntl-h-tests:
  # Code from module fcntl-tests:
  # Code from module fd-hook:
  # Code from module fdopen:
  # Code from module fdopen-tests:
  # Code from module fflush:
  AC_REQUIRE([gl_SET_LARGEFILE_SOURCE])
  # Code from module fflush-tests:
  # Code from module fgetc-tests:
  # Code from module file-has-acl:
  # Code from module file-has-acl-tests:
  # Code from module filename:
  # Code from module flexmember:
  # Code from module float-h:
  # Code from module float-h-tests:
  # Code from module fopen:
  # Code from module fopen-gnu:
  # Code from module fopen-gnu-tests:
  # Code from module fopen-tests:
  # Code from module fpieee:
  AC_REQUIRE([gl_FP_IEEE])
  # Code from module fpucw:
  # Code from module fpurge:
  # Code from module fpurge-tests:
  # Code from module fputc-tests:
  # Code from module fread-tests:
  # Code from module freading:
  # Code from module freading-tests:
  # Code from module free-posix:
  # Code from module free-posix-tests:
  # Code from module frexp:
  # Code from module frexp-tests:
  # Code from module frexpl:
  # Code from module frexpl-tests:
  # Code from module fseek:
  # Code from module fseek-tests:
  # Code from module fseeko:
  AC_REQUIRE([gl_SET_LARGEFILE_SOURCE])
  # Code from module fseeko-tests:
  # Code from module fseterr:
  # Code from module fseterr-tests:
  # Code from module fstat:
  # Code from module fstat-tests:
  # Code from module ftell:
  # Code from module ftell-tests:
  # Code from module ftello:
  AC_REQUIRE([gl_SET_LARGEFILE_SOURCE])
  # Code from module ftello-tests:
  # Code from module ftruncate:
  # Code from module ftruncate-tests:
  # Code from module fwrite-tests:
  # Code from module fwriting:
  # Code from module fwriting-tests:
  # Code from module gen-header:
  # Code from module gendocs:
  # Code from module getcwd-lgpl:
  # Code from module getcwd-lgpl-tests:
  # Code from module getdelim:
  # Code from module getdelim-tests:
  # Code from module getdtablesize:
  # Code from module getdtablesize-tests:
  # Code from module getlocalename_l-unsafe:
  # Code from module getlocalename_l-unsafe-limited:
  # Code from module getopt-gnu:
  # Code from module getopt-gnu-tests:
  # Code from module getopt-posix:
  # Code from module getopt-posix-tests:
  # Code from module getpagesize:
  # Code from module getprogname:
  # Code from module getprogname-tests:
  # Code from module getrandom:
  # Code from module getrandom-tests:
  # Code from module gettext-h:
  # Code from module gettext-h-tests:
  # Code from module gettimeofday:
  # Code from module gettimeofday-tests:
  # Code from module git-version-gen:
  # Code from module gitlog-to-changelog:
  # Code from module glibc-internal/dynarray:
  # Code from module glibc-internal/dynarray-tests:
  # Code from module glibc-internal/scratch_buffer:
  # Code from module glibc-internal/scratch_buffer-tests:
  # Code from module gnu-web-doc-update:
  # Code from module gnulib-i18n:
  # Code from module gnumakefile:
  # Code from module gnupload:
  # Code from module hard-locale:
  # Code from module hard-locale-tests:
  # Code from module ialloc:
  # Code from module idx:
  # Code from module ignore-value:
  # Code from module ignore-value-tests:
  # Code from module include_next:
  # Code from module inet_pton:
  # Code from module inet_pton-tests:
  # Code from module intprops:
  # Code from module intprops-tests:
  # Code from module inttypes-h:
  # Code from module inttypes-h-incomplete:
  # Code from module inttypes-h-tests:
  # Code from module ioctl:
  # Code from module ioctl-tests:
  # Code from module isblank:
  # Code from module isblank-tests:
  # Code from module isnand-nolibm:
  # Code from module isnand-nolibm-tests:
  # Code from module isnanf-nolibm:
  # Code from module isnanf-nolibm-tests:
  # Code from module isnanl-nolibm:
  # Code from module isnanl-nolibm-tests:
  # Code from module issymlink:
  # Code from module iswblank:
  # Code from module iswblank-tests:
  # Code from module iswctype:
  # Code from module iswctype-tests:
  # Code from module iswdigit:
  # Code from module iswdigit-tests:
  # Code from module iswpunct:
  # Code from module iswpunct-tests:
  # Code from module iswxdigit:
  # Code from module iswxdigit-tests:
  # Code from module langinfo-h:
  # Code from module langinfo-h-tests:
  # Code from module largefile:
  AC_REQUIRE([AC_SYS_LARGEFILE])
  # Code from module largefile-tests:
  # Code from module libc-config:
  # Code from module limits-h:
  # Code from module limits-h-tests:
  # Code from module link:
  # Code from module link-tests:
  # Code from module listen:
  # Code from module listen-tests:
  # Code from module localcharset:
  # Code from module localcharset-tests:
  # Code from module locale-h:
  # Code from module locale-h-tests:
  # Code from module localeconv:
  # Code from module localeconv-tests:
  # Code from module localename:
  # Code from module localename-environ:
  # Code from module localename-tests:
  # Code from module localename-unsafe:
  # Code from module localename-unsafe-limited:
  # Code from module lock:
  # Code from module lseek:
  # Code from module lseek-tests:
  # Code from module lstat:
  # Code from module lstat-tests:
  # Code from module maintainer-makefile:
  # Code from module malloc-gnu:
  # Code from module malloc-gnu-tests:
  # Code from module malloc-posix:
  # Code from module malloc-posix-tests:
  # Code from module malloca:
  # Code from module malloca-tests:
  # Code from module manywarnings:
  # Code from module math-h:
  # Code from module math-h-tests:
  # Code from module mbrtoc32:
  # Code from module mbrtoc32-regular:
  # Code from module mbrtoc32-regular-tests:
  # Code from module mbrtoc32-tests:
  # Code from module mbrtowc:
  # Code from module mbrtowc-tests:
  # Code from module mbsinit:
  # Code from module mbsinit-tests:
  # Code from module mbszero:
  # Code from module mbtowc:
  # Code from module memchr:
  # Code from module memchr-tests:
  # Code from module memeq:
  # Code from module mempcpy:
  # Code from module memrchr:
  # Code from module memrchr-tests:
  # Code from module memset_explicit:
  # Code from module memset_explicit-tests:
  # Code from module minmax:
  # Code from module mkdir:
  # Code from module mkdir-tests:
  # Code from module mkfifo:
  # Code from module mkfifo-tests:
  # Code from module mkostemp:
  # Code from module msvc-inval:
  # Code from module msvc-nothrow:
  # Code from module multiarch:
  # Code from module nan:
  # Code from module nanosleep:
  # Code from module nanosleep-tests:
  # Code from module netinet_in-h:
  # Code from module netinet_in-h-tests:
  # Code from module nl_langinfo:
  # Code from module nl_langinfo-tests:
  # Code from module nocrash:
  # Code from module obstack:
  # Code from module once:
  # Code from module once-tests:
  # Code from module open:
  # Code from module open-tests:
  # Code from module opendir:
  # Code from module package-version:
  # Code from module pathmax:
  # Code from module pathmax-tests:
  # Code from module perl:
  # Code from module perror:
  # Code from module perror-tests:
  # Code from module pipe-posix:
  # Code from module pipe-posix-tests:
  # Code from module progname:
  # Code from module pselect:
  # Code from module pselect-tests:
  # Code from module pthread-cond:
  # Code from module pthread-cond-tests:
  # Code from module pthread-h:
  gl_ANYTHREADLIB_EARLY
  # Code from module pthread-h-tests:
  # Code from module pthread-mutex:
  # Code from module pthread-mutex-tests:
  # Code from module pthread-once:
  # Code from module pthread-once-tests:
  # Code from module pthread-rwlock:
  # Code from module pthread-rwlock-tests:
  # Code from module pthread-thread:
  # Code from module pthread-thread-tests:
  # Code from module pthread_mutex_timedlock:
  # Code from module pthread_sigmask:
  # Code from module pthread_sigmask-tests:
  # Code from module putenv-gnu:
  # Code from module putenv-gnu-tests:
  # Code from module qcopy-acl:
  # Code from module qset-acl:
  # Code from module quote:
  # Code from module quotearg:
  # Code from module quotearg-simple:
  # Code from module quotearg-simple-tests:
  # Code from module raise:
  # Code from module raise-tests:
  # Code from module random:
  # Code from module random-tests:
  # Code from module random_r:
  # Code from module random_r-tests:
  # Code from module rawmemchr:
  # Code from module rawmemchr-tests:
  # Code from module read-file:
  # Code from module read-file-tests:
  # Code from module readdir:
  # Code from module readlink:
  # Code from module readlink-tests:
  # Code from module readme-release:
  # Code from module realloc-posix:
  # Code from module realloc-posix-tests:
  # Code from module reallocarray:
  # Code from module reallocarray-tests:
  # Code from module regex:
  # Code from module regex-tests:
  # Code from module rename:
  # Code from module rename-tests:
  # Code from module rmdir:
  # Code from module rmdir-tests:
  # Code from module same-inode:
  # Code from module sched-h:
  # Code from module sched-h-tests:
  # Code from module sched_yield:
  # Code from module select:
  # Code from module select-tests:
  # Code from module selinux-h:
  # Code from module selinux-h-tests:
  # Code from module setenv:
  # Code from module setenv-tests:
  # Code from module setlocale:
  # Code from module setlocale-fixes:
  # Code from module setlocale-null:
  # Code from module setlocale-null-tests:
  # Code from module setlocale-null-unlocked:
  # Code from module setlocale-null-unlocked-tests:
  # Code from module setlocale-tests:
  # Code from module setsockopt:
  # Code from module setsockopt-tests:
  # Code from module signal-h:
  # Code from module signal-h-tests:
  # Code from module signbit-no-c++:
  # Code from module signbit-no-c++-tests:
  # Code from module signed-nan:
  # Code from module signed-snan:
  # Code from module sigprocmask:
  # Code from module sigprocmask-tests:
  # Code from module sleep:
  # Code from module sleep-tests:
  # Code from module snan:
  # Code from module snippet/_Noreturn:
  # Code from module snippet/arg-nonnull:
  # Code from module snippet/c++defs:
  # Code from module snippet/warn-on-use:
  # Code from module socket:
  # Code from module socketlib:
  # Code from module sockets:
  # Code from module sockets-tests:
  # Code from module socklen:
  # Code from module ssize_t:
  # Code from module stat:
  # Code from module stat-macros:
  # Code from module stat-tests:
  # Code from module stat-time:
  # Code from module stat-time-tests:
  # Code from module std-gnu11:
  # Code from module stdarg-h:
  dnl Some compilers (e.g., AIX 5.3 cc) need to be in c99 mode
  dnl for the builtin va_copy to work.  gl_PROG_CC_C99 arranges for this.
  gl_PROG_CC_C99
  # Code from module stdarg-h-tests:
  # Code from module stdckdint-h:
  # Code from module stdckdint-h-tests:
  # Code from module stdcountof-h:
  # Code from module stdcountof-h-tests:
  # Code from module stddef-h:
  # Code from module stddef-h-tests:
  # Code from module stdint-h:
  # Code from module stdint-h-tests:
  # Code from module stdio-h:
  gl_STDIO_H_EARLY
  # Code from module stdio-h-tests:
  # Code from module stdio-windows:
  # Code from module stdlib-h:
  # Code from module stdlib-h-tests:
  # Code from module stpcpy:
  # Code from module str_endswith:
  # Code from module str_endswith-tests:
  # Code from module str_startswith:
  # Code from module str_startswith-tests:
  # Code from module strdup-posix:
  # Code from module streq:
  # Code from module streq-opt:
  # Code from module strerror:
  # Code from module strerror-override:
  # Code from module strerror-tests:
  # Code from module strerror_r-posix:
  # Code from module strerror_r-posix-tests:
  # Code from module string-h:
  # Code from module string-h-tests:
  # Code from module strncpy:
  # Code from module strncpy-tests:
  # Code from module strnul:
  # Code from module strnul-tests:
  # Code from module strtoimax:
  # Code from module strtoimax-tests:
  # Code from module strtoll:
  # Code from module strtoll-tests:
  # Code from module strverscmp:
  # Code from module strverscmp-tests:
  # Code from module symlink:
  # Code from module symlink-tests:
  # Code from module sys_ioctl-h:
  # Code from module sys_ioctl-h-tests:
  # Code from module sys_random-h:
  # Code from module sys_random-h-tests:
  # Code from module sys_select-h:
  # Code from module sys_select-h-tests:
  # Code from module sys_socket-h:
  # Code from module sys_socket-h-tests:
  # Code from module sys_stat-h:
  # Code from module sys_stat-h-tests:
  # Code from module sys_time-h:
  # Code from module sys_time-h-tests:
  # Code from module sys_types-h:
  AC_REQUIRE([AC_USE_SYSTEM_EXTENSIONS])
  # Code from module sys_types-h-tests:
  # Code from module sys_uio-h:
  # Code from module sys_uio-h-tests:
  # Code from module tempname:
  # Code from module test-framework-sh:
  # Code from module test-framework-sh-tests:
  # Code from module test-xfail:
  # Code from module thread:
  # Code from module thread-optim:
  # Code from module thread-tests:
  # Code from module threadlib:
  gl_THREADLIB_EARLY
  # Code from module time:
  # Code from module time-h:
  # Code from module time-h-tests:
  # Code from module time-tests:
  # Code from module trunc:
  # Code from module trunc-tests:
  # Code from module truncl:
  # Code from module truncl-tests:
  # Code from module uchar-h:
  # Code from module uchar-h-tests:
  # Code from module unicase/base:
  # Code from module unicase/base-tests:
  # Code from module unicase/tolower:
  # Code from module unicase/tolower-tests:
  # Code from module unicase/toupper:
  # Code from module unicase/toupper-tests:
  # Code from module unictype/base:
  # Code from module unictype/base-tests:
  # Code from module unictype/ctype-print:
  # Code from module unictype/ctype-print-tests:
  # Code from module unictype/ctype-space:
  # Code from module unictype/ctype-space-tests:
  # Code from module uninorm/base:
  # Code from module uninorm/base-tests:
  # Code from module unistd-h:
  # Code from module unistd-h-tests:
  # Code from module unitypes-h:
  # Code from module unlocked-io:
  # Code from module unlocked-io-internal:
  # Code from module unsetenv:
  # Code from module unsetenv-tests:
  # Code from module update-copyright:
  # Code from module update-copyright-tests:
  # Code from module useless-if-before-free:
  # Code from module vararrays:
  # Code from module vc-list-files:
  # Code from module vc-list-files-tests:
  # Code from module verify:
  # Code from module verify-tests:
  # Code from module version-etc:
  # Code from module version-etc-fsf:
  # Code from module version-etc-tests:
  # Code from module vma-iter:
  # Code from module warnings:
  # Code from module wchar-h:
  # Code from module wchar-h-tests:
  # Code from module wcrtomb:
  # Code from module wcrtomb-tests:
  # Code from module wctob:
  # Code from module wctomb:
  # Code from module wctype:
  # Code from module wctype-h:
  # Code from module wctype-h-tests:
  # Code from module wctype-tests:
  # Code from module windows-cond:
  # Code from module windows-mutex:
  # Code from module windows-mutex-tests:
  # Code from module windows-once:
  # Code from module windows-recmutex:
  # Code from module windows-recmutex-tests:
  # Code from module windows-rwlock:
  # Code from module windows-spin:
  # Code from module windows-thread:
  # Code from module windows-timedmutex:
  # Code from module windows-timedmutex-tests:
  # Code from module windows-timedrecmutex:
  # Code from module windows-timedrecmutex-tests:
  # Code from module windows-timedrwlock:
  # Code from module windows-tls:
  # Code from module xalloc:
  # Code from module xalloc-die:
  # Code from module xalloc-die-tests:
  # Code from module xalloc-oversized:
  # Code from module xconcat-filename:
  # Code from module xgetcwd-lgpl:
  # Code from module yield:
])

# This macro should be invoked from ./configure.ac, in the section
# "Check for header files, types and library functions".
AC_DEFUN([gl_INIT],
[
  AC_CONFIG_LIBOBJ_DIR([gnulib-tests])
  AM_CONDITIONAL([GL_COND_LIBTOOL], [false])
  gl_cond_libtool=false
  gl_libdeps=
  gl_ltlibdeps=
  gl_m4_base='m4'
  m4_pushdef([AC_LIBOBJ], m4_defn([gl_LIBOBJ]))
  m4_pushdef([AC_REPLACE_FUNCS], m4_defn([gl_REPLACE_FUNCS]))
  m4_pushdef([AC_LIBSOURCES], m4_defn([gl_LIBSOURCES]))
  m4_pushdef([gl_LIBSOURCES_LIST], [])
  m4_pushdef([gl_LIBSOURCES_DIR], [])
  m4_pushdef([GL_MACRO_PREFIX], [gl])
  m4_pushdef([GL_MODULE_INDICATOR_PREFIX], [GL])
  gl_COMMON
  gl_source_base='lib'
  gl_source_base_prefix='$(top_build_prefix)lib/'
  gl_FUNC_ACL
  gl_CONDITIONAL([GL_COND_OBJ_ACL_ENTRIES], [test $NEED_ACL_ENTRIES = 1])
  gl_ALIGNASOF
  gl_FUNC_ALLOCA
  gl_CONDITIONAL_HEADER([alloca.h])
  AC_PROG_MKDIR_P
  gl_ASSERT
  gl_ASSERT_H
  gl_CONDITIONAL_HEADER([assert.h])
  AC_PROG_MKDIR_P
  gl_C_BOOL
  gl_FUNC_BTOWC
  gl_CONDITIONAL([GL_COND_OBJ_BTOWC],
                 [test $HAVE_BTOWC = 0 || test $REPLACE_BTOWC = 1])
  AM_COND_IF([GL_COND_OBJ_BTOWC], [
    gl_PREREQ_BTOWC
  ])
  gl_WCHAR_MODULE_INDICATOR([btowc])
  gl___BUILTIN_EXPECT
  AC_REQUIRE([gl_UCHAR_H])
  dnl Determine REPLACE_MBSTATE_T, from which GNULIB_defined_mbstate_t is
  dnl determined.  It describes how mbrtoc32 is implemented.
  AC_REQUIRE([gl_MBSTATE_T_BROKEN])
  AC_REQUIRE([gl_MBRTOC32_SANITYCHECK])
  AC_REQUIRE([gl_C32RTOMB_SANITYCHECK])
  gl_UCHAR_MODULE_INDICATOR([c32isprint])
  AC_REQUIRE([gl_UCHAR_H])
  dnl Determine REPLACE_MBSTATE_T, from which GNULIB_defined_mbstate_t is
  dnl determined.  It describes how mbrtoc32 is implemented.
  AC_REQUIRE([gl_MBSTATE_T_BROKEN])
  AC_REQUIRE([gl_MBRTOC32_SANITYCHECK])
  AC_REQUIRE([gl_C32RTOMB_SANITYCHECK])
  gl_UCHAR_MODULE_INDICATOR([c32isspace])
  gl_FUNC_C32RTOMB
  gl_CONDITIONAL([GL_COND_OBJ_C32RTOMB],
                 [test $HAVE_C32RTOMB = 0 || test $REPLACE_C32RTOMB = 1])
  gl_UCHAR_MODULE_INDICATOR([c32rtomb])
  AC_REQUIRE([gl_MBRTOC32_SANITYCHECK])
  AC_REQUIRE([gl_C32RTOMB_SANITYCHECK])
  gl_UCHAR_MODULE_INDICATOR([c32tob])
  AC_REQUIRE([gl_UCHAR_H])
  dnl Determine REPLACE_MBSTATE_T, from which GNULIB_defined_mbstate_t is
  dnl determined.  It describes how mbrtoc32 is implemented.
  AC_REQUIRE([gl_MBSTATE_T_BROKEN])
  AC_REQUIRE([gl_MBRTOC32_SANITYCHECK])
  AC_REQUIRE([gl_C32RTOMB_SANITYCHECK])
  gl_UCHAR_MODULE_INDICATOR([c32tolower])
  AC_REQUIRE([gl_UCHAR_H])
  dnl Determine REPLACE_MBSTATE_T, from which GNULIB_defined_mbstate_t is
  dnl determined.  It describes how mbrtoc32 is implemented.
  AC_REQUIRE([gl_MBSTATE_T_BROKEN])
  AC_REQUIRE([gl_MBRTOC32_SANITYCHECK])
  AC_REQUIRE([gl_C32RTOMB_SANITYCHECK])
  gl_UCHAR_MODULE_INDICATOR([c32toupper])
  gl_FUNC_CALLOC_GNU
  if test $REPLACE_CALLOC_FOR_CALLOC_GNU = 1; then
    AC_LIBOBJ([calloc])
  fi
  gl_STDLIB_MODULE_INDICATOR([calloc-gnu])
  gl_FUNC_CALLOC_POSIX
  if test $REPLACE_CALLOC_FOR_CALLOC_POSIX = 1; then
    AC_LIBOBJ([calloc])
  fi
  gl_STDLIB_MODULE_INDICATOR([calloc-posix])
  gl_CANONICALIZE_LGPL
  gl_CONDITIONAL([GL_COND_OBJ_CANONICALIZE_LGPL],
                 [test $HAVE_CANONICALIZE_FILE_NAME = 0 || test $REPLACE_CANONICALIZE_FILE_NAME = 1])
  gl_MODULE_INDICATOR([canonicalize-lgpl])
  gl_STDLIB_MODULE_INDICATOR([canonicalize_file_name])
  gl_STDLIB_MODULE_INDICATOR([realpath])
  gl_UNISTD_MODULE_INDICATOR([chdir])
  gl_CLOCK_TIME
  gl_MODULE_INDICATOR_FOR_TESTS([cloexec])
  gl_FUNC_CLOSE
  gl_CONDITIONAL([GL_COND_OBJ_CLOSE], [test $REPLACE_CLOSE = 1])
  gl_UNISTD_MODULE_INDICATOR([close])
  gl_MODULE_INDICATOR([close])
  gl_CTYPE_H
  gl_CTYPE_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_REQUIRE([AC_C_INLINE])
  gl_DIRENT_H
  gl_DIRENT_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_DOUBLE_SLASH_ROOT
  gl_FUNC_DUP2
  gl_CONDITIONAL([GL_COND_OBJ_DUP2], [test $REPLACE_DUP2 = 1])
  AM_COND_IF([GL_COND_OBJ_DUP2], [
    gl_PREREQ_DUP2
  ])
  gl_UNISTD_MODULE_INDICATOR([dup2])
  gl_HEADER_ERRNO_H
  gl_CONDITIONAL_HEADER([errno.h])
  AC_PROG_MKDIR_P
  AC_REQUIRE([gl_ERROR_H])
  gl_ERROR
  gl_CONDITIONAL([GL_COND_OBJ_ERROR], [test $COMPILE_ERROR_C = 1])
  AM_COND_IF([GL_COND_OBJ_ERROR], [
    gl_PREREQ_ERROR
  ])
  m4_ifdef([AM_XGETTEXT_OPTION],
    [AM_][XGETTEXT_OPTION([--flag=error:3:c-format])
     AM_][XGETTEXT_OPTION([--flag=error_at_line:5:c-format])])
  gl_ERROR_H
  AC_PROG_MKDIR_P
  AC_REQUIRE([gl_EXTERN_INLINE])
  gl_FUNC_FCNTL
  gl_CONDITIONAL([GL_COND_OBJ_FCNTL],
                 [test $HAVE_FCNTL = 0 || test $REPLACE_FCNTL = 1])
  gl_FCNTL_MODULE_INDICATOR([fcntl])
  gl_FCNTL_H
  gl_FCNTL_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FILE_HAS_ACL
  AC_C_FLEXIBLE_ARRAY_MEMBER
  gl_FUNC_FREE
  gl_CONDITIONAL([GL_COND_OBJ_FREE], [test $REPLACE_FREE = 1])
  AM_COND_IF([GL_COND_OBJ_FREE], [
    gl_PREREQ_FREE
  ])
  gl_STDLIB_MODULE_INDICATOR([free-posix])
  gl_FUNC_FSETERR
  gl_CONDITIONAL([GL_COND_OBJ_FSETERR], [test $ac_cv_func___fseterr = no])
  gl_FUNC_FSTAT
  gl_CONDITIONAL([GL_COND_OBJ_FSTAT], [test $REPLACE_FSTAT = 1])
  AM_COND_IF([GL_COND_OBJ_FSTAT], [
    case "$host_os" in
      mingw* | windows*)
        AC_LIBOBJ([stat-w32])
        ;;
    esac
    gl_PREREQ_FSTAT
  ])
  gl_SYS_STAT_MODULE_INDICATOR([fstat])
  gl_MODULE_INDICATOR([fstat])
  gl_FUNC_FWRITING
  gl_CONDITIONAL([GL_COND_OBJ_FWRITING], [test $ac_cv_func___fwriting = no])
  gl_FUNC_GETDELIM
  gl_CONDITIONAL([GL_COND_OBJ_GETDELIM],
                 [test $HAVE_GETDELIM = 0 || test $REPLACE_GETDELIM = 1])
  AM_COND_IF([GL_COND_OBJ_GETDELIM], [
    gl_PREREQ_GETDELIM
  ])
  gl_STDIO_MODULE_INDICATOR([getdelim])
  gl_FUNC_GETDTABLESIZE
  gl_CONDITIONAL([GL_COND_OBJ_GETDTABLESIZE],
                 [test $HAVE_GETDTABLESIZE = 0 || test $REPLACE_GETDTABLESIZE = 1])
  AM_COND_IF([GL_COND_OBJ_GETDTABLESIZE], [
    gl_PREREQ_GETDTABLESIZE
  ])
  gl_UNISTD_MODULE_INDICATOR([getdtablesize])
  gl_FUNC_GETOPT_GNU
  dnl Because of the way gl_FUNC_GETOPT_GNU is implemented (the gl_getopt_required
  dnl mechanism), there is no need to do any AC_LIBOBJ or AC_SUBST here; they are
  dnl done in the getopt-posix module.
  gl_FUNC_GETOPT_POSIX
  gl_CONDITIONAL_HEADER([getopt.h])
  gl_CONDITIONAL_HEADER([getopt-cdefs.h])
  AC_PROG_MKDIR_P
  gl_CONDITIONAL([GL_COND_OBJ_GETOPT], [test $REPLACE_GETOPT = 1])
  AM_COND_IF([GL_COND_OBJ_GETOPT], [
    dnl Define the substituted variable GNULIB_UNISTD_H_GETOPT to 1.
    gl_UNISTD_H_REQUIRE_DEFAULTS
    gl_MODULE_INDICATOR_INIT_VARIABLE([GNULIB_UNISTD_H_GETOPT], [1])
  ])
  gl_UNISTD_MODULE_INDICATOR([getopt-posix])
  gl_MUSL_LIBC
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_FUNC_GETPROGNAME
  gl_CONDITIONAL([GL_COND_OBJ_GETPROGNAME],
                 [test $HAVE_GETPROGNAME = 0 || test $REPLACE_GETPROGNAME = 1])
  AM_COND_IF([GL_COND_OBJ_GETPROGNAME], [
    gl_PREREQ_GETPROGNAME
  ])
  gl_STDLIB_MODULE_INDICATOR([getprogname])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_FUNC_GETRANDOM
  gl_CONDITIONAL([GL_COND_OBJ_GETRANDOM],
                 [test $HAVE_GETRANDOM = 0 || test $REPLACE_GETRANDOM = 1])
  gl_SYS_RANDOM_MODULE_INDICATOR([getrandom])
  gl_GETTEXT_H
  AC_PROG_MKDIR_P
  AC_PROG_MKDIR_P
  GNULIB_I18N
  # Autoconf 2.61a.99 and earlier don't support linking a file only
  # in VPATH builds.  But since GNUmakefile is for maintainer use
  # only, it does not matter if we skip the link with older autoconf.
  # Automake 1.10.1 and earlier try to remove GNUmakefile in non-VPATH
  # builds, so use a shell variable to bypass this.
  GNUmakefile=GNUmakefile
  m4_if(m4_version_compare([2.61a.100],
          m4_defn([m4_PACKAGE_VERSION])), [1], [],
        [AC_CONFIG_LINKS([$GNUmakefile:$GNUmakefile], [],
          [GNUmakefile=$GNUmakefile])])
  AC_REQUIRE([gl_FUNC_SETLOCALE_NULL])
  HARD_LOCALE_LIB="$SETLOCALE_NULL_LIB"
  AC_SUBST([HARD_LOCALE_LIB])
  dnl For backward compatibility.
  LIB_HARD_LOCALE="$HARD_LOCALE_LIB"
  AC_SUBST([LIB_HARD_LOCALE])
  gl_INTTYPES_INCOMPLETE
  gl_INTTYPES_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_MODULE_INDICATOR([issymlink])
  gl_FUNC_ISWBLANK
  gl_CONDITIONAL([GL_COND_OBJ_ISWBLANK],
                 [! { test $HAVE_ISWCNTRL = 0 || test $REPLACE_ISWCNTRL = 1; } && { test $HAVE_ISWBLANK = 0 || test $REPLACE_ISWBLANK = 1; }])
  gl_WCTYPE_MODULE_INDICATOR([iswblank])
  gl_FUNC_ISWCTYPE
  gl_CONDITIONAL([GL_COND_OBJ_ISWCTYPE],
                 [test $HAVE_WCTYPE_T = 0 || test $GNULIBHEADERS_OVERRIDE_WINT_T = 1 || test $REPLACE_WCTYPE = 1])
  gl_WCTYPE_MODULE_INDICATOR([iswctype])
  gl_FUNC_ISWDIGIT
  gl_CONDITIONAL([GL_COND_OBJ_ISWDIGIT],
                 [! { test $HAVE_ISWCNTRL = 0 || test $REPLACE_ISWCNTRL = 1; } && test $REPLACE_ISWDIGIT = 1])
  gl_WCTYPE_MODULE_INDICATOR([iswdigit])
  gl_FUNC_ISWPUNCT
  gl_CONDITIONAL([GL_COND_OBJ_ISWPUNCT],
                 [! { test $HAVE_ISWCNTRL = 0 || test $REPLACE_ISWCNTRL = 1; } && test $REPLACE_ISWPUNCT = 1])
  gl_WCTYPE_MODULE_INDICATOR([iswpunct])
  gl_FUNC_ISWXDIGIT
  gl_CONDITIONAL([GL_COND_OBJ_ISWXDIGIT],
                 [! { test $HAVE_ISWCNTRL = 0 || test $REPLACE_ISWCNTRL = 1; } && test $REPLACE_ISWXDIGIT = 1])
  gl_WCTYPE_MODULE_INDICATOR([iswxdigit])
  gl_LANGINFO_H
  gl_LANGINFO_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_REQUIRE([gl_LARGEFILE])
  gl___INLINE
  gl_LIMITS_H
  gl_CONDITIONAL_HEADER([limits.h])
  AC_PROG_MKDIR_P
  gl_LOCALCHARSET
  dnl For backward compatibility. Some packages still use this.
  LOCALCHARSET_TESTS_ENVIRONMENT=
  AC_SUBST([LOCALCHARSET_TESTS_ENVIRONMENT])
  gl_LOCALE_H
  gl_LOCALE_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FUNC_LOCALECONV
  gl_CONDITIONAL([GL_COND_OBJ_LOCALECONV], [test $REPLACE_LOCALECONV = 1])
  AM_COND_IF([GL_COND_OBJ_LOCALECONV], [
    gl_PREREQ_LOCALECONV
  ])
  gl_LOCALE_MODULE_INDICATOR([localeconv])
  gl_MODULE_INDICATOR([localeconv])
  gl_LOCK
  gl_MODULE_INDICATOR([lock])
  gl_FUNC_LSTAT
  gl_CONDITIONAL([GL_COND_OBJ_LSTAT], [test $REPLACE_LSTAT = 1])
  AM_COND_IF([GL_COND_OBJ_LSTAT], [
    gl_PREREQ_LSTAT
  ])
  gl_SYS_STAT_MODULE_INDICATOR([lstat])
  gl_MODULE_INDICATOR([lstat])
  AC_CONFIG_COMMANDS_PRE([m4_ifdef([AH_HEADER],
    [AC_SUBST([CONFIG_INCLUDE], m4_defn([AH_HEADER]))])])
  AC_REQUIRE([AC_PROG_SED])
  AC_REQUIRE([AC_PROG_GREP])
  gl_FUNC_MALLOC_GNU
  if test $REPLACE_MALLOC_FOR_MALLOC_GNU = 1; then
    AC_LIBOBJ([malloc])
  fi
  gl_STDLIB_MODULE_INDICATOR([malloc-gnu])
  AC_REQUIRE([gl_FUNC_MALLOC_POSIX])
  if test $REPLACE_MALLOC_FOR_MALLOC_POSIX = 1; then
    AC_LIBOBJ([malloc])
  fi
  gl_STDLIB_MODULE_INDICATOR([malloc-posix])
  gl_MALLOCA
  gl_FUNC_MBRTOC32
  gl_CONDITIONAL([GL_COND_OBJ_MBRTOC32],
                 [test $HAVE_MBRTOC32 = 0 || test $REPLACE_MBRTOC32 = 1])
  AM_COND_IF([GL_COND_OBJ_MBRTOC32], [
    if test $REPLACE_MBSTATE_T = 1; then
      AC_LIBOBJ([lc-charset-dispatch])
      AC_LIBOBJ([mbtowc-lock])
      gl_PREREQ_MBTOWC_LOCK
    fi
    gl_PREREQ_MBRTOC32
  ])
  gl_UCHAR_MODULE_INDICATOR([mbrtoc32])
  gl_MODULE_INDICATOR([mbrtoc32-regular])
  gl_FUNC_MBRTOWC
  gl_CONDITIONAL([GL_COND_OBJ_MBRTOWC],
                 [test $HAVE_MBRTOWC = 0 || test $REPLACE_MBRTOWC = 1])
  AM_COND_IF([GL_COND_OBJ_MBRTOWC], [
    if test $REPLACE_MBSTATE_T = 1; then
      AC_LIBOBJ([lc-charset-dispatch])
      AC_LIBOBJ([mbtowc-lock])
      gl_PREREQ_MBTOWC_LOCK
    fi
    gl_PREREQ_MBRTOWC
  ])
  gl_WCHAR_MODULE_INDICATOR([mbrtowc])
  gl_FUNC_MBSINIT
  gl_CONDITIONAL([GL_COND_OBJ_MBSINIT],
                 [test $HAVE_MBSINIT = 0 || test $REPLACE_MBSINIT = 1])
  AM_COND_IF([GL_COND_OBJ_MBSINIT], [
    gl_PREREQ_MBSINIT
  ])
  gl_WCHAR_MODULE_INDICATOR([mbsinit])
  AC_REQUIRE([AC_TYPE_MBSTATE_T])
  gl_MBSTATE_T_BROKEN
  gl_MUSL_LIBC
  gl_WCHAR_MODULE_INDICATOR([mbszero])
  gl_FUNC_MBTOWC
  gl_CONDITIONAL([GL_COND_OBJ_MBTOWC],
                 [test $HAVE_MBTOWC = 0 || test $REPLACE_MBTOWC = 1])
  AM_COND_IF([GL_COND_OBJ_MBTOWC], [
    gl_PREREQ_MBTOWC
  ])
  gl_STDLIB_MODULE_INDICATOR([mbtowc])
  gl_FUNC_MEMCHR
  gl_CONDITIONAL([GL_COND_OBJ_MEMCHR], [test $REPLACE_MEMCHR = 1])
  AM_COND_IF([GL_COND_OBJ_MEMCHR], [
    gl_PREREQ_MEMCHR
  ])
  gl_STRING_MODULE_INDICATOR([memchr])
  gl_FUNC_MEMEQ
  gl_STRING_MODULE_INDICATOR([memeq])
  gl_FUNC_MEMPCPY
  gl_CONDITIONAL([GL_COND_OBJ_MEMPCPY],
                 [test $HAVE_MEMPCPY = 0 || test $REPLACE_MEMPCPY = 1])
  AM_COND_IF([GL_COND_OBJ_MEMPCPY], [
    gl_PREREQ_MEMPCPY
  ])
  gl_STRING_MODULE_INDICATOR([mempcpy])
  gl_FUNC_MEMRCHR
  gl_CONDITIONAL([GL_COND_OBJ_MEMRCHR], [test $ac_cv_func_memrchr = no])
  AM_COND_IF([GL_COND_OBJ_MEMRCHR], [
    gl_PREREQ_MEMRCHR
  ])
  gl_STRING_MODULE_INDICATOR([memrchr])
  gl_MINMAX
  gl_FUNC_MKDIR
  gl_CONDITIONAL([GL_COND_OBJ_MKDIR], [test $REPLACE_MKDIR = 1])
  gl_SYS_STAT_MODULE_INDICATOR([mkdir])
  gl_FUNC_MKOSTEMP
  gl_CONDITIONAL([GL_COND_OBJ_MKOSTEMP],
                 [test $HAVE_MKOSTEMP = 0 || test $REPLACE_MKOSTEMP = 1])
  AM_COND_IF([GL_COND_OBJ_MKOSTEMP], [
    gl_PREREQ_MKOSTEMP
  ])
  gl_MODULE_INDICATOR([mkostemp])
  gl_STDLIB_MODULE_INDICATOR([mkostemp])
  AC_REQUIRE([gl_MSVC_INVAL])
  gl_CONDITIONAL([GL_COND_OBJ_MSVC_INVAL],
                 [test $HAVE_MSVC_INVALID_PARAMETER_HANDLER = 1])
  AC_REQUIRE([gl_MSVC_NOTHROW])
  gl_CONDITIONAL([GL_COND_OBJ_MSVC_NOTHROW],
                 [test $HAVE_MSVC_INVALID_PARAMETER_HANDLER = 1])
  gl_MODULE_INDICATOR([msvc-nothrow])
  gl_MULTIARCH
  gl_FUNC_NL_LANGINFO
  gl_CONDITIONAL([GL_COND_OBJ_NL_LANGINFO],
                 [test $HAVE_NL_LANGINFO = 0 || test $REPLACE_NL_LANGINFO = 1])
  gl_CONDITIONAL([GL_COND_OBJ_NL_LANGINFO_LOCK],
                 [test $REPLACE_NL_LANGINFO = 1 && test $NL_LANGINFO_MTSAFE = 0])
  if test $REPLACE_NL_LANGINFO = 1 && test $NL_LANGINFO_MTSAFE = 0; then
    gl_PREREQ_NL_LANGINFO_LOCK
  fi
  gl_LANGINFO_MODULE_INDICATOR([nl_langinfo])
  gl_FUNC_OBSTACK
  gl_CONDITIONAL_HEADER([obstack.h])
  gl_CONDITIONAL([GL_COND_OBJ_OBSTACK],
                 [test $HAVE_OBSTACK = 0 || test $REPLACE_OBSTACK = 1])
  AC_PROG_MKDIR_P
  gl_ONCE
  gl_FUNC_OPEN
  gl_CONDITIONAL([GL_COND_OBJ_OPEN], [test $REPLACE_OPEN = 1])
  AM_COND_IF([GL_COND_OBJ_OPEN], [
    gl_PREREQ_OPEN
  ])
  gl_FCNTL_MODULE_INDICATOR([open])
  gl_PATHMAX
  gl_PERL
  AC_CHECK_DECLS([program_invocation_name], [], [], [#include <errno.h>])
  AC_CHECK_DECLS([program_invocation_short_name], [], [], [#include <errno.h>])
  gl_PTHREAD_H
  gl_PTHREAD_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_PTHREAD_ONCE
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_ONCE],
                 [test $HAVE_PTHREAD_ONCE = 0 || test $REPLACE_PTHREAD_ONCE = 1])
  gl_PTHREAD_MODULE_INDICATOR([pthread-once])
  gl_QCOPY_ACL
  gl_QUOTE
  gl_QUOTEARG
  gl_FUNC_RAWMEMCHR
  gl_CONDITIONAL([GL_COND_OBJ_RAWMEMCHR], [test $HAVE_RAWMEMCHR = 0])
  AM_COND_IF([GL_COND_OBJ_RAWMEMCHR], [
    gl_PREREQ_RAWMEMCHR
  ])
  gl_STRING_MODULE_INDICATOR([rawmemchr])
  gl_FUNC_READLINK
  gl_CONDITIONAL([GL_COND_OBJ_READLINK],
                 [test $HAVE_READLINK = 0 || test $REPLACE_READLINK = 1])
  AM_COND_IF([GL_COND_OBJ_READLINK], [
    gl_PREREQ_READLINK
  ])
  gl_UNISTD_MODULE_INDICATOR([readlink])
  gl_FUNC_REALLOC_POSIX
  gl_FUNC_REALLOC_0_NONNULL
  gl_CONDITIONAL([GL_COND_OBJ_REALLOC_POSIX],
                 [test $REPLACE_REALLOC_FOR_REALLOC_POSIX != 0])
  gl_STDLIB_MODULE_INDICATOR([realloc-posix])
  gl_FUNC_REALLOCARRAY
  gl_CONDITIONAL([GL_COND_OBJ_REALLOCARRAY],
                 [test $HAVE_REALLOCARRAY = 0 || test $REPLACE_REALLOCARRAY = 1])
  AM_COND_IF([GL_COND_OBJ_REALLOCARRAY], [
    gl_PREREQ_REALLOCARRAY
  ])
  gl_MODULE_INDICATOR([reallocarray])
  gl_STDLIB_MODULE_INDICATOR([reallocarray])
  gl_REGEX
  gl_CONDITIONAL([GL_COND_OBJ_REGEX], [test $ac_use_included_regex = yes])
  AM_COND_IF([GL_COND_OBJ_REGEX], [
    gl_PREREQ_REGEX
  ])
  gl_FUNC_RENAME
  gl_CONDITIONAL([GL_COND_OBJ_RENAME], [test $REPLACE_RENAME = 1])
  gl_STDIO_MODULE_INDICATOR([rename])
  gl_FUNC_RMDIR
  gl_CONDITIONAL([GL_COND_OBJ_RMDIR], [test $REPLACE_RMDIR = 1])
  gl_UNISTD_MODULE_INDICATOR([rmdir])
  gl_SCHED_H
  gl_SCHED_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_HEADERS_SELINUX_SELINUX_H
  gl_HEADERS_SELINUX_CONTEXT_H
  gl_HEADERS_SELINUX_LABEL_H
  gl_CONDITIONAL_HEADER([selinux/context.h])
  gl_CONDITIONAL_HEADER([selinux/label.h])
  AC_PROG_MKDIR_P
  gl_CONDITIONAL([GL_COND_OBJ_GETFILECON],
                 [test "$with_selinux" != no && test "$ac_cv_header_selinux_selinux_h" = yes])
  gl_FUNC_SETLOCALE_NULL
  gl_CONDITIONAL([GL_COND_OBJ_SETLOCALE_LOCK],
                 [test $SETLOCALE_NULL_ALL_MTSAFE = 0 || test $SETLOCALE_NULL_ONE_MTSAFE = 0])
  AM_COND_IF([GL_COND_OBJ_SETLOCALE_LOCK], [
    gl_PREREQ_SETLOCALE_LOCK
  ])
  gl_LOCALE_MODULE_INDICATOR([setlocale_null])
  gt_TYPE_SSIZE_T
  gl_FUNC_STAT
  gl_CONDITIONAL([GL_COND_OBJ_STAT], [test $REPLACE_STAT = 1])
  AM_COND_IF([GL_COND_OBJ_STAT], [
    case "$host_os" in
      mingw* | windows*)
        AC_LIBOBJ([stat-w32])
        ;;
    esac
    gl_PREREQ_STAT
  ])
  gl_SYS_STAT_MODULE_INDICATOR([stat])
  gl_MODULE_INDICATOR([stat])
  gl_STAT_TIME
  gl_STAT_BIRTHTIME
  gl_STDARG_H
  gl_CONDITIONAL_HEADER([stdarg.h])
  AC_PROG_MKDIR_P
  gl_STDCKDINT_H
  gl_CONDITIONAL_HEADER([stdckdint.h])
  AC_PROG_MKDIR_P
  gl_STDCOUNTOF_H
  gl_CONDITIONAL_HEADER([stdcountof.h])
  AC_PROG_MKDIR_P
  gl_STDDEF_H
  gl_STDDEF_H_REQUIRE_DEFAULTS
  gl_CONDITIONAL_HEADER([stddef.h])
  AC_PROG_MKDIR_P
  gl_STDINT_H
  gl_CONDITIONAL_HEADER([stdint.h])
  dnl Because of gl_REPLACE_LIMITS_H:
  gl_CONDITIONAL_HEADER([limits.h])
  AC_PROG_MKDIR_P
  gl_STDIO_H
  gl_STDIO_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_CONDITIONAL([GL_COND_OBJ_STDIO_READ], [test $REPLACE_STDIO_READ_FUNCS = 1])
  gl_CONDITIONAL([GL_COND_OBJ_STDIO_WRITE], [test $REPLACE_STDIO_WRITE_FUNCS = 1])
  dnl No need to create extra modules for these functions. Everyone who uses
  dnl <stdio.h> likely needs them.
  gl_STDIO_MODULE_INDICATOR([fscanf])
  gl_MODULE_INDICATOR([fscanf])
  gl_STDIO_MODULE_INDICATOR([scanf])
  gl_MODULE_INDICATOR([scanf])
  gl_STDIO_MODULE_INDICATOR([fgetc])
  gl_STDIO_MODULE_INDICATOR([getc])
  gl_STDIO_MODULE_INDICATOR([getchar])
  gl_STDIO_MODULE_INDICATOR([fgets])
  gl_STDIO_MODULE_INDICATOR([fread])
  dnl No need to create extra modules for these functions. Everyone who uses
  dnl <stdio.h> likely needs them.
  gl_STDIO_MODULE_INDICATOR([fprintf])
  gl_STDIO_MODULE_INDICATOR([printf])
  gl_STDIO_MODULE_INDICATOR([vfprintf])
  gl_STDIO_MODULE_INDICATOR([vprintf])
  gl_STDIO_MODULE_INDICATOR([fputc])
  gl_STDIO_MODULE_INDICATOR([putc])
  gl_STDIO_MODULE_INDICATOR([putchar])
  gl_STDIO_MODULE_INDICATOR([fputs])
  gl_STDIO_MODULE_INDICATOR([puts])
  gl_STDIO_MODULE_INDICATOR([fwrite])
  AC_REQUIRE([AC_CANONICAL_HOST])
  USES_MSVCRT=0
  case "$host_os" in
    mingw* | windows*)
      AC_EGREP_CPP([Special], [
  #ifndef _UCRT
   Special
  #endif
        ],
        [USES_MSVCRT=1])
      ;;
  esac
  gl_CONDITIONAL([GL_COND_OBJ_STDIO_CONSOLESAFE], [test $USES_MSVCRT = 1])
  AC_CHECK_FUNCS_ONCE([vasprintf])
  gl_STDLIB_H
  gl_STDLIB_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FUNC_STREQ
  gl_STRING_MODULE_INDICATOR([streq])
  gl_FUNC_STRERROR
  gl_CONDITIONAL([GL_COND_OBJ_STRERROR], [test $REPLACE_STRERROR = 1])
  gl_MODULE_INDICATOR([strerror])
  gl_STRING_MODULE_INDICATOR([strerror])
  AC_REQUIRE([gl_HEADER_ERRNO_H])
  AC_REQUIRE([gl_FUNC_STRERROR_0])
  gl_CONDITIONAL([GL_COND_OBJ_STRERROR_OVERRIDE],
                 [test -n "$ERRNO_H" || test $REPLACE_STRERROR_0 = 1])
  AM_COND_IF([GL_COND_OBJ_STRERROR_OVERRIDE], [
    gl_PREREQ_SYS_H_WINSOCK2
  ])
  gl_STRING_H
  gl_STRING_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FUNC_STRNCPY
  gl_CONDITIONAL([GL_COND_OBJ_STRNCPY], [test $REPLACE_STRNCPY = 1])
  AM_COND_IF([GL_COND_OBJ_STRNCPY], [
    gl_PREREQ_STRNCPY
  ])
  gl_STRING_MODULE_INDICATOR([strncpy])
  gl_STRING_MODULE_INDICATOR([strnul])
  gl_FUNC_STRTOIMAX
  gl_CONDITIONAL([GL_COND_OBJ_STRTOIMAX],
                 [test $HAVE_DECL_STRTOIMAX = 0 || test $REPLACE_STRTOIMAX = 1])
  AM_COND_IF([GL_COND_OBJ_STRTOIMAX], [
    gl_PREREQ_STRTOIMAX
  ])
  gl_INTTYPES_MODULE_INDICATOR([strtoimax])
  gl_FUNC_STRTOLL
  gl_CONDITIONAL([GL_COND_OBJ_STRTOLL],
                 [test $HAVE_STRTOLL = 0 || test $REPLACE_STRTOLL = 1])
  AM_COND_IF([GL_COND_OBJ_STRTOLL], [
    gl_PREREQ_STRTOLL
  ])
  gl_STDLIB_MODULE_INDICATOR([strtoll])
  gl_FUNC_STRVERSCMP
  gl_CONDITIONAL([GL_COND_OBJ_STRVERSCMP],
                 [test $HAVE_STRVERSCMP = 0 || test $REPLACE_STRVERSCMP = 1])
  AM_COND_IF([GL_COND_OBJ_STRVERSCMP], [
    gl_PREREQ_STRVERSCMP
  ])
  gl_STRING_MODULE_INDICATOR([strverscmp])
  gl_SYS_RANDOM_H
  gl_SYS_RANDOM_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SYS_STAT_H
  gl_SYS_STAT_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SYS_TYPES_H
  gl_SYS_TYPES_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FUNC_GEN_TEMPNAME
  gl_MODULE_INDICATOR([tempname])
  AC_REQUIRE([gl_THREADLIB])
  gl_TIME_H
  gl_TIME_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_UCHAR_H
  gl_UCHAR_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_LIBUNISTRING_LIBHEADER([1.2], [unicase.h])
  gl_UNICASE_H
  gl_UNICASE_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_LIBUNISTRING_MODULE([1.4], [unicase/tolower])
  gl_LIBUNISTRING_MODULE([1.4], [unicase/toupper])
  gl_LIBUNISTRING_LIBHEADER([1.3], [unictype.h])
  gl_UNICTYPE_H
  gl_UNICTYPE_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_REQUIRE([AC_C_INLINE])
  gl_LIBUNISTRING_MODULE([1.4], [unictype/ctype-print])
  AC_REQUIRE([AC_C_INLINE])
  gl_LIBUNISTRING_MODULE([1.4], [unictype/ctype-space])
  gl_LIBUNISTRING_LIBHEADER([1.2], [uninorm.h])
  gl_UNINORM_H
  gl_UNINORM_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_UNISTD_H
  gl_UNISTD_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_LIBUNISTRING_LIBHEADER([0.9.11], [unitypes.h])
  AC_PROG_MKDIR_P
  gl_UNITYPES_H
  AC_DEFINE([GNULIB_STDIO_SINGLE_THREAD], [1],
    [Define to 1 if you want the FILE stream functions getc, putc, etc.
     to use unlocked I/O if available, throughout the package.
     Unlocked I/O can improve performance, sometimes dramatically.
     But unlocked I/O is safe only in processes in which two threads
     never simultaneously access the same FILE stream.])
  AC_DEFINE([USE_UNLOCKED_IO], [GNULIB_STDIO_SINGLE_THREAD],
    [An alias of GNULIB_STDIO_SINGLE_THREAD.])
  gl_FUNC_GLIBC_UNLOCKED_IO
  AC_C_VARARRAYS
  gl_VERSION_ETC
  gl_WCHAR_H
  gl_WCHAR_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_FUNC_WCRTOMB
  gl_CONDITIONAL([GL_COND_OBJ_WCRTOMB],
                 [test $HAVE_WCRTOMB = 0 || test $REPLACE_WCRTOMB = 1])
  AM_COND_IF([GL_COND_OBJ_WCRTOMB], [
    gl_PREREQ_WCRTOMB
  ])
  gl_WCHAR_MODULE_INDICATOR([wcrtomb])
  gl_FUNC_WCTOB
  gl_CONDITIONAL([GL_COND_OBJ_WCTOB],
                 [test $HAVE_WCTOB = 0 || test $REPLACE_WCTOB = 1])
  AM_COND_IF([GL_COND_OBJ_WCTOB], [
    gl_PREREQ_WCTOB
  ])
  gl_WCHAR_MODULE_INDICATOR([wctob])
  gl_FUNC_WCTOMB
  gl_CONDITIONAL([GL_COND_OBJ_WCTOMB], [test $REPLACE_WCTOMB = 1])
  AM_COND_IF([GL_COND_OBJ_WCTOMB], [
    gl_PREREQ_WCTOMB
  ])
  gl_STDLIB_MODULE_INDICATOR([wctomb])
  gl_FUNC_WCTYPE
  gl_CONDITIONAL([GL_COND_OBJ_WCTYPE], [test $HAVE_WCTYPE = 0 || test $REPLACE_WCTYPE = 1])
  gl_WCTYPE_MODULE_INDICATOR([wctype])
  gl_WCTYPE_H
  gl_WCTYPE_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_MUTEX],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_ONCE],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_RECMUTEX],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_RWLOCK],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  gl_XALLOC
  gl_MODULE_INDICATOR([xalloc])
  gl_MODULE_INDICATOR([xalloc-die])
  # End of code from modules
  m4_ifval(gl_LIBSOURCES_LIST, [
    m4_syscmd([test ! -d ]m4_defn([gl_LIBSOURCES_DIR])[ ||
      for gl_file in ]gl_LIBSOURCES_LIST[ ; do
        if test ! -r ]m4_defn([gl_LIBSOURCES_DIR])[/$gl_file ; then
          echo "missing file ]m4_defn([gl_LIBSOURCES_DIR])[/$gl_file" >&2
          exit 1
        fi
      done])dnl
      m4_if(m4_sysval, [0], [],
        [AC_FATAL([expected source file, required through AC_LIBSOURCES, not found])])
  ])
  m4_popdef([GL_MODULE_INDICATOR_PREFIX])
  m4_popdef([GL_MACRO_PREFIX])
  m4_popdef([gl_LIBSOURCES_DIR])
  m4_popdef([gl_LIBSOURCES_LIST])
  m4_popdef([AC_LIBSOURCES])
  m4_popdef([AC_REPLACE_FUNCS])
  m4_popdef([AC_LIBOBJ])
  AC_CONFIG_COMMANDS_PRE([
    gl_libobjs=
    gl_ltlibobjs=
    gl_libobjdeps=
    gl_libsed_libobjs=
    gl_libsed_ltlibobjs=
    gl_libsed_libobjdeps=
    if test -n "$gl_LIBOBJS"; then
      # Remove the extension.
changequote(,)dnl
      sed_drop_objext='s/\.o$//;s/\.obj$//'
      sed_dirname1='s,//*,/,g'
      sed_dirname2='s,\(.\)/$,\1,'
      sed_dirname3='s,[^/]*$,,'
      sed_basename1='s,.*/,,'
changequote([, ])dnl
      for i in `for i in $gl_LIBOBJS; do echo "$i"; done | sed -e "$sed_drop_objext" | sort | uniq`; do
        gl_libobjs="$gl_libobjs lib/$i.$ac_objext"
        gl_ltlibobjs="$gl_ltlibobjs lib/$i.lo"
        i_dir=`echo "$i" | sed -e "$sed_dirname1" -e "$sed_dirname2" -e "$sed_dirname3"`
        i_base=`echo "$i" | sed -e "$sed_basename1"`
        gl_libsed_libobjs="$gl_libsed_libobjs lib/$i_dir""libsed_a-$i_base.$ac_objext"
        gl_libsed_ltlibobjs="$gl_libsed_ltlibobjs lib/$i_dir""libsed_la-$i_base.lo"
        gl_libobjdeps="$gl_libobjdeps lib/$i_dir\$(DEPDIR)/$i_base.Po"
        gl_libsed_libobjdeps="$gl_libsed_libobjdeps lib/$i_dir\$(DEPDIR)/libsed_a-$i_base.Po"
      done
    fi
    AC_SUBST([gl_LIBOBJS], [$gl_libobjs])
    AC_SUBST([gl_LTLIBOBJS], [$gl_ltlibobjs])
    AC_SUBST([gl_LIBOBJDEPS], [$gl_libobjdeps])
    AC_SUBST([gl_libsed_LIBOBJS], [$gl_libsed_libobjs])
    AC_SUBST([gl_libsed_LTLIBOBJS], [$gl_libsed_ltlibobjs])
    AC_SUBST([gl_libsed_LIBOBJDEPS], [$gl_libsed_libobjdeps])
  ])
  gltests_libdeps=
  gltests_ltlibdeps=
  m4_pushdef([AC_LIBOBJ], m4_defn([gltests_LIBOBJ]))
  m4_pushdef([AC_REPLACE_FUNCS], m4_defn([gltests_REPLACE_FUNCS]))
  m4_pushdef([AC_LIBSOURCES], m4_defn([gltests_LIBSOURCES]))
  m4_pushdef([gltests_LIBSOURCES_LIST], [])
  m4_pushdef([gltests_LIBSOURCES_DIR], [])
  m4_pushdef([GL_MACRO_PREFIX], [gltests])
  m4_pushdef([GL_MODULE_INDICATOR_PREFIX], [GL])
  gl_COMMON
  AC_REQUIRE([gl_CC_ALLOW_WARNINGS])
  AC_REQUIRE([gl_CXX_ALLOW_WARNINGS])
  gl_source_base='gnulib-tests'
  gl_source_base_prefix=
changequote(,)dnl
  gltests_WITNESS=IN_`echo "${PACKAGE-$PACKAGE_TARNAME}" | LC_ALL=C tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ | LC_ALL=C sed -e 's/[^A-Z0-9_]/_/g'`_GNULIB_TESTS
changequote([, ])dnl
  AC_SUBST([gltests_WITNESS])
  gl_module_indicator_condition=$gltests_WITNESS
  m4_pushdef([gl_MODULE_INDICATOR_CONDITION], [$gl_module_indicator_condition])
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_ACCEPT], [test "$ac_cv_header_winsock2_h" = yes])
  gl_SYS_SOCKET_MODULE_INDICATOR([accept])
  gl_MODULE_INDICATOR([accept])
  gl_ARPA_INET_H
  gl_ARPA_INET_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_BIND], [test "$ac_cv_header_winsock2_h" = yes])
  gl_SYS_SOCKET_MODULE_INDICATOR([bind])
  gl_MODULE_INDICATOR([bind])
  gl_UCHAR_MODULE_INDICATOR([btoc32])
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_FR
  gt_LOCALE_TR_UTF8
  gt_LOCALE_FR
  gt_LOCALE_TR_UTF8
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gl_MUSL_LIBC
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gl_MUSL_LIBC
  gl_FUNC_CLOSEDIR
  gl_CONDITIONAL([GL_COND_OBJ_CLOSEDIR],
                 [test $HAVE_CLOSEDIR = 0 || test $REPLACE_CLOSEDIR = 1])
  gl_DIRENT_MODULE_INDICATOR([closedir])
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_CONNECT], [test "$ac_cv_header_winsock2_h" = yes])
  gl_SYS_SOCKET_MODULE_INDICATOR([connect])
  gl_MODULE_INDICATOR([connect])
  gl_FUNC_DIRFD
  gl_CONDITIONAL([GL_COND_OBJ_DIRFD],
                 [test $HAVE_DIRFD = 0 || test $REPLACE_DIRFD = 1])
  AM_COND_IF([GL_COND_OBJ_DIRFD], [
    gl_PREREQ_DIRFD
  ])
  gl_DIRENT_MODULE_INDICATOR([dirfd])
  gl_ENVIRON
  gl_UNISTD_MODULE_INDICATOR([environ])
  gl_FUNC_FDOPEN
  gl_CONDITIONAL([GL_COND_OBJ_FDOPEN], [test $REPLACE_FDOPEN = 1])
  AM_COND_IF([GL_COND_OBJ_FDOPEN], [
    gl_PREREQ_FDOPEN
  ])
  gl_STDIO_MODULE_INDICATOR([fdopen])
  gl_FUNC_FFLUSH
  gl_CONDITIONAL([GL_COND_OBJ_FFLUSH], [test $REPLACE_FFLUSH = 1])
  AM_COND_IF([GL_COND_OBJ_FFLUSH], [
    gl_PREREQ_FFLUSH
  ])
  gl_MODULE_INDICATOR([fflush])
  gl_STDIO_MODULE_INDICATOR([fflush])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_FLOAT_H
  gl_CONDITIONAL_HEADER([float.h])
  AC_PROG_MKDIR_P
  gl_CONDITIONAL([GL_COND_OBJ_FLOAT],
                 [test $REPLACE_FLOAT_LDBL = 1 || test $REPLACE_FLOAT_SNAN = 1])
  gl_CONDITIONAL([GL_COND_OBJ_ITOLD], [test $REPLACE_ITOLD = 1])
  dnl Prerequisites of lib/float.c.
  AC_REQUIRE([gl_BIGENDIAN])
  gl_FUNC_FOPEN
  if test $REPLACE_FOPEN = 1; then
    AC_LIBOBJ([fopen])
    gl_PREREQ_FOPEN
  fi
  gl_STDIO_MODULE_INDICATOR([fopen])
  gl_FUNC_FOPEN_GNU
  if test $REPLACE_FOPEN_FOR_FOPEN_GNU = 1; then
    AC_LIBOBJ([fopen])
    gl_PREREQ_FOPEN
  fi
  gl_MODULE_INDICATOR([fopen-gnu])
  gl_STDIO_MODULE_INDICATOR([fopen-gnu])
  gl_FUNC_FPURGE
  gl_CONDITIONAL([GL_COND_OBJ_FPURGE],
                 [test $HAVE_FPURGE = 0 || test $REPLACE_FPURGE = 1])
  gl_STDIO_MODULE_INDICATOR([fpurge])
  gl_FUNC_FREADING
  AC_REQUIRE([gl_FUNC_FREXP])
  if test $gl_func_frexp != yes; then
    AC_LIBOBJ([frexp])
  fi
  gl_MATH_MODULE_INDICATOR([frexp])
  AC_REQUIRE([gl_FUNC_FREXPL])
  if test $HAVE_DECL_FREXPL = 0 || test $gl_func_frexpl = no; then
    AC_LIBOBJ([frexpl])
  fi
  gl_MATH_MODULE_INDICATOR([frexpl])
  gl_FUNC_FSEEK
  gl_CONDITIONAL([GL_COND_OBJ_FSEEK], [test $REPLACE_FSEEK = 1])
  gl_STDIO_MODULE_INDICATOR([fseek])
  gl_FUNC_UNGETC_WORKS
  gl_FUNC_FSEEKO
  gl_CONDITIONAL([GL_COND_OBJ_FSEEKO],
                 [test $HAVE_FSEEKO = 0 || test $REPLACE_FSEEKO = 1])
  AM_COND_IF([GL_COND_OBJ_FSEEKO], [
    gl_PREREQ_FSEEKO
  ])
  gl_STDIO_MODULE_INDICATOR([fseeko])
  gl_FUNC_UNGETC_WORKS
  gl_FUNC_FTELL
  gl_CONDITIONAL([GL_COND_OBJ_FTELL], [test $REPLACE_FTELL = 1])
  gl_STDIO_MODULE_INDICATOR([ftell])
  gl_FUNC_UNGETC_WORKS
  gl_FUNC_FTELLO
  gl_CONDITIONAL([GL_COND_OBJ_FTELLO],
                 [test $HAVE_FTELLO = 0 || test $REPLACE_FTELLO = 1])
  AM_COND_IF([GL_COND_OBJ_FTELLO], [
    gl_PREREQ_FTELLO
  ])
  gl_STDIO_MODULE_INDICATOR([ftello])
  gl_FUNC_UNGETC_WORKS
  gl_FUNC_FTRUNCATE
  gl_CONDITIONAL([GL_COND_OBJ_FTRUNCATE],
                 [test $HAVE_FTRUNCATE = 0 || test $REPLACE_FTRUNCATE = 1])
  AM_COND_IF([GL_COND_OBJ_FTRUNCATE], [
    gl_PREREQ_FTRUNCATE
  ])
  gl_UNISTD_MODULE_INDICATOR([ftruncate])
  gl_FUNC_GETCWD_LGPL
  gl_CONDITIONAL([GL_COND_OBJ_GETCWD_LGPL], [test $REPLACE_GETCWD = 1])
  gl_UNISTD_MODULE_INDICATOR([getcwd])
  gl_FUNC_GETLOCALENAME_L_UNSAFE
  gl_PREREQ_GETLOCALENAME_L_UNSAFE
  gl_LOCALE_MODULE_INDICATOR([getlocalename_l-unsafe])
  gl_FUNC_GETLOCALENAME_L_UNSAFE
  gl_PREREQ_GETLOCALENAME_L_UNSAFE
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_GETLOCALENAME_L_UNSAFE_LIMITED],
                 [case "$host_os" in openbsd* | aix* | *-android*) false;; *) true;; esac])
  gl_FUNC_GETPAGESIZE
  gl_CONDITIONAL([GL_COND_OBJ_GETPAGESIZE],
                 [test $HAVE_GETPAGESIZE = 0 || test $REPLACE_GETPAGESIZE = 1])
  gl_UNISTD_MODULE_INDICATOR([getpagesize])
  gl_FUNC_GETTIMEOFDAY
  gl_CONDITIONAL([GL_COND_OBJ_GETTIMEOFDAY],
                 [test $HAVE_GETTIMEOFDAY = 0 || test $REPLACE_GETTIMEOFDAY = 1])
  AM_COND_IF([GL_COND_OBJ_GETTIMEOFDAY], [
    gl_PREREQ_GETTIMEOFDAY
  ])
  gl_SYS_TIME_MODULE_INDICATOR([gettimeofday])
  gl_MUSL_LIBC
  dnl Distinguish OpenBSD >= 6.2 from OpenBSD < 6.2.
  gl_CHECK_FUNCS_ANDROID([duplocale], [[#include <locale.h>]])
  gl_FUNC_INET_PTON
  gl_CONDITIONAL([GL_COND_OBJ_INET_PTON],
                 [test $HAVE_INET_PTON = 0 || test $REPLACE_INET_PTON = 1])
  AM_COND_IF([GL_COND_OBJ_INET_PTON], [
    gl_PREREQ_INET_PTON
  ])
  gl_ARPA_INET_MODULE_INDICATOR([inet_pton])
  AC_C_BIGENDIAN
  gl_INTTYPES_H
  gl_FUNC_IOCTL
  gl_CONDITIONAL([GL_COND_OBJ_IOCTL],
                 [test $HAVE_IOCTL = 0 || test $REPLACE_IOCTL = 1])
  gl_SYS_IOCTL_MODULE_INDICATOR([ioctl])
  gl_MODULE_INDICATOR([ioctl])
  gl_FUNC_ISBLANK
  gl_CONDITIONAL([GL_COND_OBJ_ISBLANK], [test $HAVE_ISBLANK = 0])
  gl_MODULE_INDICATOR([isblank])
  gl_CTYPE_MODULE_INDICATOR([isblank])
  gl_FUNC_ISNAND_NO_LIBM
  if test $gl_func_isnand_no_libm != yes; then
    AC_LIBOBJ([isnand])
    gl_PREREQ_ISNAND
  fi
  gl_FUNC_ISNANF_NO_LIBM
  if test $gl_func_isnanf_no_libm != yes; then
    AC_LIBOBJ([isnanf])
    gl_PREREQ_ISNANF
  fi
  gl_FUNC_ISNANL_NO_LIBM
  if test $gl_func_isnanl_no_libm != yes; then
    AC_LIBOBJ([isnanl])
    gl_PREREQ_ISNANL
  fi
  AC_REQUIRE([gl_LONG_DOUBLE_VS_DOUBLE])
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gl_FUNC_LINK
  gl_CONDITIONAL([GL_COND_OBJ_LINK],
                 [test $HAVE_LINK = 0 || test $REPLACE_LINK = 1])
  gl_UNISTD_MODULE_INDICATOR([link])
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_LISTEN], [test "$ac_cv_header_winsock2_h" = yes])
  gl_SYS_SOCKET_MODULE_INDICATOR([listen])
  gl_MODULE_INDICATOR([listen])
  gl_WINDOWS_RC
  gl_CHECK_FUNCS_ANDROID([newlocale], [[#include <locale.h>]])
  gl_LOCALENAME_ENVIRON
  gl_LOCALE_MODULE_INDICATOR([localename-environ])
  gl_CHECK_FUNCS_ANDROID([newlocale], [[#include <locale.h>]])
  gl_MUSL_LIBC
  gl_WINDOWS_RC
  gl_LOCALENAME_UNSAFE
  gl_LOCALE_MODULE_INDICATOR([localename-unsafe])
  gl_MUSL_LIBC
  gl_LOCALENAME_UNSAFE_LIMITED
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_LOCALENAME_UNSAFE_LIMITED],
                 [case "$host_os" in openbsd* | aix* | *-android*) false;; *) true;; esac])
  gl_MUSL_LIBC
  gl_FUNC_LSEEK
  gl_CONDITIONAL([GL_COND_OBJ_LSEEK], [test $REPLACE_LSEEK = 1])
  gl_UNISTD_MODULE_INDICATOR([lseek])
  gl_MATH_H
  gl_MATH_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gl_WINDOWS_RC
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR_UTF8
  dnl Check for prerequisites for memory fence checks.
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_MEMSET_EXPLICIT
  gl_CONDITIONAL([GL_COND_OBJ_MEMSET_EXPLICIT],
                 [test $HAVE_MEMSET_EXPLICIT = 0 || test $REPLACE_MEMSET_EXPLICIT = 1])
  AM_COND_IF([GL_COND_OBJ_MEMSET_EXPLICIT], [
    gl_PREREQ_MEMSET_EXPLICIT
  ])
  gl_STRING_MODULE_INDICATOR([memset_explicit])
  gl_FUNC_MKFIFO
  gl_CONDITIONAL([GL_COND_OBJ_MKFIFO],
                 [test $HAVE_MKFIFO = 0 || test $REPLACE_MKFIFO = 1])
  gl_UNISTD_MODULE_INDICATOR([mkfifo])
  gl_FUNC_NANOSLEEP
  gl_CONDITIONAL([GL_COND_OBJ_NANOSLEEP],
                 [test $HAVE_NANOSLEEP = 0 || test $REPLACE_NANOSLEEP = 1])
  gl_TIME_MODULE_INDICATOR([nanosleep])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_HEADER_NETINET_IN
  gl_CONDITIONAL_HEADER([netinet/in.h])
  AC_PROG_MKDIR_P
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_FUNC_USELOCALE
  gl_MUSL_LIBC
  AC_CHECK_DECLS_ONCE([alarm])
  gl_FUNC_OPENDIR
  gl_CONDITIONAL([GL_COND_OBJ_OPENDIR],
                 [test $HAVE_OPENDIR = 0 || test $REPLACE_OPENDIR = 1])
  gl_DIRENT_MODULE_INDICATOR([opendir])
  gl_FUNC_PERROR
  gl_CONDITIONAL([GL_COND_OBJ_PERROR], [test $REPLACE_PERROR = 1])
  gl_STRING_MODULE_INDICATOR([perror])
  gl_FUNC_PIPE
  gl_CONDITIONAL([GL_COND_OBJ_PIPE], [test $HAVE_PIPE = 0])
  gl_UNISTD_MODULE_INDICATOR([pipe])
  gl_FUNC_PSELECT
  gl_CONDITIONAL([GL_COND_OBJ_PSELECT],
                 [test $HAVE_PSELECT = 0 || test $REPLACE_PSELECT = 1])
  gl_SYS_SELECT_MODULE_INDICATOR([pselect])
  AC_CHECK_HEADERS_ONCE([sys/wait.h])
  gl_PTHREAD_COND
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_COND],
                 [test $HAVE_PTHREAD_COND_INIT = 0 || test $REPLACE_PTHREAD_COND_INIT = 1])
  gl_PTHREAD_MODULE_INDICATOR([pthread-cond])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_PTHREAD_MUTEX
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_MUTEX],
                 [test $HAVE_PTHREAD_MUTEX_INIT = 0 || test $REPLACE_PTHREAD_MUTEX_INIT = 1 || test $HAVE_PTHREAD_MUTEXATTR_GETROBUST = 0 || test $REPLACE_PTHREAD_MUTEXATTR_GETROBUST = 1])
  gl_PTHREAD_MODULE_INDICATOR([pthread-mutex])
  AC_CHECK_HEADERS_ONCE([semaphore.h])
  AC_CHECK_DECLS_ONCE([alarm])
  AC_REQUIRE([gl_SEMAPHORE])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_PTHREAD_RWLOCK
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_RWLOCK],
                 [test $REPLACE_PTHREAD_RWLOCK_INIT = 1 || test $HAVE_PTHREAD_RWLOCK_TIMEDRDLOCK = 0 || test $REPLACE_PTHREAD_RWLOCK_TIMEDRDLOCK = 1])
  gl_PTHREAD_MODULE_INDICATOR([pthread-rwlock])
  AC_CHECK_HEADERS_ONCE([semaphore.h])
  AC_CHECK_DECLS_ONCE([alarm])
  AC_REQUIRE([gl_SEMAPHORE])
  gl_PTHREAD_THREAD
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_THREAD],
                 [test $HAVE_PTHREAD_CREATE = 0 || test $REPLACE_PTHREAD_CREATE = 1])
  gl_PTHREAD_MODULE_INDICATOR([pthread-thread])
  gl_FUNC_PTHREAD_MUTEX_TIMEDLOCK
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_MUTEX_TIMEDLOCK],
                 [test $HAVE_PTHREAD_T = 1 && test $HAVE_PTHREAD_MUTEX_TIMEDLOCK = 0])
  gl_PTHREAD_MODULE_INDICATOR([pthread_mutex_timedlock])
  gl_FUNC_PTHREAD_SIGMASK
  gl_CONDITIONAL([GL_COND_OBJ_PTHREAD_SIGMASK],
                 [test $HAVE_PTHREAD_SIGMASK = 0 || test $REPLACE_PTHREAD_SIGMASK = 1])
  AM_COND_IF([GL_COND_OBJ_PTHREAD_SIGMASK], [
    gl_PREREQ_PTHREAD_SIGMASK
  ])
  gl_SIGNAL_MODULE_INDICATOR([pthread_sigmask])
  gl_FUNC_PUTENV
  gl_CONDITIONAL([GL_COND_OBJ_PUTENV], [test $REPLACE_PUTENV = 1])
  AM_COND_IF([GL_COND_OBJ_PUTENV], [
    gl_PREREQ_PUTENV
  ])
  gl_STDLIB_MODULE_INDICATOR([putenv])
  dnl Check for prerequisites for memory fence checks.
  dnl FIXME: zerosize-ptr.h requires these: make a module for it
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_RAISE
  gl_CONDITIONAL([GL_COND_OBJ_RAISE],
                 [test $HAVE_RAISE = 0 || test $REPLACE_RAISE = 1])
  AM_COND_IF([GL_COND_OBJ_RAISE], [
    gl_PREREQ_RAISE
  ])
  gl_SIGNAL_MODULE_INDICATOR([raise])
  gl_FUNC_RANDOM
  gl_CONDITIONAL([GL_COND_OBJ_RANDOM],
                 [test $HAVE_RANDOM = 0 || test $REPLACE_RANDOM = 1 || test $REPLACE_INITSTATE = 1 || test $REPLACE_SETSTATE = 1])
  AM_COND_IF([GL_COND_OBJ_RANDOM], [
    gl_PREREQ_RANDOM
  ])
  gl_STDLIB_MODULE_INDICATOR([random])
  gl_FUNC_RANDOM_R
  gl_CONDITIONAL([GL_COND_OBJ_RANDOM_R],
                 [test $HAVE_RANDOM_R = 0 || test $REPLACE_RANDOM_R = 1])
  AM_COND_IF([GL_COND_OBJ_RANDOM_R], [
    gl_PREREQ_RANDOM_R
  ])
  gl_STDLIB_MODULE_INDICATOR([random_r])
  dnl Check for prerequisites for memory fence checks.
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_PREREQ_READ_FILE
  gl_FUNC_READDIR
  gl_CONDITIONAL([GL_COND_OBJ_READDIR],
                 [test $HAVE_READDIR = 0 || test $REPLACE_READDIR = 1])
  gl_DIRENT_MODULE_INDICATOR([readdir])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_FUNC_SCHED_YIELD
  gl_CONDITIONAL([GL_COND_OBJ_SCHED_YIELD],
                 [test $HAVE_SCHED_YIELD = 0 || test $REPLACE_SCHED_YIELD = 1])
  gl_SCHED_MODULE_INDICATOR([sched_yield])
  gl_FUNC_SELECT
  gl_CONDITIONAL([GL_COND_OBJ_SELECT], [test $REPLACE_SELECT = 1])
  gl_SYS_SELECT_MODULE_INDICATOR([select])
  gl_MODULE_INDICATOR([select])
  AC_CHECK_HEADERS_ONCE([sys/wait.h])
  gl_FUNC_SETENV
  gl_CONDITIONAL([GL_COND_OBJ_SETENV],
                 [test $HAVE_SETENV = 0 || test $REPLACE_SETENV = 1])
  gl_STDLIB_MODULE_INDICATOR([setenv])
  gl_FUNC_SETLOCALE
  gl_CONDITIONAL([GL_COND_OBJ_SETLOCALE], [test $REPLACE_SETLOCALE = 1])
  AM_COND_IF([GL_COND_OBJ_SETLOCALE], [
    gl_PREREQ_SETLOCALE
  ])
  gl_LOCALE_MODULE_INDICATOR([setlocale])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_SETLOCALE_FIXES],
                 [case "$host_os" in mingw* | windows* | *-android*) true;; *) false;; esac])
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  gl_WINDOWS_RC
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_SETSOCKOPT],
                 [test "$ac_cv_header_winsock2_h" = yes])
  gl_SYS_SOCKET_MODULE_INDICATOR([setsockopt])
  gl_MODULE_INDICATOR([setsockopt])
  gl_SIGNAL_H
  gl_SIGNAL_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SIGNBIT
  gl_CONDITIONAL([GL_COND_OBJ_SIGNBIT3], [test $REPLACE_SIGNBIT = 1])
  gl_MATH_MODULE_INDICATOR([signbit-no-cxx])
  gl_SIGNALBLOCKING
  gl_CONDITIONAL([GL_COND_OBJ_SIGPROCMASK], [test $HAVE_POSIX_SIGNALBLOCKING = 0])
  AM_COND_IF([GL_COND_OBJ_SIGPROCMASK], [
    gl_PREREQ_SIGPROCMASK
  ])
  gl_SIGNAL_MODULE_INDICATOR([sigprocmask])
  gl_FUNC_SLEEP
  gl_CONDITIONAL([GL_COND_OBJ_SLEEP],
                 [test $HAVE_SLEEP = 0 || test $REPLACE_SLEEP = 1])
  gl_UNISTD_MODULE_INDICATOR([sleep])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_SNAN
  gl_NAN_MIPS
  AC_REQUIRE([gl_SYS_SOCKET_H])
  gl_CONDITIONAL([GL_COND_OBJ_SOCKET], [test "$ac_cv_header_winsock2_h" = yes])
  # When this module is used, sockets may actually occur as file descriptors,
  # hence it is worth warning if the modules 'close' and 'ioctl' are not used.
  m4_ifdef([gl_UNISTD_H_DEFAULTS], [gl_UNISTD_H_REQUIRE_DEFAULTS])
  m4_ifdef([gl_SYS_IOCTL_H_DEFAULTS], [gl_SYS_IOCTL_H_REQUIRE_DEFAULTS])
  AC_REQUIRE([gl_PREREQ_SYS_H_WINSOCK2])
  if test "$ac_cv_header_winsock2_h" = yes; then
    UNISTD_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS=1
    SYS_IOCTL_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS=1
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([socket])
  gl_MODULE_INDICATOR([socket])
  AC_REQUIRE([gl_SOCKETLIB])
  AC_REQUIRE([gl_SOCKETS])
  gl_TYPE_SOCKLEN_T
  AC_REQUIRE([gt_TYPE_WINT_T])
  gl_DOUBLE_EXPONENT_LOCATION
  gl_FUNC_STPCPY
  gl_CONDITIONAL([GL_COND_OBJ_STPCPY],
                 [test $HAVE_STPCPY = 0 || test $REPLACE_STPCPY = 1])
  AM_COND_IF([GL_COND_OBJ_STPCPY], [
    gl_PREREQ_STPCPY
  ])
  gl_STRING_MODULE_INDICATOR([stpcpy])
  gl_STRING_MODULE_INDICATOR([str_endswith])
  gl_STRING_MODULE_INDICATOR([str_startswith])
  gl_FUNC_STRDUP_POSIX
  gl_CONDITIONAL([GL_COND_OBJ_STRDUP], [test $REPLACE_STRDUP = 1])
  AM_COND_IF([GL_COND_OBJ_STRDUP], [
    gl_PREREQ_STRDUP
  ])
  gl_STRING_MODULE_INDICATOR([strdup])
  gl_FUNC_STRERROR_R
  AS_IF([test $HAVE_DECL_STRERROR_R = 0 || test $REPLACE_STRERROR_R = 1], [
    AC_LIBOBJ([strerror_r])
    gl_PREREQ_STRERROR_R
  ])
  gl_STRING_MODULE_INDICATOR([strerror_r])
  dnl For the modules argp, error, xstrerror.
  gl_MODULE_INDICATOR([strerror_r-posix])
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_SYMLINK
  gl_CONDITIONAL([GL_COND_OBJ_SYMLINK],
                 [test $HAVE_SYMLINK = 0 || test $REPLACE_SYMLINK = 1])
  gl_UNISTD_MODULE_INDICATOR([symlink])
  gl_SYS_IOCTL_H
  gl_SYS_IOCTL_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SYS_SELECT_H
  gl_SYS_SELECT_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SYS_SOCKET_H
  gl_SYS_SOCKET_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  AC_CHECK_FUNCS_ONCE([shutdown])
  gl_SOCKET_FAMILIES
  gl_SOCKET_FAMILY_UNIX
  gl_SYS_TIME_H
  gl_SYS_TIME_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_SYS_UIO_H
  gl_SYS_UIO_H_REQUIRE_DEFAULTS
  AC_PROG_MKDIR_P
  gl_MUSL_LIBC
  gl_CONDITIONAL([LIBC_IS_GNU],
                 [case "$host_os" in *-gnu* | gnu*) true ;; *) false ;; esac])
  gl_CONDITIONAL([LIBC_IS_MUSL],
                 [case "$host_os" in *-musl* | midipix*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_MACOS],
                 [case "$host_os" in darwin*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_MACOS11],
                 [case "$host_os" in darwin20.*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_MACOS12],
                 [case "$host_os" in darwin21.*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_MACOS13],
                 [case "$host_os" in darwin22.*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_MACOS14],
                 [case "$host_os" in darwin23.*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_FREEBSD],
                 [case "$host_os" in freebsd* | dragonfly*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_NETBSD],
                 [case "$host_os" in netbsd*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_OPENBSD],
                 [case "$host_os" in openbsd*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_AIX],
                 [case "$host_os" in aix*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_SOLARIS11],
                 [case "$host_os" in solaris2.11*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_CYGWIN],
                 [case "$host_os" in cygwin*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_NATIVE_WINDOWS],
                 [case "$host_os" in mingw* | windows*) true ;; *) false ;; esac])
  is_mingw=false; is_msvc=false
  case "$host_os" in
    windows*-msvc*) is_msvc=true ;;
    mingw* | windows*)
      AC_EGREP_CPP([Special], [
  #ifdef _MSC_VER
   Special
  #endif
  ], [is_msvc=true], [is_mingw=true])
      ;;
  esac
  gl_CONDITIONAL([PLATFORM_IS_MINGW], [$is_mingw])
  gl_CONDITIONAL([PLATFORM_IS_MSVC], [$is_msvc])
  gl_CONDITIONAL([OS_IS_HAIKU],
                 [case "$host_os" in haiku*) true ;; *) false ;; esac])
  gl_CONDITIONAL([OS_IS_ANDROID],
                 [case "$host_os" in linux-androideabi*) true ;; *) false ;; esac])
  gl_THREAD
  AC_CHECK_HEADERS([sys/single_threaded.h])
  gl_FUNC_TIME
  gl_CONDITIONAL([GL_COND_OBJ_TIME], [test $REPLACE_TIME = 1])
  AM_COND_IF([GL_COND_OBJ_TIME], [
    gl_PREREQ_TIME
  ])
  gl_TIME_MODULE_INDICATOR([time])
  gl_FUNC_TRUNC
  gl_CONDITIONAL([GL_COND_OBJ_TRUNC],
                 [test $HAVE_DECL_TRUNC = 0 || test $REPLACE_TRUNC = 1])
  gl_MATH_MODULE_INDICATOR([trunc])
  gl_FUNC_TRUNCL
  gl_CONDITIONAL([GL_COND_OBJ_TRUNCL],
                 [test $HAVE_DECL_TRUNCL = 0 || test $REPLACE_TRUNCL = 1])
  gl_MATH_MODULE_INDICATOR([truncl])
  gl_FUNC_UNSETENV
  gl_CONDITIONAL([GL_COND_OBJ_UNSETENV],
                 [test $HAVE_UNSETENV = 0 || test $REPLACE_UNSETENV = 1])
  AM_COND_IF([GL_COND_OBJ_UNSETENV], [
    gl_PREREQ_UNSETENV
  ])
  gl_STDLIB_MODULE_INDICATOR([unsetenv])
  abs_aux_dir=`cd "$ac_aux_dir"; pwd`
  AC_SUBST([abs_aux_dir])
  abs_aux_dir=`cd "$ac_aux_dir"; pwd`
  AC_SUBST([abs_aux_dir])
  gl_FUNC_MMAP_ANON
  AC_REQUIRE([AC_C_INLINE])
  AC_CHECK_FUNCS_ONCE([mquery pstat_getprocvm])
  gt_LOCALE_EN_UTF8
  gt_LOCALE_FR
  gt_LOCALE_FR_UTF8
  gt_LOCALE_JA
  gt_LOCALE_ZH_CN
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_COND],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_SPIN],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_THREAD],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_TIMEDMUTEX],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_TIMEDRECMUTEX],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_TIMEDRWLOCK],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  AC_REQUIRE([AC_CANONICAL_HOST])
  gl_CONDITIONAL([GL_COND_OBJ_WINDOWS_TLS],
                 [case "$host_os" in mingw* | windows*) true;; *) false;; esac])
  gl_XGETCWD
  AC_REQUIRE([gl_YIELD])
  m4_popdef([gl_MODULE_INDICATOR_CONDITION])
  m4_ifval(gltests_LIBSOURCES_LIST, [
    m4_syscmd([test ! -d ]m4_defn([gltests_LIBSOURCES_DIR])[ ||
      for gl_file in ]gltests_LIBSOURCES_LIST[ ; do
        if test ! -r ]m4_defn([gltests_LIBSOURCES_DIR])[/$gl_file ; then
          echo "missing file ]m4_defn([gltests_LIBSOURCES_DIR])[/$gl_file" >&2
          exit 1
        fi
      done])dnl
      m4_if(m4_sysval, [0], [],
        [AC_FATAL([expected source file, required through AC_LIBSOURCES, not found])])
  ])
  m4_popdef([GL_MODULE_INDICATOR_PREFIX])
  m4_popdef([GL_MACRO_PREFIX])
  m4_popdef([gltests_LIBSOURCES_DIR])
  m4_popdef([gltests_LIBSOURCES_LIST])
  m4_popdef([AC_LIBSOURCES])
  m4_popdef([AC_REPLACE_FUNCS])
  m4_popdef([AC_LIBOBJ])
  AC_CONFIG_COMMANDS_PRE([
    gltests_libobjs=
    gltests_ltlibobjs=
    gltests_libobjdeps=
    gltests_libsed_libobjs=
    gltests_libsed_ltlibobjs=
    gltests_libsed_libobjdeps=
    if test -n "$gltests_LIBOBJS"; then
      # Remove the extension.
changequote(,)dnl
      sed_drop_objext='s/\.o$//;s/\.obj$//'
      sed_dirname1='s,//*,/,g'
      sed_dirname2='s,\(.\)/$,\1,'
      sed_dirname3='s,[^/]*$,,'
      sed_basename1='s,.*/,,'
changequote([, ])dnl
      for i in `for i in $gltests_LIBOBJS; do echo "$i"; done | sed -e "$sed_drop_objext" | sort | uniq`; do
        gltests_libobjs="$gltests_libobjs $i.$ac_objext"
        gltests_ltlibobjs="$gltests_ltlibobjs $i.lo"
        i_dir=`echo "$i" | sed -e "$sed_dirname1" -e "$sed_dirname2" -e "$sed_dirname3"`
        i_base=`echo "$i" | sed -e "$sed_basename1"`
        gltests_libsed_libobjs="$gltests_libsed_libobjs $i_dir""libsed_a-$i_base.$ac_objext"
        gltests_libsed_ltlibobjs="$gltests_libsed_ltlibobjs $i_dir""libsed_la-$i_base.lo"
        gltests_libobjdeps="$gltests_libobjdeps $i_dir\$(DEPDIR)/$i_base.Po"
        gltests_libsed_libobjdeps="$gltests_libsed_libobjdeps $i_dir\$(DEPDIR)/libsed_a-$i_base.Po"
      done
    fi
    AC_SUBST([gltests_LIBOBJS], [$gltests_libobjs])
    AC_SUBST([gltests_LTLIBOBJS], [$gltests_ltlibobjs])
    AC_SUBST([gltests_LIBOBJDEPS], [$gltests_libobjdeps])
    AC_SUBST([gltests_libsed_LIBOBJS], [$gltests_libsed_libobjs])
    AC_SUBST([gltests_libsed_LTLIBOBJS], [$gltests_libsed_ltlibobjs])
    AC_SUBST([gltests_libsed_LIBOBJDEPS], [$gltests_libsed_libobjdeps])
  ])
  AC_REQUIRE([gl_CC_GNULIB_WARNINGS])
  LIBSED_LIBDEPS="$gl_libdeps"
  AC_SUBST([LIBSED_LIBDEPS])
  LIBSED_LTLIBDEPS="$gl_ltlibdeps"
  AC_SUBST([LIBSED_LTLIBDEPS])
  LIBTESTS_LIBDEPS="$gltests_libdeps"
  AC_SUBST([LIBTESTS_LIBDEPS])
])

# Like AC_LIBOBJ, except that the module name goes
# into gl_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gl_LIBOBJ], [
  AS_LITERAL_IF([$1], [gl_LIBSOURCES([$1.c])])dnl
  gl_LIBOBJS="$gl_LIBOBJS $1.$ac_objext"
])

# Like AC_REPLACE_FUNCS, except that the module name goes
# into gl_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gl_REPLACE_FUNCS], [
  m4_foreach_w([gl_NAME], [$1], [AC_LIBSOURCES(gl_NAME[.c])])dnl
  AC_CHECK_FUNCS([$1], , [gl_LIBOBJ($ac_func)])
])

# Like AC_LIBSOURCES, except the directory where the source file is
# expected is derived from the gnulib-tool parameterization,
# and alloca is special cased (for the alloca-opt module).
# We could also entirely rely on EXTRA_lib..._SOURCES.
AC_DEFUN([gl_LIBSOURCES], [
  m4_foreach([_gl_NAME], [$1], [
    m4_if(_gl_NAME, [alloca.c], [], [
      m4_define([gl_LIBSOURCES_DIR], [lib])
      m4_append([gl_LIBSOURCES_LIST], _gl_NAME, [ ])
    ])
  ])
])

# Like AC_LIBOBJ, except that the module name goes
# into gltests_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gltests_LIBOBJ], [
  AS_LITERAL_IF([$1], [gltests_LIBSOURCES([$1.c])])dnl
  gltests_LIBOBJS="$gltests_LIBOBJS $1.$ac_objext"
])

# Like AC_REPLACE_FUNCS, except that the module name goes
# into gltests_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gltests_REPLACE_FUNCS], [
  m4_foreach_w([gl_NAME], [$1], [AC_LIBSOURCES(gl_NAME[.c])])dnl
  AC_CHECK_FUNCS([$1], , [gltests_LIBOBJ($ac_func)])
])

# Like AC_LIBSOURCES, except the directory where the source file is
# expected is derived from the gnulib-tool parameterization,
# and alloca is special cased (for the alloca-opt module).
# We could also entirely rely on EXTRA_lib..._SOURCES.
AC_DEFUN([gltests_LIBSOURCES], [
  m4_foreach([_gl_NAME], [$1], [
    m4_if(_gl_NAME, [alloca.c], [], [
      m4_define([gltests_LIBSOURCES_DIR], [gnulib-tests])
      m4_append([gltests_LIBSOURCES_LIST], _gl_NAME, [ ])
    ])
  ])
])

# This macro records the list of files which have been installed by
# gnulib-tool and may be removed by future gnulib-tool invocations.
AC_DEFUN([gl_FILE_LIST], [
  build-aux/announce-gen
  build-aux/do-release-commit-and-tag
  build-aux/gendocs.sh
  build-aux/git-version-gen
  build-aux/gitlog-to-changelog
  build-aux/gnu-web-doc-update
  build-aux/gnupload
  build-aux/update-copyright
  build-aux/useless-if-before-free
  build-aux/vc-list-files
  doc/gendocs_template
  doc/gendocs_template_min
  lib/_Noreturn.h
  lib/acl-errno-valid.c
  lib/acl-internal.c
  lib/acl-internal.h
  lib/acl.h
  lib/acl_entries.c
  lib/alloca.in.h
  lib/arg-nonnull.h
  lib/assert.in.h
  lib/attribute.h
  lib/basename-lgpl.c
  lib/basename-lgpl.h
  lib/binary-io.c
  lib/binary-io.h
  lib/btowc.c
  lib/c++defs.h
  lib/c-ctype.c
  lib/c-ctype.h
  lib/c-strcase.h
  lib/c-strcasecmp.c
  lib/c-strcaseeq.h
  lib/c32is-impl.h
  lib/c32isprint.c
  lib/c32isspace.c
  lib/c32rtomb.c
  lib/c32to-impl.h
  lib/c32tob.c
  lib/c32tolower.c
  lib/c32toupper.c
  lib/calloc.c
  lib/canonicalize-lgpl.c
  lib/cdefs.h
  lib/cloexec.c
  lib/cloexec.h
  lib/close.c
  lib/copy-acl.c
  lib/ctype.in.h
  lib/dfa.c
  lib/dfa.h
  lib/dirent.in.h
  lib/dirname-lgpl.c
  lib/dirname.h
  lib/dup2.c
  lib/dynarray.h
  lib/eloop-threshold.h
  lib/errno.in.h
  lib/error.c
  lib/error.in.h
  lib/exitfail.c
  lib/exitfail.h
  lib/fcntl.c
  lib/fcntl.in.h
  lib/fd-hook.c
  lib/fd-hook.h
  lib/file-has-acl.c
  lib/filename.h
  lib/flexmember.h
  lib/free.c
  lib/fseterr.c
  lib/fseterr.h
  lib/fstat.c
  lib/fwriting.c
  lib/fwriting.h
  lib/get-permissions.c
  lib/getdelim.c
  lib/getdtablesize.c
  lib/getfilecon.c
  lib/getopt-cdefs.in.h
  lib/getopt-core.h
  lib/getopt-ext.h
  lib/getopt-pfx-core.h
  lib/getopt-pfx-ext.h
  lib/getopt.c
  lib/getopt.in.h
  lib/getopt1.c
  lib/getopt_int.h
  lib/getprogname.c
  lib/getprogname.h
  lib/getrandom.c
  lib/gettext.h
  lib/glthread/lock.c
  lib/glthread/lock.h
  lib/glthread/once.c
  lib/glthread/once.h
  lib/glthread/threadlib.c
  lib/hard-locale.c
  lib/hard-locale.h
  lib/ialloc.c
  lib/ialloc.h
  lib/idx.h
  lib/ignore-value.h
  lib/intprops-internal.h
  lib/intprops.h
  lib/inttypes.in.h
  lib/issymlink.c
  lib/issymlink.h
  lib/iswblank.c
  lib/iswctype-impl.h
  lib/iswctype.c
  lib/iswdigit.c
  lib/iswpunct.c
  lib/iswxdigit.c
  lib/langinfo.in.h
  lib/lc-charset-dispatch.c
  lib/lc-charset-dispatch.h
  lib/libc-config.h
  lib/limits.in.h
  lib/localcharset.c
  lib/localcharset.h
  lib/locale.in.h
  lib/localeconv.c
  lib/localeinfo.c
  lib/localeinfo.h
  lib/lstat.c
  lib/malloc.c
  lib/malloc/dynarray-skeleton.c
  lib/malloc/dynarray.h
  lib/malloc/dynarray_at_failure.c
  lib/malloc/dynarray_emplace_enlarge.c
  lib/malloc/dynarray_finalize.c
  lib/malloc/dynarray_resize.c
  lib/malloc/dynarray_resize_clear.c
  lib/malloc/scratch_buffer.h
  lib/malloc/scratch_buffer_grow.c
  lib/malloc/scratch_buffer_grow_preserve.c
  lib/malloc/scratch_buffer_set_array_size.c
  lib/malloca.c
  lib/malloca.h
  lib/mbrtoc32.c
  lib/mbrtowc-impl-utf8.h
  lib/mbrtowc-impl.h
  lib/mbrtowc.c
  lib/mbsinit.c
  lib/mbszero.c
  lib/mbtowc-impl.h
  lib/mbtowc-lock.c
  lib/mbtowc-lock.h
  lib/mbtowc.c
  lib/memchr.c
  lib/memchr.valgrind
  lib/memeq.c
  lib/mempcpy.c
  lib/memrchr.c
  lib/minmax.h
  lib/mkdir.c
  lib/mkostemp.c
  lib/msvc-inval.c
  lib/msvc-inval.h
  lib/msvc-nothrow.c
  lib/msvc-nothrow.h
  lib/nl_langinfo-lock.c
  lib/nl_langinfo.c
  lib/obstack.c
  lib/obstack.in.h
  lib/open.c
  lib/pathmax.h
  lib/progname.c
  lib/progname.h
  lib/pthread-once.c
  lib/pthread.in.h
  lib/qcopy-acl.c
  lib/qset-acl.c
  lib/quote.h
  lib/quotearg.c
  lib/quotearg.h
  lib/rawmemchr.c
  lib/rawmemchr.valgrind
  lib/readlink.c
  lib/realloc.c
  lib/reallocarray.c
  lib/regcomp.c
  lib/regex.c
  lib/regex.h
  lib/regex_internal.c
  lib/regex_internal.h
  lib/regexec.c
  lib/rename.c
  lib/rmdir.c
  lib/same-inode.c
  lib/same-inode.h
  lib/sched.in.h
  lib/scratch_buffer.h
  lib/se-context.c
  lib/se-context.in.h
  lib/se-label.c
  lib/se-label.in.h
  lib/se-selinux.c
  lib/se-selinux.in.h
  lib/set-acl.c
  lib/set-permissions.c
  lib/setlocale-lock.c
  lib/setlocale_null-unlocked.c
  lib/setlocale_null.c
  lib/setlocale_null.h
  lib/stat-macros.h
  lib/stat-time.c
  lib/stat-time.h
  lib/stat-w32.c
  lib/stat-w32.h
  lib/stat.c
  lib/stdarg.in.h
  lib/stdckdint.in.h
  lib/stdcountof.in.h
  lib/stddef.in.h
  lib/stdint.in.h
  lib/stdio-consolesafe.c
  lib/stdio-impl.h
  lib/stdio-read.c
  lib/stdio-write.c
  lib/stdio.in.h
  lib/stdlib.c
  lib/stdlib.in.h
  lib/streq-opt.h
  lib/streq.c
  lib/strerror-override.c
  lib/strerror-override.h
  lib/strerror.c
  lib/string.in.h
  lib/stripslash.c
  lib/strncpy.c
  lib/strnul.c
  lib/strtoimax.c
  lib/strtol.c
  lib/strtoll.c
  lib/strverscmp.c
  lib/sys_random.in.h
  lib/sys_stat.in.h
  lib/sys_types.in.h
  lib/tempname.c
  lib/tempname.h
  lib/time.in.h
  lib/uchar.in.h
  lib/unicase.in.h
  lib/unicase/simple-mapping.h
  lib/unicase/tolower.c
  lib/unicase/tolower.h
  lib/unicase/toupper.c
  lib/unicase/toupper.h
  lib/unictype.in.h
  lib/unictype/bitmap.h
  lib/unictype/ctype_print.c
  lib/unictype/ctype_print.h
  lib/unictype/ctype_space.c
  lib/unictype/ctype_space.h
  lib/uninorm.in.h
  lib/unistd.c
  lib/unistd.in.h
  lib/unitypes.in.h
  lib/unlocked-io.h
  lib/verify.h
  lib/version-etc-fsf.c
  lib/version-etc.c
  lib/version-etc.h
  lib/warn-on-use.h
  lib/wchar.in.h
  lib/wcrtomb.c
  lib/wctob.c
  lib/wctomb-impl.h
  lib/wctomb.c
  lib/wctype-h.c
  lib/wctype-impl.h
  lib/wctype.c
  lib/wctype.in.h
  lib/windows-initguard.h
  lib/windows-mutex.c
  lib/windows-mutex.h
  lib/windows-once.c
  lib/windows-once.h
  lib/windows-recmutex.c
  lib/windows-recmutex.h
  lib/windows-rwlock.c
  lib/windows-rwlock.h
  lib/xalloc-die.c
  lib/xalloc-oversized.h
  lib/xalloc.h
  lib/xmalloc.c
  m4/00gnulib.m4
  m4/__inline.m4
  m4/absolute-header.m4
  m4/acl.m4
  m4/alloca.m4
  m4/arpa_inet_h.m4
  m4/assert.m4
  m4/assert_h.m4
  m4/btowc.m4
  m4/build-to-host.m4
  m4/builtin-expect.m4
  m4/c-bool.m4
  m4/c32rtomb.m4
  m4/calloc.m4
  m4/canonicalize.m4
  m4/clock_time.m4
  m4/close.m4
  m4/closedir.m4
  m4/codeset.m4
  m4/ctype_h.m4
  m4/dirent_h.m4
  m4/dirfd.m4
  m4/double-slash-root.m4
  m4/dup2.m4
  m4/environ.m4
  m4/errno_h.m4
  m4/error.m4
  m4/error_h.m4
  m4/exponentd.m4
  m4/exponentf.m4
  m4/exponentl.m4
  m4/extensions-aix.m4
  m4/extensions.m4
  m4/extern-inline.m4
  m4/fclose.m4
  m4/fcntl-o.m4
  m4/fcntl.m4
  m4/fcntl_h.m4
  m4/fdopen.m4
  m4/fflush.m4
  m4/flexmember.m4
  m4/float_h.m4
  m4/fopen.m4
  m4/fpieee.m4
  m4/fpurge.m4
  m4/freading.m4
  m4/free.m4
  m4/frexp.m4
  m4/frexpl.m4
  m4/fseek.m4
  m4/fseeko.m4
  m4/fseterr.m4
  m4/fstat.m4
  m4/ftell.m4
  m4/ftello.m4
  m4/ftruncate.m4
  m4/fwriting.m4
  m4/getcwd.m4
  m4/getdelim.m4
  m4/getdtablesize.m4
  m4/getlocalename_l.m4
  m4/getopt.m4
  m4/getpagesize.m4
  m4/getprogname.m4
  m4/getrandom.m4
  m4/gettext_h.m4
  m4/gettimeofday.m4
  m4/gnulib-common.m4
  m4/gnulib-i18n.m4
  m4/include_next.m4
  m4/inet_pton.m4
  m4/init-package-version.m4
  m4/intl-thread-locale.m4
  m4/intlmacosx.m4
  m4/inttypes.m4
  m4/ioctl.m4
  m4/isblank.m4
  m4/isnand.m4
  m4/isnanf.m4
  m4/isnanl.m4
  m4/iswblank.m4
  m4/iswctype.m4
  m4/iswdigit.m4
  m4/iswpunct.m4
  m4/iswxdigit.m4
  m4/langinfo_h.m4
  m4/largefile.m4
  m4/lcmessage.m4
  m4/libunistring-base.m4
  m4/limits-h.m4
  m4/link.m4
  m4/localcharset.m4
  m4/locale-en.m4
  m4/locale-fr.m4
  m4/locale-ja.m4
  m4/locale-tr.m4
  m4/locale-zh.m4
  m4/locale_h.m4
  m4/localeconv.m4
  m4/localename.m4
  m4/lock.m4
  m4/lseek.m4
  m4/lstat.m4
  m4/malloc.m4
  m4/malloca.m4
  m4/manywarnings-c++.m4
  m4/manywarnings.m4
  m4/math_h.m4
  m4/mbrtoc32.m4
  m4/mbrtowc.m4
  m4/mbsinit.m4
  m4/mbstate_t.m4
  m4/mbtowc.m4
  m4/memchr.m4
  m4/memeq.m4
  m4/mempcpy.m4
  m4/memrchr.m4
  m4/memset_explicit.m4
  m4/minmax.m4
  m4/mkdir.m4
  m4/mkfifo.m4
  m4/mkostemp.m4
  m4/mmap-anon.m4
  m4/mode_t.m4
  m4/msvc-inval.m4
  m4/msvc-nothrow.m4
  m4/multiarch.m4
  m4/musl.m4
  m4/nan-mips.m4
  m4/nanosleep.m4
  m4/netinet_in_h.m4
  m4/nl_langinfo.m4
  m4/nocrash.m4
  m4/obstack.m4
  m4/off64_t.m4
  m4/off_t.m4
  m4/once.m4
  m4/open-cloexec.m4
  m4/open-slash.m4
  m4/open.m4
  m4/opendir.m4
  m4/pathmax.m4
  m4/perl.m4
  m4/perror.m4
  m4/pid_t.m4
  m4/pipe.m4
  m4/pselect.m4
  m4/pthread-cond.m4
  m4/pthread-mutex.m4
  m4/pthread-once.m4
  m4/pthread-rwlock.m4
  m4/pthread-spin.m4
  m4/pthread-thread.m4
  m4/pthread_h.m4
  m4/pthread_mutex_timedlock.m4
  m4/pthread_rwlock_rdlock.m4
  m4/pthread_sigmask.m4
  m4/putenv.m4
  m4/quote.m4
  m4/quotearg.m4
  m4/raise.m4
  m4/random.m4
  m4/random_r.m4
  m4/rawmemchr.m4
  m4/read-file.m4
  m4/readdir.m4
  m4/readlink.m4
  m4/realloc.m4
  m4/reallocarray.m4
  m4/regex.m4
  m4/rename.m4
  m4/rmdir.m4
  m4/sched_h.m4
  m4/sched_yield.m4
  m4/select.m4
  m4/selinux-context-h.m4
  m4/selinux-label-h.m4
  m4/selinux-selinux-h.m4
  m4/semaphore.m4
  m4/setenv.m4
  m4/setlocale.m4
  m4/setlocale_null.m4
  m4/signal_h.m4
  m4/signalblocking.m4
  m4/signbit.m4
  m4/sleep.m4
  m4/snan.m4
  m4/socketlib.m4
  m4/sockets.m4
  m4/socklen.m4
  m4/sockpfaf.m4
  m4/ssize_t.m4
  m4/stat-time.m4
  m4/stat.m4
  m4/std-gnu11.m4
  m4/stdalign.m4
  m4/stdarg.m4
  m4/stdckdint_h.m4
  m4/stdcountof_h.m4
  m4/stddef_h.m4
  m4/stdint.m4
  m4/stdio_h.m4
  m4/stdlib_h.m4
  m4/stpcpy.m4
  m4/strdup.m4
  m4/streq.m4
  m4/strerror.m4
  m4/strerror_r.m4
  m4/string_h.m4
  m4/strncpy.m4
  m4/strtoimax.m4
  m4/strtoll.m4
  m4/strverscmp.m4
  m4/symlink.m4
  m4/sys_cdefs_h.m4
  m4/sys_ioctl_h.m4
  m4/sys_random_h.m4
  m4/sys_select_h.m4
  m4/sys_socket_h.m4
  m4/sys_stat_h.m4
  m4/sys_time_h.m4
  m4/sys_types_h.m4
  m4/sys_uio_h.m4
  m4/tempname.m4
  m4/thread.m4
  m4/threadlib.m4
  m4/time.m4
  m4/time_h.m4
  m4/trunc.m4
  m4/truncl.m4
  m4/uchar_h.m4
  m4/ungetc.m4
  m4/unicase_h.m4
  m4/unictype_h.m4
  m4/uninorm_h.m4
  m4/unistd_h.m4
  m4/unitypes_h.m4
  m4/unlocked-io.m4
  m4/vararrays.m4
  m4/version-etc.m4
  m4/visibility.m4
  m4/warn-on-use.m4
  m4/warnings.m4
  m4/wchar_h.m4
  m4/wcrtomb.m4
  m4/wctob.m4
  m4/wctomb.m4
  m4/wctype.m4
  m4/wctype_h.m4
  m4/windows-rc.m4
  m4/wint_t.m4
  m4/xalloc.m4
  m4/xattr.m4
  m4/xgetcwd.m4
  m4/yield.m4
  m4/zzgnulib.m4
  tests/atomic-int-posix.h
  tests/infinity.h
  tests/init.sh
  tests/locale.c
  tests/macros.h
  tests/minus-zero.h
  tests/nap.h
  tests/null-ptr.h
  tests/randomd.c
  tests/randoml.c
  tests/signature.h
  tests/test-accept.c
  tests/test-alignasof.c
  tests/test-alloca-opt.c
  tests/test-arpa_inet-h.c
  tests/test-assert.c
  tests/test-binary-io.c
  tests/test-binary-io.sh
  tests/test-bind.c
  tests/test-bool.c
  tests/test-btoc32-1.sh
  tests/test-btoc32-2.sh
  tests/test-btoc32-3.sh
  tests/test-btoc32.c
  tests/test-btowc-1.sh
  tests/test-btowc-2.sh
  tests/test-btowc-3.sh
  tests/test-btowc.c
  tests/test-c-ctype.c
  tests/test-c-strcasecmp.c
  tests/test-c-strcasecmp.sh
  tests/test-c-strcasestr.c
  tests/test-c-strncasecmp.c
  tests/test-c-strncasecmp.sh
  tests/test-c32isprint.c
  tests/test-c32isprint.sh
  tests/test-c32isspace.c
  tests/test-c32isspace.sh
  tests/test-c32rtomb-w32-2.sh
  tests/test-c32rtomb-w32-3.sh
  tests/test-c32rtomb-w32-4.sh
  tests/test-c32rtomb-w32-5.sh
  tests/test-c32rtomb-w32-6.sh
  tests/test-c32rtomb-w32-7.sh
  tests/test-c32rtomb-w32-8.sh
  tests/test-c32rtomb-w32.c
  tests/test-c32rtomb.c
  tests/test-c32rtomb.sh
  tests/test-c32tolower.c
  tests/test-c32tolower.sh
  tests/test-c32toupper.c
  tests/test-c32toupper.sh
  tests/test-calloc-gnu.c
  tests/test-calloc-posix.c
  tests/test-canonicalize-lgpl.c
  tests/test-chdir.c
  tests/test-cloexec.c
  tests/test-close.c
  tests/test-connect.c
  tests/test-copy-acl-1.sh
  tests/test-copy-acl-2.sh
  tests/test-copy-acl.c
  tests/test-copy-acl.sh
  tests/test-ctype-h.c
  tests/test-dfa-invalid-char-class.sh
  tests/test-dfa-invalid-merge.sh
  tests/test-dfa-match-aux.c
  tests/test-dfa-match.sh
  tests/test-dirent-h.c
  tests/test-dirfd.c
  tests/test-dup2.c
  tests/test-dynarray.c
  tests/test-environ.c
  tests/test-errno-h.c
  tests/test-error.c
  tests/test-error.sh
  tests/test-fcntl-h.c
  tests/test-fcntl.c
  tests/test-fdopen.c
  tests/test-fflush.c
  tests/test-fflush2.c
  tests/test-fflush2.sh
  tests/test-fgetc.c
  tests/test-file-has-acl-1.sh
  tests/test-file-has-acl-2.sh
  tests/test-file-has-acl.c
  tests/test-file-has-acl.sh
  tests/test-float-h.c
  tests/test-fopen-gnu.c
  tests/test-fopen.c
  tests/test-fopen.h
  tests/test-fpurge.c
  tests/test-fputc.c
  tests/test-fread.c
  tests/test-freading.c
  tests/test-free.c
  tests/test-frexp.c
  tests/test-frexp.h
  tests/test-frexpl.c
  tests/test-fseek.c
  tests/test-fseek.sh
  tests/test-fseek2.sh
  tests/test-fseeko.c
  tests/test-fseeko.sh
  tests/test-fseeko2.sh
  tests/test-fseeko3.c
  tests/test-fseeko3.sh
  tests/test-fseeko4.c
  tests/test-fseeko4.sh
  tests/test-fseterr.c
  tests/test-fstat.c
  tests/test-ftell.c
  tests/test-ftell.sh
  tests/test-ftell2.sh
  tests/test-ftell3.c
  tests/test-ftello.c
  tests/test-ftello.sh
  tests/test-ftello2.sh
  tests/test-ftello3.c
  tests/test-ftello4.c
  tests/test-ftello4.sh
  tests/test-ftruncate.c
  tests/test-ftruncate.sh
  tests/test-fwrite.c
  tests/test-fwriting.c
  tests/test-getcwd-lgpl.c
  tests/test-getdelim.c
  tests/test-getdtablesize.c
  tests/test-getopt-gnu.c
  tests/test-getopt-main.h
  tests/test-getopt-posix.c
  tests/test-getopt.h
  tests/test-getopt_long.h
  tests/test-getprogname.c
  tests/test-getrandom.c
  tests/test-gettext-h.c
  tests/test-gettimeofday.c
  tests/test-hard-locale.c
  tests/test-ignore-value.c
  tests/test-inet_pton.c
  tests/test-init.sh
  tests/test-intprops.c
  tests/test-inttypes-h.c
  tests/test-ioctl.c
  tests/test-isblank.c
  tests/test-isnand-nolibm.c
  tests/test-isnand.h
  tests/test-isnanf-nolibm.c
  tests/test-isnanf.h
  tests/test-isnanl-nolibm.c
  tests/test-isnanl.h
  tests/test-iswblank.c
  tests/test-iswctype.c
  tests/test-iswdigit.c
  tests/test-iswdigit.sh
  tests/test-iswpunct.c
  tests/test-iswpunct.sh
  tests/test-iswxdigit.c
  tests/test-iswxdigit.sh
  tests/test-langinfo-h.c
  tests/test-largefile.c
  tests/test-limits-h.c
  tests/test-link.c
  tests/test-link.h
  tests/test-listen.c
  tests/test-localcharset-w32utf8.c
  tests/test-localcharset-w32utf8.sh
  tests/test-localcharset.c
  tests/test-locale-h.c
  tests/test-localeconv-mt.c
  tests/test-localeconv.c
  tests/test-localename-w32utf8.c
  tests/test-localename-w32utf8.sh
  tests/test-localename.c
  tests/test-lseek.c
  tests/test-lseek.sh
  tests/test-lstat.c
  tests/test-lstat.h
  tests/test-malloc-gnu.c
  tests/test-malloc-posix.c
  tests/test-malloca.c
  tests/test-math-h.c
  tests/test-mbrtoc32-1.sh
  tests/test-mbrtoc32-2.sh
  tests/test-mbrtoc32-3.sh
  tests/test-mbrtoc32-4.sh
  tests/test-mbrtoc32-5.sh
  tests/test-mbrtoc32-regular.c
  tests/test-mbrtoc32-w32-2.sh
  tests/test-mbrtoc32-w32-3.sh
  tests/test-mbrtoc32-w32-4.sh
  tests/test-mbrtoc32-w32-5.sh
  tests/test-mbrtoc32-w32-6.sh
  tests/test-mbrtoc32-w32-7.sh
  tests/test-mbrtoc32-w32-8.sh
  tests/test-mbrtoc32-w32.c
  tests/test-mbrtoc32.c
  tests/test-mbrtowc-1.sh
  tests/test-mbrtowc-2.sh
  tests/test-mbrtowc-3.sh
  tests/test-mbrtowc-4.sh
  tests/test-mbrtowc-5.sh
  tests/test-mbrtowc-w32-2.sh
  tests/test-mbrtowc-w32-3.sh
  tests/test-mbrtowc-w32-4.sh
  tests/test-mbrtowc-w32-5.sh
  tests/test-mbrtowc-w32-6.sh
  tests/test-mbrtowc-w32-7.sh
  tests/test-mbrtowc-w32-8.sh
  tests/test-mbrtowc-w32.c
  tests/test-mbrtowc-w32utf8.c
  tests/test-mbrtowc-w32utf8.sh
  tests/test-mbrtowc.c
  tests/test-mbsinit.c
  tests/test-mbsinit.sh
  tests/test-memchr.c
  tests/test-memrchr.c
  tests/test-memset_explicit.c
  tests/test-mkdir.c
  tests/test-mkdir.h
  tests/test-mkfifo.c
  tests/test-mkfifo.h
  tests/test-nanosleep.c
  tests/test-netinet_in-h.c
  tests/test-nl_langinfo-mt.c
  tests/test-nl_langinfo1.c
  tests/test-nl_langinfo1.sh
  tests/test-nl_langinfo2.c
  tests/test-nl_langinfo2.sh
  tests/test-once.c
  tests/test-open.c
  tests/test-open.h
  tests/test-pathmax.c
  tests/test-perror.c
  tests/test-perror.sh
  tests/test-perror2.c
  tests/test-pipe.c
  tests/test-pselect.c
  tests/test-pthread-cond.c
  tests/test-pthread-mutex-type.c
  tests/test-pthread-mutex.c
  tests/test-pthread-once1.c
  tests/test-pthread-once2.c
  tests/test-pthread-rwlock.c
  tests/test-pthread-thread.c
  tests/test-pthread.c
  tests/test-pthread_sigmask1.c
  tests/test-pthread_sigmask2.c
  tests/test-putenv.c
  tests/test-quotearg-simple.c
  tests/test-quotearg.h
  tests/test-raise.c
  tests/test-random-mt.c
  tests/test-random.c
  tests/test-random_r.c
  tests/test-rawmemchr.c
  tests/test-read-file.c
  tests/test-readlink.c
  tests/test-readlink.h
  tests/test-realloc-posix.c
  tests/test-reallocarray.c
  tests/test-regex.c
  tests/test-rename.c
  tests/test-rename.h
  tests/test-rmdir.c
  tests/test-rmdir.h
  tests/test-sameacls.c
  tests/test-sched-h.c
  tests/test-scratch-buffer.c
  tests/test-select-fd.c
  tests/test-select-in.sh
  tests/test-select-out.sh
  tests/test-select-stdin.c
  tests/test-select.c
  tests/test-select.h
  tests/test-selinux-context-h.c
  tests/test-selinux-label-h.c
  tests/test-selinux-selinux-h.c
  tests/test-set-mode-acl-1.sh
  tests/test-set-mode-acl-2.sh
  tests/test-set-mode-acl.c
  tests/test-set-mode-acl.sh
  tests/test-setenv.c
  tests/test-setlocale-w32.c
  tests/test-setlocale-w32utf8.c
  tests/test-setlocale-w32utf8.sh
  tests/test-setlocale1.c
  tests/test-setlocale1.sh
  tests/test-setlocale2.c
  tests/test-setlocale2.sh
  tests/test-setlocale_null-mt-all.c
  tests/test-setlocale_null-mt-one.c
  tests/test-setlocale_null-unlocked.c
  tests/test-setlocale_null.c
  tests/test-setsockopt.c
  tests/test-signal-h.c
  tests/test-signbit.c
  tests/test-sigprocmask.c
  tests/test-sleep.c
  tests/test-sockets.c
  tests/test-stat-time.c
  tests/test-stat.c
  tests/test-stat.h
  tests/test-stdckdint-h.c
  tests/test-stdcountof-h.c
  tests/test-stddef-h.c
  tests/test-stdint-h.c
  tests/test-stdio-h.c
  tests/test-stdlib-h.c
  tests/test-str_endswith.c
  tests/test-str_startswith.c
  tests/test-strerror.c
  tests/test-strerror_r.c
  tests/test-string-h.c
  tests/test-strncpy.c
  tests/test-strnul.c
  tests/test-strtoimax.c
  tests/test-strtoll.c
  tests/test-strverscmp.c
  tests/test-symlink.c
  tests/test-symlink.h
  tests/test-sys_ioctl-h.c
  tests/test-sys_random-h.c
  tests/test-sys_select-h.c
  tests/test-sys_socket-h.c
  tests/test-sys_stat-h.c
  tests/test-sys_time-h.c
  tests/test-sys_types-h.c
  tests/test-sys_uio-h.c
  tests/test-sys_wait-h.h
  tests/test-thread_create.c
  tests/test-thread_self.c
  tests/test-time-h.c
  tests/test-time.c
  tests/test-trunc1.c
  tests/test-trunc2.c
  tests/test-truncl.c
  tests/test-uchar-h.c
  tests/test-unistd-h.c
  tests/test-unsetenv.c
  tests/test-update-copyright.sh
  tests/test-vc-list-files-cvs.sh
  tests/test-vc-list-files-git.sh
  tests/test-verify-try.c
  tests/test-verify.c
  tests/test-verify.sh
  tests/test-version-etc.c
  tests/test-version-etc.sh
  tests/test-wchar-h.c
  tests/test-wcrtomb-w32-2.sh
  tests/test-wcrtomb-w32-3.sh
  tests/test-wcrtomb-w32-4.sh
  tests/test-wcrtomb-w32-5.sh
  tests/test-wcrtomb-w32-6.sh
  tests/test-wcrtomb-w32-7.sh
  tests/test-wcrtomb-w32-8.sh
  tests/test-wcrtomb-w32.c
  tests/test-wcrtomb.c
  tests/test-wcrtomb.sh
  tests/test-wctype-h.c
  tests/test-wctype.c
  tests/test-windows-mutex-type.c
  tests/test-windows-recmutex-type.c
  tests/test-windows-timedmutex-type.c
  tests/test-windows-timedrecmutex-type.c
  tests/test-xalloc-die.c
  tests/test-xalloc-die.sh
  tests/unicase/test-mapping-part1.h
  tests/unicase/test-mapping-part2.h
  tests/unicase/test-uc_tolower.c
  tests/unicase/test-uc_toupper.c
  tests/unicase/test-unicase-h.c
  tests/unictype/test-ctype_print.c
  tests/unictype/test-ctype_space.c
  tests/unictype/test-predicate-part1.h
  tests/unictype/test-predicate-part2.h
  tests/unictype/test-unictype-h.c
  tests/uninorm/test-uninorm-h.c
  tests/virtualbox.h
  tests/windows-utf8.manifest
  tests/windows-utf8.rc
  tests/zerosize-ptr.h
  tests=lib/_Noreturn.h
  tests=lib/accept.c
  tests=lib/alloca.c
  tests=lib/arg-nonnull.h
  tests=lib/arpa_inet.c
  tests=lib/arpa_inet.in.h
  tests=lib/bind.c
  tests=lib/btoc32.c
  tests=lib/c++defs.h
  tests=lib/c-strcase.h
  tests=lib/c-strcasestr.c
  tests=lib/c-strcasestr.h
  tests=lib/c-strncasecmp.c
  tests=lib/closedir.c
  tests=lib/concat-filename.c
  tests=lib/concat-filename.h
  tests=lib/connect.c
  tests=lib/dirent-private.h
  tests=lib/dirfd.c
  tests=lib/fdopen.c
  tests=lib/fflush.c
  tests=lib/float+.h
  tests=lib/float.c
  tests=lib/float.in.h
  tests=lib/fopen.c
  tests=lib/fpucw.h
  tests=lib/fpurge.c
  tests=lib/freading.c
  tests=lib/freading.h
  tests=lib/frexp.c
  tests=lib/frexpl.c
  tests=lib/fseek.c
  tests=lib/fseeko.c
  tests=lib/ftell.c
  tests=lib/ftello.c
  tests=lib/ftruncate.c
  tests=lib/getcwd-lgpl.c
  tests=lib/getlocalename_l-unsafe.c
  tests=lib/getlocalename_l-unsafe.h
  tests=lib/getpagesize.c
  tests=lib/gettimeofday.c
  tests=lib/glthread/thread.c
  tests=lib/glthread/thread.h
  tests=lib/glthread/yield.h
  tests=lib/inet_pton.c
  tests=lib/ioctl.c
  tests=lib/isblank.c
  tests=lib/isnan.c
  tests=lib/isnand-nolibm.h
  tests=lib/isnand.c
  tests=lib/isnanf-nolibm.h
  tests=lib/isnanf.c
  tests=lib/isnanl-nolibm.h
  tests=lib/isnanl.c
  tests=lib/itold.c
  tests=lib/link.c
  tests=lib/listen.c
  tests=lib/localename-environ.c
  tests=lib/localename-table.c
  tests=lib/localename-table.h
  tests=lib/localename-unsafe.c
  tests=lib/localename.c
  tests=lib/localename.h
  tests=lib/lseek.c
  tests=lib/math.c
  tests=lib/math.in.h
  tests=lib/memset_explicit.c
  tests=lib/mkfifo.c
  tests=lib/nan.h
  tests=lib/nanosleep.c
  tests=lib/netinet_in.in.h
  tests=lib/opendir.c
  tests=lib/perror.c
  tests=lib/pipe.c
  tests=lib/pselect.c
  tests=lib/pthread-cond.c
  tests=lib/pthread-mutex.c
  tests=lib/pthread-rwlock.c
  tests=lib/pthread-thread.c
  tests=lib/pthread_mutex_timedlock.c
  tests=lib/pthread_sigmask.c
  tests=lib/putenv.c
  tests=lib/raise.c
  tests=lib/random.c
  tests=lib/random_r.c
  tests=lib/read-file.c
  tests=lib/read-file.h
  tests=lib/readdir.c
  tests=lib/sched_yield.c
  tests=lib/select.c
  tests=lib/setenv.c
  tests=lib/setlocale-fixes.c
  tests=lib/setlocale-fixes.h
  tests=lib/setlocale.c
  tests=lib/setsockopt.c
  tests=lib/signal.in.h
  tests=lib/signbitd.c
  tests=lib/signbitf.c
  tests=lib/signbitl.c
  tests=lib/signed-nan.h
  tests=lib/signed-snan.h
  tests=lib/sigprocmask.c
  tests=lib/sleep.c
  tests=lib/snan.h
  tests=lib/socket.c
  tests=lib/sockets.c
  tests=lib/sockets.h
  tests=lib/stdio-impl.h
  tests=lib/stpcpy.c
  tests=lib/str-two-way.h
  tests=lib/str_endswith.c
  tests=lib/str_startswith.c
  tests=lib/strdup.c
  tests=lib/strerror_r.c
  tests=lib/struniq.h
  tests=lib/symlink.c
  tests=lib/sys_ioctl.in.h
  tests=lib/sys_select.in.h
  tests=lib/sys_socket.c
  tests=lib/sys_socket.in.h
  tests=lib/sys_time.in.h
  tests=lib/sys_uio.in.h
  tests=lib/thread-optim.h
  tests=lib/time.c
  tests=lib/trunc.c
  tests=lib/truncl.c
  tests=lib/unsetenv.c
  tests=lib/vma-iter.c
  tests=lib/vma-iter.h
  tests=lib/w32sock.h
  tests=lib/warn-on-use.h
  tests=lib/windows-cond.c
  tests=lib/windows-cond.h
  tests=lib/windows-initguard.h
  tests=lib/windows-spin.c
  tests=lib/windows-spin.h
  tests=lib/windows-thread.c
  tests=lib/windows-thread.h
  tests=lib/windows-timedmutex.c
  tests=lib/windows-timedmutex.h
  tests=lib/windows-timedrecmutex.c
  tests=lib/windows-timedrecmutex.h
  tests=lib/windows-timedrwlock.c
  tests=lib/windows-timedrwlock.h
  tests=lib/windows-tls.c
  tests=lib/windows-tls.h
  tests=lib/xconcat-filename.c
  tests=lib/xgetcwd.c
  tests=lib/xgetcwd.h
  top/GNUmakefile
  top/README-release
  top/maint.mk
])
